"""Go 代码生成器 — 从意图 IR 生成 Go 策略代码。

目标: backend/strategy/sdk/ 接口。
"""

from __future__ import annotations

from typing import List

from tools.mql_migration.intent_ir import (
    CloseAction,
    EntryRule,
    ExecutionKind,
    ExitRule,
    ExitTrigger,
    IndicatorSpec,
    OrderAction,
    ParamSpec,
    ParamType,
    SizingKind,
    StrategyIntent,
    TimerRule,
)


class GoCodeGenerator:
    """从意图 IR 生成 Go SDK 策略代码。"""

    def __init__(self):
        self._lines: List[str] = []
        self._indent = 0

    def generate(self, intent: StrategyIntent) -> str:
        self._lines = []
        self._indent = 0

        self._gen_header(intent)
        self._gen_struct(intent)
        self._gen_on_init(intent)
        self._gen_on_bar(intent)
        if intent.timer:
            self._gen_on_timer(intent.timer)
        self._gen_on_deinit(intent)
        self._gen_helpers(intent)

        return "\n".join(self._lines)

    # ── Header ─────────────────────────────────────────────────────

    def _gen_header(self, intent: StrategyIntent) -> None:
        name = intent.meta.name or "ImportedStrategy"
        pkg = _go_pkg_name(name)
        self._emit("// Code generated by ant migration engine. DO NOT EDIT.")
        self._emit(f"// Source: {intent.meta.mql_version.value} strategy")
        self._emit(f"package {pkg}")
        self._emit()
        self._emit("import (")
        self._indent += 1
        self._emit('"github.com/shopspring/decimal"')
        self._emit('"anttrader/strategy/sdk"')
        self._indent -= 1
        self._emit(")")
        self._emit()

    # ── Struct ────────────────────────────────────────────────────

    def _gen_struct(self, intent: StrategyIntent) -> None:
        name = intent.meta.name or "ImportedStrategy"
        self._emit(f"// {name} is an imported {intent.meta.mql_version.value} strategy.")
        self._emit(f"type {name} struct {{")
        self._indent += 1
        # State variables
        for sv in intent.state:
            go_type = _mql_to_go_type(sv.var_type)
            self._emit(f"{_go_var_name(sv.name)} {go_type}")
        # Internal trading state
        self._emit("magic int32")
        self._emit("lotSize decimal.Decimal")
        self._emit("hedging bool")
        self._indent -= 1
        self._emit("}")
        self._emit()
        # Verify interface
        self._emit(f"var _ sdk.Strategy = (*{name})(nil)")
        self._emit()

    # ── on_init ──────────────────────────────────────────────────

    def _gen_on_init(self, intent: StrategyIntent) -> None:
        name = intent.meta.name or "ImportedStrategy"
        self._emit(f"func (s *{name}) OnInit(ctx sdk.Context) error {{")
        self._indent += 1

        # Parameters
        for p in intent.params:
            self._emit_param(p)

        # Timer
        if intent.timer:
            self._emit(f"ctx.SetTimer({intent.timer.interval_seconds})")

        # Account mode
        self._emit("s.hedging = ctx.Mode() == sdk.ModeHedging")
        self._emit("s.lotSize = s._lotSize")

        self._emit("return nil")
        self._indent -= 1
        self._emit("}")
        self._emit()

    # ── on_bar ──────────────────────────────────────────────────

    def _gen_on_bar(self, intent: StrategyIntent) -> None:
        name = intent.meta.name or "ImportedStrategy"
        self._emit(f"func (s *{name}) OnBar(ctx sdk.Context, tf string) (*sdk.Signal, error) {{")
        self._indent += 1

        if intent.execution.kind == ExecutionKind.ON_BAR:
            self._emit("if tf != ctx.Timeframe() {")
            self._emit("    return nil, nil")
            self._emit("}")

        self._emit("bars := ctx.Bars()")
        self._emit("_ = bars")
        self._emit()

        # Indicator computations
        for spec in intent.indicators:
            self._emit_indicator(spec, intent)

        # Exits before entries
        for exit_rule in intent.exit:
            self._gen_exit(exit_rule)

        # Entries
        for entry in intent.entry:
            self._gen_entry(entry, intent)

        self._emit("return nil, nil")
        self._indent -= 1
        self._emit("}")
        self._emit()

    # ── Entry ────────────────────────────────────────────────────

    def _gen_entry(self, entry: EntryRule, intent: StrategyIntent) -> None:
        cond_parts = [c.expr for c in entry.conditions if c.expr]
        if cond_parts:
            cond = " && ".join(cond_parts)
            self._emit(f"if {cond} {{")
            self._indent += 1

        sig_type = _go_signal_action(entry.action)
        volume = entry.order_params.volume or "s.lotSize"
        magic = entry.order_params.magic or "s.magic"
        fill := _go_fill_policy(entry.action)

        self._emit(f"sig := &sdk.Signal{{")
        self._emit(f"    Action: {sig_type},")
        self._emit(f"    Volume: {volume},")
        if entry.order_params.sl and entry.order_params.sl not in ("0", "0.0", ""):
            self._emit(f"    StopLoss: {entry.order_params.sl},")
        if entry.order_params.tp and entry.order_params.tp not in ("0", "0.0", ""):
            self._emit(f"    TakeProfit: {entry.order_params.tp},")
        if entry.order_params.comment:
            self._emit(f"    Comment: \"{entry.order_params.comment}\",")
        self._emit(f"    Magic: {magic},")
        self._emit(f"    FillPolicy: {fill},")
        self._emit("}")
        self._emit("return sig, nil")

        if cond_parts:
            self._indent -= 1
            self._emit("}")

    # ── Exit ─────────────────────────────────────────────────────

    def _gen_exit(self, exit_rule: ExitRule) -> None:
        if exit_rule.trigger == ExitTrigger.MAGIC_CLOSE:
            cond = " && ".join(c.expr for c in exit_rule.conditions) if exit_rule.conditions else ""
            if cond:
                self._emit(f"if {cond} {{")
                self._indent += 1
            magic = exit_rule.target.magic_value or "s.magic"
            self._emit(f"for _, pos := range ctx.Broker().Positions({magic}) {{")
            self._emit("    ctx.Broker().PositionClose(pos.Ticket, decimal.Zero)")
            self._emit("}")
            if cond:
                self._indent -= 1
                self._emit("}")
        elif exit_rule.trigger == ExitTrigger.MAGIC_DELETE:
            magic := exit_rule.target.magic_value or "s.magic"
            self._emit(f"for _, ord := range ctx.Broker().Orders({magic}) {{")
            self._emit("    ctx.Broker().OrderDelete(ord.Ticket)")
            self._emit("}")

    # ── on_timer ────────────────────────────────────────────────

    def _gen_on_timer(self, timer: TimerRule) -> None:
        name = self._lines[0].split(" ")[3] if self._lines else "S"
        # We need the struct name — extract from generated code
        self._emit()
        self._emit(f"func (s *{self._struct_name}) OnTimer(ctx sdk.Context) error {{")
        self._indent += 1
        self._emit("margin := ctx.Broker().Account().MarginLevel")
        self._emit("threshold := ctx.ParamDecimal(\"MarginThreshold\", decimal.NewFromInt(50))")
        self._emit("if margin.LessThan(threshold) {")
        self._emit("    s.closeAll(ctx)")
        self._emit("}")
        self._emit("return nil")
        self._indent -= 1
        self._emit("}")
        self._emit()

    @property
    def _struct_name(self) -> str:
        for line in self._lines:
            if line.startswith("type ") and line.endswith(" struct {"):
                return line[5:].split(" ")[0]
        return "ImportedStrategy"

    # ── on_deinit ────────────────────────────────────────────────

    def _gen_on_deinit(self, intent: StrategyIntent) -> None:
        name = self._struct_name
        self._emit(f"func (s *{name}) OnDeinit(ctx sdk.Context, reason string) error {{")
        self._indent += 1
        if intent.timer:
            self._emit("ctx.KillTimer()")
        self._emit("if reason != \"user_stop\" && reason != \"kill_switch\" {")
        self._emit("    return nil")
        self._emit("}")
        self._emit("s.closeAll(ctx)")
        self._emit("return nil")
        self._indent -= 1
        self._emit("}")
        self._emit()

    # ── Helpers ──────────────────────────────────────────────────

    def _gen_helpers(self, intent: StrategyIntent) -> None:
        name = self._struct_name
        self._emit(f"func (s *{name}) closeAll(ctx sdk.Context) {{")
        self._indent += 1
        self._emit("for _, pos := range ctx.Broker().Positions(s.magic) {")
        self._emit("    ctx.Broker().PositionClose(pos.Ticket, decimal.Zero)")
        self._emit("}")
        self._emit("for _, ord := range ctx.Broker().Orders(s.magic) {")
        self._emit("    ctx.Broker().OrderDelete(ord.Ticket)")
        self._emit("}")
        self._indent -= 1
        self._emit("}")

    # ── Parameter emission ───────────────────────────────────────

    def _emit_param(self, p: ParamSpec) -> None:
        defaults = str(p.default) if p.default is not None else "0"
        go_type = _param_go_type(p.param_type)
        go_name = _go_var_name(p.name)

        if p.param_type == ParamType.DOUBLE or p.param_type == ParamType.INT:
            self._emit(f"s.{go_name} = ctx.ParamDecimal(\"{p.name}\", "
                       f"decimal.NewFromFloat({defaults}))")
        elif p.param_type == ParamType.STRING:
            val = defaults.strip("'\"")
            self._emit(f"s.{go_name} = ctx.ParamString(\"{p.name}\", \"{val}\")")
        elif p.param_type == ParamType.BOOL:
            val = "true" if defaults.lower() in ("true", "1") else "false"
            self._emit(f"s.{go_name} = ctx.ParamBool(\"{p.name}\", {val})")

    # ── Indicator emission ───────────────────────────────────────

    def _emit_indicator(self, spec: IndicatorSpec, intent: StrategyIntent) -> None:
        if not spec.result_var:
            return
        var_name = _go_var_name(spec.result_var)
        params = spec.params or {}

        period = params.get("period", "14")
        shift = params.get("shift", "1")
        method = params.get("method", "'ema'").strip("'\"")

        method = spec.sdk_method
        if method in ("ma", "ema"):
            self._emit(f"{var_name} := ctx.Indicators().EMA({period}, {shift})")
        elif method == "rsi":
            self._emit(f"{var_name} := ctx.Indicators().RSI({period}, {shift})")
        elif method == "atr":
            self._emit(f"{var_name} := ctx.Indicators().ATR({period}, {shift})")
        elif method == "macd":
            fast = params.get("fast", "12")
            slow = params.get("slow", "26")
            sig = params.get("signal", "9")
            self._emit(f"{var_name} := ctx.Indicators().MACD({fast}, {slow}, {sig}, {shift})")
        elif method == "i_custom":
            name_val = spec.comment or "CustomIndicator"
            self._emit(f"{var_name} := ctx.Indicators().ICustom(\"{name_val}\", nil, 0, {shift})")
        elif method == "bands":
            dev = params.get("deviation", "2")
            self._emit(f"{var_name}Upper, {var_name}Mid, {var_name}Lower := "
                       f"ctx.Indicators().Bollinger({period}, {dev}, {shift})")

    # ── Output ───────────────────────────────────────────────────

    def _emit(self, line: str = "") -> None:
        if line:
            self._lines.append("\t" * self._indent + line)
        else:
            self._lines.append("")


# ── Helpers ─────────────────────────────────────────────────────────


def _go_pkg_name(name: str) -> str:
    """Infer a valid Go package name from strategy name."""
    import re
    pkg = re.sub(r'[^a-z0-9]', '', name.lower())
    return pkg or "strategy"


def _go_var_name(name: str) -> str:
    """Convert MQL variable name to Go exported or unexported name."""
    # Keep original case but ensure it's valid Go identifier
    return name


def _mql_to_go_type(mql_type: str) -> str:
    return {
        "int": "int", "long": "int64", "uint": "uint32",
        "double": "decimal.Decimal", "float": "decimal.Decimal",
        "bool": "bool", "string": "string",
    }.get(mql_type, "string")


def _param_go_type(pt: ParamType) -> str:
    return {
        ParamType.INT: "int",
        ParamType.DOUBLE: "decimal.Decimal",
        ParamType.STRING: "string",
        ParamType.BOOL: "bool",
    }.get(pt, "string")


def _go_signal_action(action: OrderAction) -> str:
    return {
        OrderAction.MARKET_BUY: "sdk.ActionBuy",
        OrderAction.MARKET_SELL: "sdk.ActionSell",
        OrderAction.BUY_LIMIT: "sdk.ActionBuyLimit",
        OrderAction.SELL_LIMIT: "sdk.ActionSellLimit",
        OrderAction.BUY_STOP: "sdk.ActionBuyStop",
        OrderAction.SELL_STOP: "sdk.ActionSellStop",
    }.get(action, "sdk.ActionNone")


def _go_fill_policy(action: OrderAction) -> str:
    if action in (OrderAction.MARKET_BUY, OrderAction.MARKET_SELL):
        return "sdk.FillIOC"
    return "sdk.FillReturn"
