// Package strategy provides the Strategy Lifecycle abstraction (M10-BASE-E0).
//
// Strategy defines the 8-hook contract that all trading strategies must implement.
// Aligned with NautilusTrader Strategy.save()/load() and Lean QCAlgorithm lifecycle.
//
// Lifecycle:
//
//	OnStart → OnBar/OnTick/OnOrderEvent loop → OnEndOfDay (daily) → OnStop
//	Snapshot() called before OnStop; Restore() called during OnStart.
//
// Hot-reload: old instance OnStop() → snapshot → PG → new instance OnStart(snapshot).
// Version-mismatch detection rejects incompatible hot-reloads, forcing rollover.
package strategy

import (
	"context"
	"time"

	"anttrader/internal/mdgateway/adapter/mdtick"
)

// Strategy defines the full lifecycle contract for a trading strategy.
// All 8 hooks must be implemented. Use BaseStrategy for no-op defaults.
type Strategy interface {
	// Name returns the human-readable strategy name.
	Name() string

	// Version returns the strategy version string (semver). Used for compatibility checks.
	// Hot-reload rejects strategies with different major versions.
	Version() string

	// --- Lifecycle hooks ---

	// OnStart is called when the strategy is deployed or hot-reloaded.
	// state is the serialized snapshot from a previous run, or nil for fresh starts.
	OnStart(ctx context.Context, state []byte) error

	// OnBar is called for each completed bar event.
	OnBar(ctx context.Context, bar *mdtick.Bar) error

	// OnTick is called for each tick event.
	OnTick(ctx context.Context, tick *mdtick.Tick) error

	// OnOrderEvent is called for order state changes.
	OnOrderEvent(ctx context.Context, event *OrderEvent) error

	// OnEndOfDay is called at market close for daily processing/rebalancing.
	OnEndOfDay(ctx context.Context, date time.Time) error

	// OnStop is called when the strategy is stopped or hot-reloaded away.
	OnStop(ctx context.Context) error

	// --- State persistence ---

	// Snapshot serializes the strategy's internal state for persistence.
	// Called before OnStop during hot-reload.
	Snapshot() ([]byte, error)

	// Restore deserializes the strategy's internal state.
	// Called during OnStart if a previous snapshot exists.
	Restore(state []byte) error
}

// OrderEvent is the strategy-level order event (simplified from mthub.OrderEvent).
type OrderEvent struct {
	AccountID string
	Ticket    int64
	EventType string
	Canonical string
	Side      string
	Volume    float64
	Price     float64
	State     string
	Timestamp time.Time
}

// Signal is a trading signal generated by the strategy.
type Signal struct {
	Symbol    string
	Side      string // "buy" / "sell"
	Volume    float64
	Price     float64
	Strategy  string
	AccountID string
	Timestamp time.Time
}

// BaseStrategy provides no-op defaults for all 8 hooks.
// Embed this to only override the hooks you need.
type BaseStrategy struct {
	name    string
	version string
}

// NewBaseStrategy creates a base strategy with the given name and version.
func NewBaseStrategy(name, version string) *BaseStrategy {
	return &BaseStrategy{name: name, version: version}
}

func (b *BaseStrategy) Name() string       { return b.name }
func (b *BaseStrategy) Version() string    { return b.version }
func (b *BaseStrategy) OnStart(context.Context, []byte) error { return nil }
func (b *BaseStrategy) OnBar(context.Context, *mdtick.Bar) error { return nil }
func (b *BaseStrategy) OnTick(context.Context, *mdtick.Tick) error { return nil }
func (b *BaseStrategy) OnOrderEvent(context.Context, *OrderEvent) error { return nil }
func (b *BaseStrategy) OnEndOfDay(context.Context, time.Time) error { return nil }
func (b *BaseStrategy) OnStop(context.Context) error { return nil }
func (b *BaseStrategy) Snapshot() ([]byte, error) { return nil, nil }
func (b *BaseStrategy) Restore([]byte) error { return nil }
