// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Auth = {
  "auth": {
    "validation": {
      "loginRequired": "Vui lòng nhập email hoặc số tài khoản"
    },
    "fields": {
      "login": "Email/Tài khoản"
    },
    "seo": {
      "login": {
        "title": "Đăng nhập",
        "description": "Đăng nhập AlphaForge để quản lý chiến lược giao dịch MT4/MT5 của bạn."
      },
      "register": {
        "title": "Đăng ký",
        "description": "Tạo tài khoản AlphaForge miễn phí để bắt đầu backtest và tự động giao dịch chiến lược MT4/MT5."
      },
      "forgotPassword": {
        "title": "Quên mật khẩu",
        "description": "Đặt lại mật khẩu tài khoản AlphaForge của bạn."
      },
      "resetPassword": {
        "title": "Đặt lại mật khẩu",
        "description": "Đặt lại mật khẩu tài khoản AlphaForge của bạn."
      },
      "verifyEmail": {
        "title": "Xác thực email",
        "description": "Xác thực địa chỉ email của bạn"
      }
    }
  }
} as const;
export default Auth;
