// Auto-generated by scripts/generate-missing-i18n.mjs
const Common = {
  "common": {
    "unknownError": "Lỗi không xác định",
    "copied": "Sao chép tất cả",
    "deleteFailed": "Xóa thất bại",
    "operationFailed": "Thao tác thất bại",
    "saveSuccess": "Đã lưu thành công",
    "refresh": "刷新",
    "loading": "加载中...",
    "saveFailed": "Lưu thất bại",
    "noData": "Không tìm thấy log",
    "confirm": "确认",
    "cancel": "取消"
  }
} as const;
export default Common;
