// Auto-generated by scripts/generate-missing-i18n.mjs
const ImportAnalysis = {
  "importAnalysis": {
    "execution": {
      "onBar": "Sự kiện đóng bar",
      "onInitGrid": "Khởi tạo lưới"
    },
    "sizing": {
      "fixed": "Khối lượng cố định",
      "percentBalance": "Phần trăm số dư"
    },
    "analyzing": "Đang phân tích cấu trúc chiến lược...",
    "tradeLogicComplete": "Logic giao dịch đã nhận diện đầy đủ",
    "guiNoiseDesc": "Các điểm mù sau là tính năng hiển thị chart/nút bấm bị bỏ qua khi thực thi server-side, không ảnh hưởng kết quả giao dịch. An toàn để nhập.",
    "emptyAnalysisDesc": "Không nhận diện được logic chiến lược. Mã nguồn có thể không đầy đủ, dùng ngôn ngữ khác, hoặc thử AI dịch.",
    "cannotImport": "Không thể tự động nhập",
    "incompleteCoverage": "Phạm vi logic giao dịch chưa đầy đủ",
    "goodCoverage": "Phạm vi nhập tốt",
    "goodCoverageDesc": "Logic chính của chiến lược đã nhận diện. An toàn để nhập. Kiểm tra danh sách tham số trước khi dùng.",
    "coverageTitle": "Phạm vi nhập",
    "userActionRequired": "Cần hành động của bạn",
    "noBlindSpots": "Không có logic cần xác nhận",
    "noBlindSpotsDesc": "Toàn bộ logic chiến lược tự nhận diện. An toàn để nhập."
  }
} as const;
export default ImportAnalysis;
