// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to vi
const ImportAnalysis = {
  "importAnalysis": {
    "execution": {
      "onBar": "Bar close event-driven",
      "onInitGrid": "Init grid"
    },
    "sizing": {
      "fixed": "Fixed lots",
      "percentBalance": "Percent of balance"
    },
    "analyzing": "Analyzing strategy structure...",
    "tradeLogicComplete": "Trading logic fully recognized",
    "guiNoiseDesc": "The following blind spots are chart display/button features that are skipped during server-side execution and do not affect trading results. Safe to import.",
    "cannotImport": "Cannot auto-import",
    "incompleteCoverage": "Trading logic coverage incomplete",
    "goodCoverage": "Import coverage is good",
    "goodCoverageDesc": "Strategy main logic recognized. Safe to import. Check parameter list before use.",
    "coverageTitle": "Import Coverage",
    "userActionRequired": "Your action required",
    "noBlindSpots": "No logic needs confirmation",
    "noBlindSpotsDesc": "All strategy logic auto-recognized. Safe to import."
  }
} as const;
export default ImportAnalysis;
