// Auto-generated by scripts/generate-missing-i18n.mjs
const Market = {
  "market": {
    "allSymbols": "Tất cả symbol",
    "selectSymbol": "Chọn symbol",
    "loadingSymbols": "Không tìm thấy symbol"
  }
} as const;
export default Market;
