// Auto-generated by scripts/generate-missing-i18n.mjs
const Monitoring = {
  "monitoring": {
    "title": "Giám sát hệ thống",
    "sseConnected": "SSE đã kết nối",
    "streamError": "Lỗi stream",
    "waitingData": "Đang chờ dữ liệu...",
    "serviceHealth": "Tình trạng dịch vụ",
    "diskUsage": "Sử dụng ổ đĩa",
    "goRuntime": "Go Runtime",
    "gcCount": "Số lần GC",
    "gcPauseAvg": "GC tạm dừng TB",
    "stackUsage": "Sử dụng stack",
    "heapMemory": "Bộ nhớ heap",
    "dbPool": "Pool kết nối DB",
    "mdGateway": "MD Gateway",
    "spillFiles": "Tệp spill",
    "droppedBars": "Bar bị loại",
    "droppedSignals": "Tín hiệu bị loại",
    "consumerLag": "Độ trễ consumer",
    "staleAccounts": "Tài khoản cũ",
    "deadAccounts": "Tài khoản chết",
    "avgGapSec": "Khoảng cách TB (giây)",
    "maxGapSec": "Khoảng cách tối đa (giây)",
    "dlq": "Hàng đợi thư chết (DLQ)",
    "parseErrors": "Lỗi phân tích",
    "bidGtAsk": "Bid>Ask",
    "pushInterval": "Cập nhật cuối"
  }
} as const;
export default Monitoring;
