// Auto-generated by scripts/generate-missing-i18n.mjs
const Notifications = {
  "notifications": {
    "prefs": {
      "saveFailed": "Lưu tùy chọn thất bại",
      "newStrategy": "Chiến lược mới đã xuất bản",
      "priceChange": "Giá chiến lược đã thay đổi",
      "subExpiring": "Đăng ký sắp hết hạn",
      "performance": "Hiệu suất chiến lược bất thường",
      "newRating": "Nhận được đánh giá hoặc bình luận mới",
      "title": "Tùy chọn thông báo"
    }
  }
} as const;
export default Notifications;
