// Auto-generated by scripts/generate-missing-i18n.mjs
const Onboarding = {
  "onboarding": {
    "step1": {
      "title": "Kết nối tài khoản",
      "desc": "Liên kết tài khoản giao dịch MT4/MT5 để bắt đầu.",
      "action": "Liên kết tài khoản"
    },
    "step2": {
      "title": "Tạo chiến lược đầu tiên",
      "desc": "Sử dụng AI để tạo chiến lược giao dịch từ ngôn ngữ tự nhiên.",
      "action": "Mở workspace"
    },
    "step3": {
      "title": "Nâng cấp gói",
      "desc": "Mở khóa thêm AI token, chiến lược và giao dịch trực tiếp với Pro.",
      "action": "Xem gói"
    },
    "welcome": "Chào mừng đến AlphaForge, {{name}}!",
    "subtitle": "Bắt đầu trong 3 bước đơn giản",
    "dismiss": "Đã hiểu, đóng"
  }
} as const;
export default Onboarding;
