// Auto-generated by scripts/generate-missing-i18n.mjs + manual share keys
const SharePage = {
  "sharePage": {
    "noPositions": "Không có vị thế mở",
    "positionsLocked": "Vị thế đã bị ẩn bởi người tạo",
    "notFound": "Không tìm thấy chiến lược hoặc không còn khả dụng",
    "backtestReturn": "Lợi nhuận backtest",
    "maxDrawdown": "Sụt giảm tối đa",
    "livePerformance": "Hiệu suất thực tế",
    "liveReturn": "Lợi nhuận thực tế",
    "liveMaxDD": "Sụt giảm tối đa thực tế",
    "codePreview": "Xem trước mã"
  }
} as const;
export default SharePage;
