// Auto-generated by scripts/generate-missing-i18n.mjs
const Share = {
  "share": {
    "token": "Liên kết chia sẻ",
    "deleteConfirm": "Xóa liên kết chia sẻ này?",
    "title": "Quản lý chia sẻ",
    "createNew": "Tạo liên kết chia sẻ mới",
    "empty": "Chưa có liên kết chia sẻ"
  }
} as const;
export default Share;
