// Auto-generated by scripts/generate-missing-i18n.mjs
const Sre = {
  "sre": {
    "breakers": {
      "stateHalfOpen": "Nửa mở (thăm dò)",
      "columns": {
        "strategyId": "ID chiến lược",
        "totalPnl": "Tổng L&L",
        "lossPercent": "Thua lỗ %",
        "trippedAt": "Kích hoạt lúc",
        "tripReason": "Lý do kích hoạt"
      },
      "confirmReset": "Đặt lại bộ ngắt này?",
      "title": "Bộ ngắt chiến lược",
      "description": "Tổng quan trạng thái bộ ngắt — tự động phát hiện lỗ bất thường và kích hoạt",
      "noBreakers": "Không có bộ ngắt đã đăng ký"
    },
    "canary": {
      "columns": {
        "strategyId": "ID chiến lược",
        "versionTag": "Thẻ phiên bản",
        "accounts": "Tài khoản canary",
        "startAt": "Bắt đầu lúc"
      },
      "confirmDelete": "Xóa cấu hình canary này?",
      "title": "Cấu hình Canary",
      "description": "Phiên bản chiến lược mới chạy trên vài tài khoản trong N ngày trước khi triển khai toàn bộ",
      "newCanary": "Canary mới",
      "noCanaries": "Không có cấu hình canary",
      "newCanaryTitle": "Canary mới",
      "accountIdsLabel": "ID tài khoản canary (phân tách bằng dấu phẩy hoặc xuống dòng)",
      "durationDays": "Số ngày canary"
    },
    "killSwitch": {
      "title": "Công tắc dừng khẩn cấp",
      "description": "Dừng tất cả giao dịch một chạm — cần xác nhận KILL; hoàn tác trong 5 phút",
      "engaged": "Công tắc dừng đã kích hoạt — tất cả giao dịch đã dừng",
      "disarmed": "Công tắc dừng đã tắt — giao dịch bình thường",
      "engagedAt": "Kích hoạt lúc",
      "undo": "Hoàn tác công tắc dừng",
      "disengage": "Tắt công tắc dừng",
      "engage": "Kích hoạt công tắc dừng",
      "confirmTitle": "Kích hoạt công tắc dừng — Xác nhận",
      "confirmEngage": "Xác nhận kích hoạt",
      "confirmWarning": "Sẽ dừng ngay tất cả hoạt động giao dịch của mọi tài khoản, kể cả lệnh đang chờ và đã gửi. Nhập lý do và gõ KILL để xác nhận.",
      "reasonLabel": "Lý do (bắt buộc)",
      "reasonPlaceholder": "VD: Phát hiện biến động thị trường bất thường, dừng khẩn cấp tất cả giao dịch",
      "typeKill": "Gõ KILL để xác nhận",
      "typeKillPlaceholder": "Gõ KILL (in hoa)"
    }
  }
} as const;
export default Sre;
