// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to vi
const Sre = {
  "sre": {
    "breakers": {
      "stateHalfOpen": "Half-Open (probing)",
      "columns": {
        "strategyId": "Strategy ID",
        "totalPnl": "Total P&L",
        "lossPercent": "Loss %",
        "trippedAt": "Tripped At",
        "tripReason": "Trip Reason"
      },
      "confirmReset": "Reset this breaker?",
      "title": "Strategy Breakers",
      "description": "Strategy breaker status overview — auto-detects abnormal losses and trips",
      "noBreakers": "No registered breakers"
    },
    "canary": {
      "columns": {
        "strategyId": "Strategy ID",
        "versionTag": "Version Tag",
        "accounts": "Canary Accounts",
        "startAt": "Start At"
      },
      "confirmDelete": "Delete this canary config?",
      "title": "Canary Configuration",
      "description": "New strategy versions run on a few accounts for N days before promotion to all",
      "newCanary": "New Canary",
      "noCanaries": "No canary configs",
      "newCanaryTitle": "New Canary",
      "accountIdsLabel": "Canary Account IDs (comma or newline separated)",
      "durationDays": "Canary Days"
    },
    "killSwitch": {
      "title": "Kill Switch",
      "description": "One-click stop all trading — requires KILL confirmation; undo within 5 minutes",
      "engaged": "Kill Switch engaged — all trading stopped",
      "disarmed": "Kill Switch disarmed — trading normal",
      "engagedAt": "Engaged At",
      "undo": "Undo Kill Switch",
      "disengage": "Disengage Kill Switch",
      "engage": "Engage Kill Switch",
      "confirmTitle": "Engage Kill Switch — Confirmation",
      "confirmEngage": "Confirm Engage",
      "confirmWarning": "This will immediately stop all trading activity for all accounts, including pending and submitted orders. Enter a reason and type KILL to confirm.",
      "reasonLabel": "Reason (required)",
      "reasonPlaceholder": "e.g.: Detected abnormal market volatility, emergency stop all trading",
      "typeKill": "Type KILL to confirm",
      "typeKillPlaceholder": "Type KILL (uppercase)"
    }
  }
} as const;
export default Sre;
