// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Subscription = {
  "subscription": {
    "subscribeSuccess": "Đăng ký kích hoạt thành công!",
    "charged": "Đã trừ: ${res.amountCharged}, Số dư: ${res.balanceAfter}",
    "insufficientBalance": "Số dư ví không đủ. Vui lòng nạp tiền trước.",
    "subscribeFailed": "Đăng ký thất bại. Vui lòng thử lại.",
    "cancelSuccess": "Đã hủy gia hạn tự động. Đăng ký của bạn vẫn có hiệu lực đến hết kỳ hiện tại.",
    "cancelFailed": "Hủy thất bại. Vui lòng thử lại.",
    "changeSuccess": "Đổi gói thành công!",
    "changeFailed": "Đổi gói thất bại. Vui lòng thử lại.",
    "title": "Gói đăng ký",
    "period": "Kỳ hiện tại",
    "cancelAutoRenew": "Hủy gia hạn tự động",
    "usageTitle": "Sử dụng tháng này",
    "aiTokens": "AI Token",
    "activeStrategies": "Chiến lược hoạt động",
    "runtimeMinutes": "Thời gian chạy (phút)",
    "walletBalance": "Số dư ví",
    "freeForever": "Miễn phí mãi mãi",
    "currentPlan": "Gói hiện tại",
    "choosePlan": "Chọn gói",
    "noPlans": "Không có gói nào",
    "changePlanTitle": "Đổi gói",
    "subscribeTitle": "Đăng ký gói",
    "selectBillingCycle": "Chu kỳ thanh toán",
    "chargeNotice": "Gói trả phí sẽ được trừ từ ví. Gói miễn phí không tính phí.",
    "seoTitle": "Đăng ký",
    "seoDesc": "Quản lý gói đăng ký của bạn"
  }
} as const;
export default Subscription;
