// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to vi
const Subscription = {
  "subscription": {
    "subscribeSuccess": "Subscription activated successfully!",
    "charged": "Charged: ${res.amountCharged}, Balance: ${res.balanceAfter}",
    "insufficientBalance": "Insufficient wallet balance. Please top up your wallet first.",
    "subscribeFailed": "Subscription failed. Please try again.",
    "cancelSuccess": "Auto-renewal cancelled. Your subscription remains active until the period ends.",
    "cancelFailed": "Failed to cancel. Please try again.",
    "changeSuccess": "Plan changed successfully!",
    "changeFailed": "Plan change failed. Please try again.",
    "title": "Subscription Plans",
    "period": "Current period",
    "cancelAutoRenew": "Cancel Auto-renew",
    "usageTitle": "Current Month Usage",
    "aiTokens": "AI Tokens",
    "activeStrategies": "Active Strategies",
    "runtimeMinutes": "Runtime (min)",
    "walletBalance": "Wallet Balance",
    "freeForever": "Free forever",
    "currentPlan": "Current Plan",
    "choosePlan": "Choose Plan",
    "noPlans": "No plans available",
    "changePlanTitle": "Change Plan",
    "subscribeTitle": "Subscribe to Plan",
    "selectBillingCycle": "Billing Cycle",
    "chargeNotice": "Your wallet will be charged for paid plans. Free plans have no charge."
  }
} as const;
export default Subscription;
