// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Auth = {
  "auth": {
    "validation": {
      "loginRequired": "请输入邮箱或账号编号"
    },
    "fields": {
      "login": "邮箱/账号"
    },
    "seo": {
      "login": {
        "title": "登录",
        "description": "登录 AlphaForge 管理您的 MT4/MT5 交易策略。"
      },
      "register": {
        "title": "注册",
        "description": "创建免费的 AlphaForge 账户，开始回测和自动交易 MT4/MT5 策略。"
      },
      "forgotPassword": {
        "title": "忘记密码",
        "description": "重置您的 AlphaForge 账户密码。"
      },
      "resetPassword": {
        "title": "重置密码",
        "description": "重置您的 AlphaForge 账户密码。"
      },
      "verifyEmail": {
        "title": "验证邮箱",
        "description": "验证您的邮箱地址"
      }
    }
  }
} as const;
export default Auth;
