// Auto-generated by scripts/generate-missing-i18n.mjs
const Common = {
  "common": {
    "unknownError": "未知错误",
    "copied": "复制全部",
    "deleteFailed": "删除失败",
    "operationFailed": "操作失败",
    "saveSuccess": "保存成功",
    "refresh": "刷新",
    "loading": "加载中...",
    "saveFailed": "保存失败",
    "noData": "未找到日志",
    "confirm": "确认",
    "cancel": "取消"
  }
} as const;
export default Common;
