// Auto-generated by scripts/generate-missing-i18n.mjs
const ImportAnalysis = {
  "importAnalysis": {
    "execution": {
      "onBar": "Bar 收盘事件驱动",
      "onInitGrid": "初始化网格"
    },
    "sizing": {
      "fixed": "固定手数",
      "percentBalance": "余额百分比"
    },
    "analyzing": "正在分析策略结构...",
    "tradeLogicComplete": "交易逻辑已完全识别",
    "guiNoiseDesc": "以下盲区为图表显示/按钮功能，服务端执行时跳过，不影响交易结果。可安全导入。",
    "emptyAnalysisDesc": "未识别到任何策略逻辑。源码可能不完整、使用了不同语言，请尝试 AI 翻译。",
    "cannotImport": "无法自动导入",
    "incompleteCoverage": "交易逻辑覆盖不完整",
    "goodCoverage": "导入覆盖良好",
    "goodCoverageDesc": "策略主要逻辑已识别。可安全导入。使用前请检查参数列表。",
    "coverageTitle": "导入覆盖率",
    "userActionRequired": "需要您手动确认",
    "noBlindSpots": "无需确认的逻辑",
    "noBlindSpotsDesc": "所有策略逻辑已自动识别。可安全导入。"
  }
} as const;
export default ImportAnalysis;
