// Auto-generated by scripts/generate-missing-i18n.mjs
const Monitoring = {
  "monitoring": {
    "title": "系统监控",
    "sseConnected": "SSE 已连接",
    "streamError": "流错误",
    "waitingData": "等待数据...",
    "serviceHealth": "服务健康",
    "diskUsage": "磁盘使用",
    "goRuntime": "Go 运行时",
    "gcCount": "GC 次数",
    "gcPauseAvg": "GC 平均暂停",
    "stackUsage": "栈使用",
    "heapMemory": "堆内存",
    "dbPool": "数据库连接池",
    "mdGateway": "行情网关",
    "spillFiles": "溢出文件",
    "droppedBars": "丢弃 K 线",
    "droppedSignals": "丢弃信号",
    "consumerLag": "消费者延迟",
    "staleAccounts": "过期账号",
    "deadAccounts": "死账号",
    "avgGapSec": "平均间隔 (秒)",
    "maxGapSec": "最大间隔 (秒)",
    "dlq": "死信队列 (DLQ)",
    "parseErrors": "解析错误",
    "bidGtAsk": "买价>卖价",
    "pushInterval": "最后更新"
  }
} as const;
export default Monitoring;
