// Auto-generated by scripts/generate-missing-i18n.mjs
const Notifications = {
  "notifications": {
    "prefs": {
      "saveFailed": "保存偏好设置失败",
      "newStrategy": "新策略已发布",
      "priceChange": "策略价格已变更",
      "subExpiring": "订阅即将到期",
      "performance": "策略表现异常",
      "newRating": "收到新评分或评论",
      "title": "通知偏好设置"
    }
  }
} as const;
export default Notifications;
