// Auto-generated by scripts/generate-missing-i18n.mjs
const Onboarding = {
  "onboarding": {
    "step1": {
      "title": "连接您的账户",
      "desc": "绑定您的 MT4/MT5 交易账户以开始。",
      "action": "绑定账户"
    },
    "step2": {
      "title": "创建您的第一个策略",
      "desc": "使用 AI 从自然语言生成交易策略。",
      "action": "打开工作区"
    },
    "step3": {
      "title": "升级您的套餐",
      "desc": "解锁更多 AI 代币、策略和实盘交易功能。",
      "action": "查看套餐"
    },
    "welcome": "欢迎使用 AlphaForge，{{name}}！",
    "subtitle": "3 个简单步骤即可开始",
    "dismiss": "知道了，关闭"
  }
} as const;
export default Onboarding;
