// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to zh-cn
const Onboarding = {
  "onboarding": {
    "step1": {
      "title": "Connect Your Account",
      "desc": "Link your MT4/MT5 trading account to start.",
      "action": "Bind Account"
    },
    "step2": {
      "title": "Create Your First Strategy",
      "desc": "Use AI to generate a trading strategy from natural language.",
      "action": "Open Workspace"
    },
    "step3": {
      "title": "Upgrade Your Plan",
      "desc": "Unlock more AI tokens, strategies, and live trading with Pro.",
      "action": "View Plans"
    },
    "welcome": "Welcome to AlphaForge, {{name}}!",
    "subtitle": "Get started in 3 simple steps",
    "dismiss": "Got it, dismiss"
  }
} as const;
export default Onboarding;
