// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to zh-cn
const Share = {
  "share": {
    "token": "Share Link",
    "deleteConfirm": "Delete this share link?",
    "title": "Share Management",
    "createNew": "Create New Share Link",
    "empty": "No share links yet"
  }
} as const;
export default Share;
