// Auto-generated by scripts/generate-missing-i18n.mjs
const Sre = {
  "sre": {
    "breakers": {
      "stateHalfOpen": "半开（探测中）",
      "columns": {
        "strategyId": "策略 ID",
        "totalPnl": "总盈亏",
        "lossPercent": "亏损 %",
        "trippedAt": "熔断时间",
        "tripReason": "熔断原因"
      },
      "confirmReset": "重置此熔断器？",
      "title": "策略熔断器",
      "description": "策略熔断器状态总览 — 自动检测异常亏损并熔断",
      "noBreakers": "无已注册熔断器"
    },
    "canary": {
      "columns": {
        "strategyId": "策略 ID",
        "versionTag": "版本标签",
        "accounts": "金丝雀账号",
        "startAt": "开始时间"
      },
      "confirmDelete": "删除此金丝雀配置？",
      "title": "金丝雀配置",
      "description": "新策略版本先在少数账号上运行 N 天，再推广到全部账号",
      "newCanary": "新建金丝雀",
      "noCanaries": "无金丝雀配置",
      "newCanaryTitle": "新建金丝雀",
      "accountIdsLabel": "金丝雀账号 ID（逗号或换行分隔）",
      "durationDays": "金丝雀天数"
    },
    "killSwitch": {
      "title": "一键停止",
      "description": "一键停止所有交易 — 需输入 KILL 确认；5 分钟内可撤销",
      "engaged": "一键停止已触发 — 所有交易已停止",
      "disarmed": "一键停止已解除 — 交易正常",
      "engagedAt": "触发时间",
      "undo": "撤销一键停止",
      "disengage": "解除一键停止",
      "engage": "触发一键停止",
      "confirmTitle": "触发一键停止 — 确认",
      "confirmEngage": "确认触发",
      "confirmWarning": "这将立即停止所有账号的所有交易活动，包括待提交和已提交的订单。请输入原因并输入 KILL 确认。",
      "reasonLabel": "原因（必填）",
      "reasonPlaceholder": "例如：检测到异常市场波动，紧急停止所有交易",
      "typeKill": "输入 KILL 确认",
      "typeKillPlaceholder": "输入 KILL（大写）"
    }
  }
} as const;
export default Sre;
