// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Subscription = {
  "subscription": {
    "subscribeSuccess": "订阅激活成功！",
    "charged": "已扣费: ${res.amountCharged}, 余额: ${res.balanceAfter}",
    "insufficientBalance": "钱包余额不足，请先充值。",
    "subscribeFailed": "订阅失败，请重试。",
    "cancelSuccess": "已取消自动续费。您的订阅在当前周期结束前仍然有效。",
    "cancelFailed": "取消失败，请重试。",
    "changeSuccess": "套餐更换成功！",
    "changeFailed": "套餐更换失败，请重试。",
    "title": "订阅套餐",
    "period": "当前周期",
    "cancelAutoRenew": "取消自动续费",
    "usageTitle": "本月使用量",
    "aiTokens": "AI Token",
    "activeStrategies": "活跃策略",
    "runtimeMinutes": "运行时长（分钟）",
    "walletBalance": "钱包余额",
    "freeForever": "永久免费",
    "currentPlan": "当前套餐",
    "choosePlan": "选择套餐",
    "noPlans": "暂无可用套餐",
    "changePlanTitle": "更换套餐",
    "subscribeTitle": "订阅套餐",
    "selectBillingCycle": "计费周期",
    "chargeNotice": "付费套餐将从钱包扣款，免费套餐不产生费用。",
    "seoTitle": "订阅",
    "seoDesc": "管理您的订阅套餐"
  }
} as const;
export default Subscription;
