import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Card, Descriptions, Spin, Tag, Typography, Empty, Row, Col, Table } from 'antd';
import { RiseOutlined, FallOutlined, ShareAltOutlined, EyeOutlined } from '@ant-design/icons';
import { create } from '@bufbuild/protobuf';
import { shareClient } from '@/client/connect';
import { GetSharedPerformanceRequestSchema } from '@/gen/ant/v1/share_pb';
import type { GetSharedPerformanceResponse } from '@/gen/ant/v1/share_pb';
import ShareChart from './ShareChart';

const { Title, Text } = Typography;

function fmt(n: number, d = 2) { return Number.isFinite(n) ? n.toFixed(d) : '-'; }

export default function SharePerformancePage() {
  const { token } = useParams<{ token: string }>();
  const [data, setData] = useState<GetSharedPerformanceResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!token) return;
    setLoading(true);
    const req = create(GetSharedPerformanceRequestSchema, { token });
    shareClient.getSharedPerformance(req)
      .then(setData)
      .catch(() => setError('Failed to load shared performance'))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) return <div style={{ textAlign: 'center', padding: 80 }}><Spin size="large" /></div>;
  if (error || !data) return <div style={{ textAlign: 'center', padding: 80 }}><Empty description={error || 'Not found'} /></div>;
  if (data.expired) return <div style={{ textAlign: 'center', padding: 80 }}><Empty description="This share link has expired" /></div>;

  const isPositive = data.totalReturn >= 0;
  const cols = [
    { title: 'Symbol', dataIndex: 'symbol', key: 'symbol', width: 100, responsive: ['xs' as const, 'sm' as const] },
    { title: 'Side', dataIndex: 'side', key: 'side', width: 60,
      render: (v: string) => <Tag color={v?.toLowerCase() === 'buy' ? 'green' : 'red'}>{v}</Tag> },
    { title: 'Volume', dataIndex: 'volume', key: 'volume', width: 80, render: (v: number) => v?.toFixed(2) },
    { title: 'Profit', dataIndex: 'profit', key: 'profit', width: 100,
      render: (v: number) => <span style={{ color: v >= 0 ? '#52c41a' : '#ff4d4f', fontWeight: 500 }}>{fmt(v, 2)}</span> },
    { title: 'Close', dataIndex: 'closeTimeMs', key: 'closeTimeMs', width: 140,
      render: (v: number) => v ? new Date(v).toLocaleDateString() : '-' },
  ];

  return (
    <div style={{ maxWidth: 960, margin: '0 auto', padding: '16px 12px 32px' }}>
      {/* Header */}
      <div style={{ textAlign: 'center', marginBottom: 20 }}>
        <Title level={3} style={{ marginBottom: 4 }}>
          <ShareAltOutlined /> 交易成绩单
        </Title>
        <div style={{ display: 'flex', justifyContent: 'center', gap: 16, flexWrap: 'wrap', color: '#8c8c8c', fontSize: 13 }}>
          <span><Text>{data.userName}</Text></span>
          <span><EyeOutlined /> 查看</span>
        </div>
      </div>

      {/* KPI cards – responsive grid */}
      <Row gutter={[12, 12]} style={{ marginBottom: 16 }}>
        {[
          ['总收益', `${isPositive ? '+' : ''}${fmt(data.totalReturn, 2)}%`, isPositive ? '#52c41a' : '#ff4d4f', isPositive ? <RiseOutlined /> : <FallOutlined />],
          ['胜率', `${fmt(data.winRate, 1)}%`, '#1677ff', null],
          ['最大回撤', `${fmt(data.maxDrawdown, 2)}%`, '#fa8c16', null],
          ['总交易', String(data.totalTrades), '#722ed1', null],
        ].map(([label, value, color, icon], i) => (
          <Col xs={12} sm={6} key={i}>
            <Card size="small" style={{ textAlign: 'center', borderRadius: 10 }}>
              <div style={{ fontSize: 11, color: '#8c8c8c', marginBottom: 4 }}>{label}</div>
              <Title level={4} style={{ margin: 0, color, fontSize: 22 }}>
                {icon}{value}
              </Title>
            </Card>
          </Col>
        ))}
      </Row>

      {/* Equity chart */}
      {data.equityCurve.length > 0 && (
        <Card size="small" title="收益曲线" style={{ marginBottom: 16, borderRadius: 10 }}>
          <ShareChart data={data.equityCurve} />
        </Card>
      )}

      {/* Trade list */}
      <Card size="small" title={`交易记录 (${data.trades?.length || 0})`} style={{ borderRadius: 10 }}>
        <Table
          dataSource={data.trades || []}
          columns={cols}
          rowKey={(_, i) => String(i)}
          size="small"
          pagination={{ pageSize: 20, size: 'small' }}
          scroll={{ x: 480 }}
        />
      </Card>

      <div style={{ textAlign: 'center', marginTop: 24, fontSize: 11, color: '#bbb' }}>
        Generated by AntTrader · This link will expire
      </div>
    </div>
  );
}
