#!/usr/bin/env python3
"""Generate MQL accessor → SDK property mapping from proto message schemas.

Parses reference/grpc/mt4.proto and mt5.proto to extract message field
definitions, then maps each MQL accessor name to its SDK property equivalent.

Output: tools/mql_transpiler/mappings_generated.py
  (importable Python dict that the transpiler can use directly)

Usage:   python3 tools/mql_transpiler/kb/generate_mappings.py
"""

from __future__ import annotations

import re
from pathlib import Path

PROTO_DIR = Path(__file__).resolve().parent.parent.parent.parent / "reference" / "grpc"
MT4_PROTO = PROTO_DIR / "mt4.proto"
MT5_PROTO = PROTO_DIR / "mt5.proto"
OUTPUT = Path(__file__).resolve().parent.parent / "mappings_generated.py"

# ── Proto field extractor ──────────────────────────────────────────


def extract_message_fields(proto_path: Path) -> dict[str, list[tuple[str, str, str]]]:
    """Extract all message field definitions: {MessageName: [(field_type, field_name, field_number)]}."""
    results = {}
    current_msg = None
    with open(proto_path) as f:
        for line in f:
            m_msg = re.match(r"\s*message\s+(\w+)\s*\{", line)
            m_close = re.match(r"\s*\}", line)
            m_field = re.match(
                r"\s*(?:repeated\s+)?(?:optional\s+)?(\w+(?:\.\w+)*)\s+(\w+)\s*=\s*(\d+)", line
            )

            if m_msg:
                current_msg = m_msg.group(1)
                results[current_msg] = []
            elif m_close and current_msg:
                current_msg = None
            elif m_field and current_msg:
                results[current_msg].append((m_field.group(1), m_field.group(2), m_field.group(3)))
    return results


# ── Field name → SDK property ──────────────────────────────────────


def sdk_property_name(proto_field: str) -> str:
    """Convert ProtoFieldName → sdk_property_name (snake_case)."""
    result = []
    for i, ch in enumerate(proto_field):
        if ch.isupper() and i > 0:
            result.append("_")
        result.append(ch.lower())
    return "".join(result).lstrip("_")


def mql_accessor_name(proto_field: str, prefix: str = "Order") -> str:
    """Convert ProtoFieldName → MQL accessor: OrderXxx()."""
    return f"{prefix}{proto_field}()"


# ── Message → MQL mapping rules ────────────────────────────────────

# Which proto messages map to MQL accessor patterns.
MSG_TO_ACCESSOR_RULES: dict[str, tuple[str, str]] = {
    # proto_message → (mql_prefix, sdk_object_path)
    # sdk_object_path should be the FULL Python accessor path from self.
    "Order": ("Order", "order"),
    "DealInternal": ("HistoryDealGet", "deal"),
    "AccountSummary": ("Account", "self.broker.account()"),
    "OrderInternal": ("OrderInternal", "order.internal"),
}


# ── Main generator ─────────────────────────────────────────────────

def generate_mappings() -> dict[str, str]:
    """Generate complete MQL→SDK mapping dict from proto schemas."""
    mappings = {}

    for proto_path in [MT4_PROTO, MT5_PROTO]:
        if not proto_path.exists():
            continue
        all_fields = extract_message_fields(proto_path)

        for msg_name, (mql_prefix, sdk_obj) in MSG_TO_ACCESSOR_RULES.items():
            if msg_name not in all_fields:
                continue
            for ftype, fname, fnum in all_fields[msg_name]:
                mql_call = mql_accessor_name(fname, mql_prefix)
                sdk_prop = sdk_property_name(fname)
                mappings[mql_call] = f"{sdk_obj}.{sdk_prop}"

    return mappings


def write_mappings_file(mappings: dict[str, str], path: Path) -> None:
    """Write the generated mappings as an importable Python file."""
    lines = [
        '"""Auto-generated MQL accessor → SDK property mappings.',
        "",
        "Generated by: tools/mql_transpiler/kb/generate_mappings.py",
        "Source:      reference/grpc/mt4.proto + mt5.proto",
        "",
        "DO NOT EDIT MANUALLY — changes will be overwritten.",
        'Run `python3 tools/mql_transpiler/kb/generate_mappings.py` to regenerate.',
        '"""',
        "",
        "# fmt: off",
        "MQL_TO_SDK_ACCESSOR: dict[str, str] = {",
    ]
    for mql, sdk in sorted(mappings.items()):
        lines.append(f'    "{mql}": "{sdk}",')
    lines.append("}")
    lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(mappings)} mappings to {path}")


def main() -> None:
    mappings = generate_mappings()
    write_mappings_file(mappings, OUTPUT)

    # Summary
    by_prefix = {}
    for mql in mappings:
        prefix = mql.split("(")[0].rstrip("1234567890")
        by_prefix[prefix] = by_prefix.get(prefix, 0) + 1

    print(f"\nGenerated {len(mappings)} MQL→SDK mappings:")
    for prefix, count in sorted(by_prefix.items()):
        print(f"  {prefix}*: {count} mappings")


if __name__ == "__main__":
    main()
