package interp

// MQL color and boolean constants extracted from constants.go for file-lines
// compliance. VM-CODE-HYGIENE-1. Merged into MQLConstants via init() in
// constants.go (which sorts before api_registry.go, ensuring registryMap
// sees all constants).

var mqlConstantsColors = map[string]Value{

	// ── Colors (MQL4/MQL5 WebColors) ───────────────────────────────────
	// https://docs.mql4.com/constants/namedconstants/otherconstants
	"Black":             IntVal(0),
	"White":             IntVal(16777215),
	"Red":               IntVal(255),
	"Green":             IntVal(32768),
	"Blue":              IntVal(16711680),
	"Yellow":            IntVal(65535),
	"CLR_NONE":          IntVal(-1),
	"Aqua":              IntVal(16776960),
	"Orange":            IntVal(42495),
	"Gold":              IntVal(55295),
	"Gray":              IntVal(8421504),
	"Silver":            IntVal(12632256),
	"Lime":              IntVal(65280),
	"Olive":             IntVal(32896),
	"Purple":            IntVal(8388736),
	"Teal":              IntVal(8421376),
	"NavajoWhite":       IntVal(1056964608),
	"WhiteSmoke":        IntVal(16119285),
	"DarkGray":          IntVal(9109504),
	"LightGray":         IntVal(13882323),
	"MidnightBlue":      IntVal(1644825),
	"Navy":              IntVal(128),
	"CornflowerBlue":    IntVal(15570276),
	"DodgerBlue":        IntVal(16748574),
	"RoyalBlue":         IntVal(16749338),
	"SteelBlue":         IntVal(11829830),
	"DeepSkyBlue":       IntVal(16760576),
	"SkyBlue":           IntVal(15453815),
	"LightSkyBlue":      IntVal(16436871),
	"LightBlue":         IntVal(15128749),
	"PaleTurquoise":     IntVal(15658671),
	"DarkTurquoise":     IntVal(13749760),
	"Turquoise":         IntVal(13688896),
	"Aquamarine":        IntVal(16753920),
	"Khaki":             IntVal(13434828),
	"DarkKhaki":         IntVal(9054196),
	"YellowGreen":       IntVal(6730598),
	"DarkOrange":        IntVal(36095),
	"OrangeRed":         IntVal(17919),
	"Tomato":            IntVal(4678655),
	"Coral":             IntVal(44279),
	"LightCoral":        IntVal(8421614),
	"Salmon":            IntVal(7504122),
	"DarkSalmon":        IntVal(8034025),
	"LightSalmon":       IntVal(12180223),
	"RosyBrown":         IntVal(7724975),
	"IndianRed":         IntVal(32832),
	"SandyBrown":        IntVal(6333684),
	"Chocolate":         IntVal(1993170),
	"SaddleBrown":       IntVal(1262987),
	"Sienna":            IntVal(6700286),
	"Brown":             IntVal(2763429),
	"Maroon":            IntVal(128),
	"FireBrick":         IntVal(22637),
	"DarkRed":           IntVal(139),
	"GreenYellow":       IntVal(3145645),
	"Chartreuse":        IntVal(65407),
	"LawnGreen":         IntVal(64636),
	"DarkGreen":         IntVal(25600),
	"SpringGreen":       IntVal(8388608),
	"MediumSpringGreen": IntVal(8206336),
	"SeaGreen":          IntVal(5737262),
	"ForestGreen":       IntVal(2263842),
	"LightGreen":        IntVal(9498256),
	"PaleGreen":         IntVal(10025880),
	"DarkSeaGreen":      IntVal(9419919),
	"MediumSeaGreen":    IntVal(7359752),
	"MediumAquamarine":  IntVal(6737322),
	"DarkOliveGreen":    IntVal(3107669),
	"OliveDrab":         IntVal(2330179),
	"DarkCyan":          IntVal(9145088),
	"MediumTurquoise":   IntVal(13422912),
	"Transparent":       IntVal(-1),
	"Magenta":           IntVal(16711935),
	"Pink":              IntVal(13353215),

	// clr* prefixed color aliases moved to CompatFixes (L0 deterministic alias).
	// See compat_fixes.go for the {clr* → unprefixed} mapping.

	// ── Time format flags ──────────────────────────────────────────────
	"TIME_DATE":    IntVal(1),
	"TIME_MINUTES": IntVal(2),
	"TIME_SECONDS": IntVal(4),

	// ── Init return values (MQL4/MQL5) ─────────────────────────────────
	"INIT_SUCCEEDED":            IntVal(0),
	"INIT_FAILED":               IntVal(1),
	"INIT_PARAMETERS_INCORRECT": IntVal(2),

	// ── Uninit reasons (ENUM_UNINIT_REASON) ────────────────────────────
	"REASON_REMOVE":      IntVal(1),
	"REASON_RECOMPILE":   IntVal(2),
	"REASON_CHARTCLOSE":  IntVal(3),
	"REASON_CHARTCHANGE": IntVal(4),
	"REASON_ACCOUNT":     IntVal(5),
	"REASON_TEMPLATE":    IntVal(6),
	"REASON_INITFAILED":  IntVal(7),
	"REASON_CLOSE":       IntVal(8),

	// ── Object types (ENUM_OBJECT) ─────────────────────────────────────
	"OBJ_HLINE":           IntVal(0),
	"OBJ_VLINE":           IntVal(1),
	"OBJ_TREND":           IntVal(2),
	"OBJ_TRENDANGLE":      IntVal(3),
	"OBJ_REGRESSION":      IntVal(4),
	"OBJ_CHANNEL":         IntVal(5),
	"OBJ_STDDEVCHANNEL":   IntVal(6),
	"OBJ_GANNLINE":        IntVal(7),
	"OBJ_GANNFAN":         IntVal(8),
	"OBJ_GANNGRID":        IntVal(9),
	"OBJ_FIBO":            IntVal(10),
	"OBJ_ELLIOTWAVE":      IntVal(11),
	"OBJ_RECTANGLE":       IntVal(12),
	"OBJ_TRIANGLE":        IntVal(13),
	"OBJ_ELLIPSE":         IntVal(14),
	"OBJ_PITCHFORK":       IntVal(15),
	"OBJ_CYCLES":          IntVal(16),
	"OBJ_TEXT":            IntVal(17),
	"OBJ_ARROW":           IntVal(18),
	"OBJ_LABEL":           IntVal(19),
	"OBJ_BUTTON":          IntVal(20),
	"OBJ_BITMAP":          IntVal(21),
	"OBJ_EDIT":            IntVal(22),
	"OBJ_EVENT":           IntVal(23),
	"OBJ_RECTANGLE_LABEL": IntVal(24),
	"OBJ_BITMAP_LABEL":    IntVal(25),

	// ── Error codes (MQL4 common) ──────────────────────────────────────
	"ERR_NO_ERROR":                 IntVal(0),
	"ERR_NO_RESULT":                IntVal(1),
	"ERR_COMMON_ERROR":             IntVal(2),
	"ERR_INVALID_TRADE_PARAMETERS": IntVal(3),
	"ERR_SERVER_BUSY":              IntVal(4),
	"ERR_OLD_VERSION":              IntVal(5),
	"ERR_NO_CONNECTION":            IntVal(6),
	"ERR_NOT_ENOUGH_RIGHTS":        IntVal(7),
	"ERR_TOO_FREQUENT_REQUESTS":    IntVal(8),
	"ERR_MALFUNCTIONAL_TRADE":      IntVal(9),
	"ERR_ACCOUNT_DISABLED":         IntVal(10),
	"ERR_INVALID_ACCOUNT":          IntVal(11),
	"ERR_TRADE_TIMEOUT":            IntVal(12),
	"ERR_INVALID_PRICE":            IntVal(13),
	"ERR_INVALID_STOPS":            IntVal(130),
	"ERR_INVALID_TRADE_VOLUME":     IntVal(131),
	"ERR_NOT_ENOUGH_MONEY":         IntVal(134),
	"ERR_PRICE_CHANGED":            IntVal(135),
	"ERR_OFF_QUOTES":               IntVal(136),
	"ERR_BROKER_BUSY":              IntVal(137),
	"ERR_REQUOTE":                  IntVal(138),
	"ERR_ORDER_LOCKED":             IntVal(139),
	"ERR_LONG_POSITIONS_ONLY":      IntVal(140),
	"ERR_TOO_MANY_REQUESTS":        IntVal(141),
	"ERR_TRADE_MODIFY_DENIED":      IntVal(145),
	"ERR_TRADE_CONTEXT_BUSY":       IntVal(146),
	"ERR_TRADE_EXPIRATION_DENIED":  IntVal(147),

	// ── MQL5 symbol info constants ─────────────────────────────────────
	"SYMBOL_SELECT":              IntVal(0),
	"SYMBOL_VISIBLE":             IntVal(1),
	"SYMBOL_TIME":                IntVal(5),
	"SYMBOL_DIGITS":              IntVal(12),
	"SYMBOL_SPREAD_FLOAT":        IntVal(14),
	"SYMBOL_SPREAD":              IntVal(13),
	"SYMBOL_TRADE_CALC_MODE":     IntVal(15),
	"SYMBOL_TRADE_MODE":          IntVal(16),
	"SYMBOL_START_TIME":          IntVal(17),
	"SYMBOL_EXPIRATION_TIME":     IntVal(18),
	"SYMBOL_TRADE_STOPS_LEVEL":   IntVal(19),
	"SYMBOL_TRADE_FREEZE_LEVEL":  IntVal(20),
	"SYMBOL_TRADE_EXEMODE":       IntVal(21),
	"SYMBOL_SWAP_MODE":           IntVal(22),
	"SYMBOL_SWAP_ROLLOVER3DAYS":  IntVal(23),
	"SYMBOL_BID":                 IntVal(0),
	"SYMBOL_ASK":                 IntVal(1),
	"SYMBOL_POINT":               IntVal(2),
	"SYMBOL_TRADE_TICK_VALUE":    IntVal(3),
	"SYMBOL_TRADE_TICK_SIZE":     IntVal(4),
	"SYMBOL_TRADE_CONTRACT_SIZE": IntVal(5),
	"SYMBOL_VOLUME_MIN":          IntVal(6),
	"SYMBOL_VOLUME_MAX":          IntVal(7),
	"SYMBOL_VOLUME_STEP":         IntVal(8),
	"SYMBOL_SWAP_LONG":           IntVal(9),
	"SYMBOL_SWAP_SHORT":          IntVal(10),
	"SYMBOL_MARGIN_INITIAL":      IntVal(11),
	"SYMBOL_MARGIN_MAINTENANCE":  IntVal(12),

	// ── MQL5 symbol trade modes (ENUM_SYMBOL_TRADE_MODE) ───────────────
	"SYMBOL_TRADE_MODE_DISABLED":  IntVal(0),
	"SYMBOL_TRADE_MODE_LONGONLY":  IntVal(1),
	"SYMBOL_TRADE_MODE_SHORTONLY": IntVal(2),
	"SYMBOL_TRADE_MODE_CLOSEONLY": IntVal(3),
	"SYMBOL_TRADE_MODE_FULL":      IntVal(4),

	// ── MQL5 symbol trade execution (ENUM_SYMBOL_TRADE_EXECUTION) ──────
	"SYMBOL_TRADE_EXECUTION_REQUEST":  IntVal(0),
	"SYMBOL_TRADE_EXECUTION_INSTANT":  IntVal(1),
	"SYMBOL_TRADE_EXECUTION_MARKET":   IntVal(2),
	"SYMBOL_TRADE_EXECUTION_EXCHANGE": IntVal(3),

	// ── Account stopout modes ──────────────────────────────────────────
	"ACCOUNT_STOPOUT_MODE_NONE":    IntVal(0),
	"ACCOUNT_STOPOUT_MODE_PERCENT": IntVal(1),
	"ACCOUNT_STOPOUT_MODE_MONEY":   IntVal(2),

	// ── Account info double properties (MQL5) ──────────────────────────
	"ACCOUNT_BALANCE":            IntVal(0),
	"ACCOUNT_CREDIT":             IntVal(1),
	"ACCOUNT_PROFIT":             IntVal(2),
	"ACCOUNT_EQUITY":             IntVal(3),
	"ACCOUNT_MARGIN":             IntVal(4),
	"ACCOUNT_MARGIN_FREE":        IntVal(5),
	"ACCOUNT_MARGIN_LEVEL":       IntVal(6),
	"ACCOUNT_MARGIN_INITIAL":     IntVal(7),
	"ACCOUNT_MARGIN_MAINTENANCE": IntVal(8),
	"ACCOUNT_MARGIN_SO_CALL":     IntVal(9),
	"ACCOUNT_MARGIN_SO_SO":       IntVal(10),

	// ── Booleans ───────────────────────────────────────────────────────
	"true":  BoolVal(true),
	"false": BoolVal(false),
}
