ALTER TABLE strategy_experiment_candidates
    ADD COLUMN IF NOT EXISTS oos_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS oos_total_return DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS oos_sharpe_ratio DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS degradation_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS is_overfit BOOLEAN NOT NULL DEFAULT FALSE;
