-- 176_backtest_numeric_precision.down.sql
-- Revert NUMERIC(20,8) back to DOUBLE PRECISION

ALTER TABLE backtest_run_trades
  ALTER COLUMN volume      TYPE DOUBLE PRECISION USING volume::DOUBLE PRECISION,
  ALTER COLUMN open_price  TYPE DOUBLE PRECISION USING open_price::DOUBLE PRECISION,
  ALTER COLUMN close_price TYPE DOUBLE PRECISION USING close_price::DOUBLE PRECISION,
  ALTER COLUMN pnl         TYPE DOUBLE PRECISION USING pnl::DOUBLE PRECISION,
  ALTER COLUMN commission  TYPE DOUBLE PRECISION USING commission::DOUBLE PRECISION;

ALTER TABLE backtest_runs
  ALTER COLUMN initial_capital TYPE DOUBLE PRECISION USING initial_capital::DOUBLE PRECISION,
  ALTER COLUMN commission TYPE DOUBLE PRECISION USING commission::DOUBLE PRECISION,
  ALTER COLUMN slippage   TYPE DOUBLE PRECISION USING slippage::DOUBLE PRECISION,
  ALTER COLUMN leverage   TYPE DOUBLE PRECISION USING leverage::DOUBLE PRECISION;
