-- 184_agent_memory.up.sql
-- ADR-0025 §4.2: Three-layer memory system tables.
-- 1. domain_knowledge — platform-managed global knowledge (all tenants share)
-- 2. user_strategy_templates — user-saved strategy preferences (per user)
-- 3. agent_experience — Agent auto-generated experiences (per user)

-- Domain knowledge: platform-managed, shared across all users.
CREATE TABLE IF NOT EXISTS domain_knowledge (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content     TEXT NOT NULL,
    scope       JSONB NOT NULL DEFAULT '{}',
    status      VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_domain_knowledge_status ON domain_knowledge(status) WHERE status = 'active';

-- User strategy templates: user-saved preferences, per user isolation.
CREATE TABLE IF NOT EXISTS user_strategy_templates (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       VARCHAR(128) NOT NULL,
    content    TEXT NOT NULL,
    scope      JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_strategy_templates_user ON user_strategy_templates(user_id);
CREATE UNIQUE INDEX idx_user_strategy_templates_user_name ON user_strategy_templates(user_id, name);

-- Agent experience: auto-generated by retrospect Agent (ADR-0025 §6).
-- Uses pgvector for semantic search + structural fingerprint for exact match.
CREATE TABLE IF NOT EXISTS agent_experience (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category      VARCHAR(64) NOT NULL DEFAULT 'strategy_pattern',
    content       TEXT NOT NULL,
    fingerprint   TEXT NOT NULL DEFAULT '',
    indicators    TEXT[] NOT NULL DEFAULT '{}',
    condition_structure VARCHAR(64) NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_experience_user ON agent_experience(user_id);
CREATE INDEX idx_agent_experience_category ON agent_experience(user_id, category);
CREATE INDEX idx_agent_experience_fingerprint ON agent_experience(fingerprint) WHERE fingerprint != '';
