package mql2go

// Extended builtin registry entries (MQL4/MQL5 complete lists).
// VM-CODE-HYGIENE-1: extracted from builtins_registry.go for file-lines compliance.

var builtinRegistryExt = []builtinEntry{
	// ── Math functions (MQL4/MQL5 complete list) ──────────────────────
	{"MathCos", nil},
	{"MathSin", nil},
	{"MathTan", nil},
	{"MathArccos", nil},
	{"MathArcsin", nil},
	{"MathArctan", nil},
	{"MathLog10", nil},
	{"MathMod", nil},
	{"MathRand", nil},
	{"MathSrand", nil},
	{"MathIsValidNumber", nil},
	// MQL4 lowercase math aliases
	{"ceil", nil},
	{"floor", nil},
	{"cos", nil},
	{"sin", nil},
	{"tan", nil},
	{"exp", nil},
	{"fabs", nil},
	{"fmax", nil},
	{"fmin", nil},
	{"fmod", nil},
	{"log", nil},
	{"log10", nil},
	{"pow", nil},
	{"round", nil},
	{"rand", nil},
	{"srand", nil},
	{"sqrt", nil},

	// ── String functions (MQL4/MQL5 complete list) ────────────────────
	{"StringAdd", nil},
	{"StringCompare", nil},
	{"StringGetCharacter", nil},
	{"StringSetCharacter", nil},
	{"StringToLower", nil},
	{"StringToUpper", nil},
	{"StringBufferLen", nil},
	{"StringInit", nil},
	{"StringFill", nil},

	// ── Conversion functions (MQL4/MQL5 complete list) ────────────────
	{"CharToString", nil},
	{"CharArrayToString", nil},
	{"ShortToString", nil},
	{"ShortArrayToString", nil},
	{"StringToColor", nil},
	{"StringToCharArray", nil},
	{"StringToShortArray", nil},
	{"EnumToString", nil},
	{"TimeToString", nil},

	// ── Date/Time functions (MQL4/MQL5 complete list) ─────────────────
	{"TimeGMT", nil},
	{"TimeGMTOffset", nil},
	{"TimeDaylightSavings", nil},
	{"TimeTradeServer", nil},
	{"TimeToStruct", nil},
	{"StructToTime", nil},
	{"PeriodSeconds", nil},

	// ── Array functions (additions) ───────────────────────────────────
	{"ArrayBsearch", nil},
	{"ArrayCompare", nil},
	{"ArrayInsert", nil},
	{"ArrayRemove", nil},
	{"ArrayReverse", nil},
	{"ArraySwap", nil},
	{"ArrayPrint", nil},
	{"ArrayGetAsSeries", nil},
	{"ArrayIsDynamic", nil},

	// ── Checkup / Platform functions (MQL4/MQL5 complete list) ────────
	{"IsConnected", nil},
	{"IsDemo", nil},
	{"IsDllsAllowed", nil},
	{"IsExpertEnabled", nil},
	{"IsLibrariesAllowed", nil},
	{"IsTradeAllowed", nil},
	{"IsTradeContextBusy", nil},
	{"IsStopped", nil},
	{"UninitializeReason", nil},
	{"MQLInfoInteger", nil},
	{"MQLInfoString", nil},
	{"TerminalInfoDouble", nil},
	{"TerminalInfoInteger", nil},
	{"TerminalInfoString", nil},
	{"GetTickCount", nil},
	{"GetTickCount64", nil},
	{"GetMicrosecondCount", nil},
	{"SetUserError", nil},
	{"SetReturnError", nil},
	{"CurTime", nil},

	// ── MQL5 timeseries access ────────────────────────────────────────
	{"Bars", nil},
	{"iBarShift", nil},
	{"iHighest", nil},
	{"iLowest", nil},
	{"iTickVolume", nil},
	{"iRealVolume", nil},
	{"iSpread", nil},
	{"CopyRates", nil},
	{"CopyClose", nil},
	{"CopyHigh", nil},
	{"CopyLow", nil},
	{"CopyOpen", nil},
	{"CopyTime", nil},
	{"CopyBuffer", nil},
	{"CopyTickVolume", nil},
	{"CopyRealVolume", nil},
	{"CopySpread", nil},
	{"CopyTicks", nil},
	{"BarsCalculated", nil},
	{"SeriesInfoInteger", nil},

	// ── MQL5 market info additions ────────────────────────────────────
	{"SymbolInfoTick", nil},
	{"SymbolName", nil},
	{"SymbolSelect", nil},
	{"SymbolsTotal", nil},
	{"SymbolInfoMarginRate", nil},
	{"SymbolInfoSessionQuote", nil},
	{"SymbolInfoSessionTrade", nil},
	{"SymbolIsSynchronized", nil},

	// ── MQL5 trade helpers ────────────────────────────────────────────
	{"OrderCalcMargin", nil},
	{"OrderCalcProfit", nil},
	{"OrderCheck", nil},
	{"PositionSelect", nil},

	// ── MQL5 order functions (pending orders) ─────────────────────────
	{"OrderGetTicket", nil},
	{"OrderGetDouble", nil},
	{"OrderGetInteger", nil},
	{"OrderGetString", nil},
	{"OrdersTotalMQL5", nil},

	// ── MQL5 deal/history functions ───────────────────────────────────
	{"HistorySelect", nil},
	{"HistorySelectByPosition", nil},
	{"HistoryDealsTotal", nil},
	{"HistoryDealSelect", nil},
	{"HistoryDealGetTicket", nil},
	{"HistoryDealGetDouble", nil},
	{"HistoryDealGetInteger", nil},
	{"HistoryDealGetString", nil},
	{"HistoryOrdersTotal", nil},
	{"HistoryOrderSelect", nil},
	{"HistoryOrderGetTicket", nil},
	{"HistoryOrderGetDouble", nil},
	{"HistoryOrderGetInteger", nil},
	{"HistoryOrderGetString", nil},

	// ── Account info additions (MQL5) ─────────────────────────────────
	{"AccountInfoDouble", nil},
	{"AccountInfoInteger", nil},
	{"AccountInfoString", nil},
	{"AccountStopoutMode", nil},
	{"AccountCredit", nil},

	// ── Python-specific operators ─────────────────────────────────────
	{"operator_in", nil},

	// ── Global Variables of the Terminal ──────────────────────────────
	{"GlobalVariableSet", nil},
	{"GlobalVariableGet", nil},
	{"GlobalVariableDel", nil},
	{"GlobalVariableCheck", nil},
	{"GlobalVariableTemp", nil},
	{"GlobalVariableFlush", nil},
	{"GlobalVariablesDeleteAll", nil},
	{"GlobalVariablesTotal", nil},
	{"GlobalVariableName", nil},
}
