package mql2go

import (
	"fmt"
	"strings"
	"unicode"
)

// Generate produces Go strategy source code from a StrategyIntent.
func Generate(intent *StrategyIntent) string {
	g := &generator{intent: intent}
	return g.generate()
}

type generator struct {
	intent *StrategyIntent
	b      strings.Builder
	indent int
}

func (g *generator) generate() string {
	g.b.Reset()
	g.genHeader()
	g.genBlindSpotComments()
	g.genStruct()
	g.genOnInit()

	// Execution model drives which callbacks are generated.
	switch g.intent.Execution.Kind {
	case ExecOnTick:
		// OnTick with bar guard → effectively a bar strategy.
		if g.intent.Execution.HasBarGuard {
			g.genOnBar()
		} else {
			// Pure tick strategy: generate OnTick, plus OnBar for bar data access.
			g.genOnTick()
			g.genOnBar()
		}
	case ExecOnInitGrid:
		g.genOnBar()
	default: // ExecOnBar
		g.genOnBar()
	}

	if g.intent.Timer != nil {
		g.genOnTimer()
	}
	g.genOnDeinit()
	g.genHelpers()
	return g.b.String()
}

// hasTickInterface returns true if the strategy generates an OnTick callback.
func (g *generator) hasTickInterface() bool {
	return g.intent.Execution.Kind == ExecOnTick && !g.intent.Execution.HasBarGuard
}

// hasTimerInterface returns true if the strategy generates an OnTimer callback.
func (g *generator) hasTimerInterface() bool {
	return g.intent.Timer != nil
}

// ── Header ────────────────────────────────────────────────────────

func (g *generator) genHeader() {
	name := g.goStructName()
	pkg := g.goPkgName(name)
	g.emit("// Code generated by mql2go. DO NOT EDIT.")
	g.emitf("package %s", pkg)
	g.emit("")
	g.emit("import (")
	g.emitf("\t\"anttrader/strategy/sdk\"")
	g.emit("")
	g.emit("\t\"github.com/shopspring/decimal\"")
	g.emit(")")
	g.emit("")
}

// ── Blind spot comments ────────────────────────────────────────────

func (g *generator) genBlindSpotComments() {
	if len(g.intent.BlindSpots) == 0 {
		return
	}
	g.emit("// ⚠️ Blind spots detected during MQL→Go transpilation:")
	for _, bs := range g.intent.BlindSpots {
		g.emitf("//   [%s] %s (%s): %s", bs.Severity, bs.ID, bs.Category, bs.Description)
		g.emitf("//     → %s", bs.Handling)
	}
	g.emit("")
}

// ── Struct ────────────────────────────────────────────────────────

func (g *generator) genStruct() {
	name := g.goStructName()
	g.emitf("// %s is an imported strategy.", name)
	g.emitf("type %s struct {", name)
	g.indent++
	for _, p := range g.intent.Params {
		g.emitf("%s %s", p.Name, paramGoType(p.Type))
	}
	g.indent--
	g.emit("}")
	g.emitf("var _ sdk.Strategy = (*%s)(nil)", name)
	if g.hasTickInterface() {
		g.emitf("var _ sdk.TickStrategy = (*%s)(nil)", name)
	}
	if g.hasTimerInterface() {
		g.emitf("var _ sdk.TimerStrategy = (*%s)(nil)", name)
	}
	g.emit("")
}

// ── on_init ──────────────────────────────────────────────────────

func (g *generator) genOnInit() {
	name := g.goStructName()
	g.emitf("func (s *%s) OnInit(ctx sdk.Context) error {", name)
	g.indent++
	for _, p := range g.intent.Params {
		g.emitParam(p)
	}
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── on_bar ────────────────────────────────────────────────────────

func (g *generator) genOnBar() {
	name := g.goStructName()
	g.emitf("func (s *%s) OnBar(ctx sdk.Context, tf string) (*sdk.Signal, error) {", name)
	g.indent++
	for _, ind := range g.intent.Indicators {
		g.emitIndicator(ind)
	}
	for _, rc := range g.intent.Risk {
		g.emitRiskCheck(rc)
	}
	for _, e := range g.intent.Exit {
		g.emitExit(e)
	}
	for _, loop := range g.intent.OrderLoops {
		g.emitOrderLoop(loop)
	}
	for _, loop := range g.intent.PositionLoops {
		g.emitPositionLoop(loop)
	}
	for _, mr := range g.intent.Modifies {
		g.emitModify(mr)
	}
	for _, e := range g.intent.Entry {
		g.emitEntry(e)
	}
	g.emit("return nil, nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── Entry ─────────────────────────────────────────────────────────

func (g *generator) emitEntry(e EntryRule) {
	condParts := nonEmpty(e.Conditions)
	if len(condParts) > 0 {
		cond := strings.Join(condParts, " && ")
		cond = g.convertParams(mqlToGoExpr(cond))
		cond = convertComparisons(cond)
		g.emitf("if %s {", cond)
		g.indent++
	}
	action := goSignalAction(e.Action)
	policy := goFillPolicy(e.Action)
	g.emitf("return &sdk.Signal{")
	g.indent++
	g.emitf("Action: %s,", action)
	if e.Volume != "" {
		vol := mqlToGoExpr(e.Volume)
		vol = g.convertParams(vol)
		g.emitf("Volume: %s,", wrapDecimal(vol))
	}
	if e.StopLoss != "" {
		sl := mqlToGoExpr(e.StopLoss)
		sl = g.convertParams(sl)
		g.emitf("StopLoss: %s,", wrapDecimal(sl))
	}
	if e.TakeProfit != "" {
		tp := mqlToGoExpr(e.TakeProfit)
		tp = g.convertParams(tp)
		g.emitf("TakeProfit: %s,", wrapDecimal(tp))
	}
	if e.Comment != "" {
		g.emitf("Comment: %q,", mqlToGoExpr(e.Comment))
	}
	g.emitf("Magic: s.magic,")
	g.emitf("FillPolicy: %s,", policy)
	g.indent--
	g.emitf("}")
	if len(condParts) > 0 {
		g.indent--
		g.emit("}")
	}
}

// ── Exit ──────────────────────────────────────────────────────────

func (g *generator) emitExit(e ExitRule) {
	magic := mqlToGoExpr(e.MagicVal)
	if magic == "" {
		magic = "s.magic"
	}
	parts := strings.SplitN(e.Action, ":", 2)
	action := parts[0]
	cond := ""
	if len(parts) > 1 {
		cond = parts[1]
	}
	if cond != "" {
		cond = g.convertParams(mqlToGoExpr(cond))
		cond = convertComparisons(cond)
		g.emitf("if %s {", cond)
		g.indent++
	}
	switch action {
	case "position_close":
		g.emitf("ctx.Broker().PositionClose(ctx, %s)", magic)
	case "position_close_partial":
		g.emitf("ctx.Broker().PositionClosePartial(ctx, %s, decimal.Zero)", magic)
	case "position_close_by":
		g.emitf("ctx.Broker().PositionCloseBy(ctx, %s, %s)", magic, magic)
	case "order_delete":
		g.emitf("ctx.Broker().OrderDelete(ctx, %s)", magic)
	}
	if cond != "" {
		g.indent--
		g.emit("}")
	}
}

// ── Modify (OrderModify / PositionModify) ─────────────────────────

func (g *generator) emitModify(mr ModifyRule) {
	magic := mqlToGoExpr(mr.MagicVal)
	if magic == "" {
		magic = "s.magic"
	}
	if mr.Condition != "" {
		cond := g.convertParams(mqlToGoExpr(mr.Condition))
		cond = convertComparisons(cond)
		g.emitf("if %s {", cond)
		g.indent++
	}
	sl := mqlToGoExpr(mr.StopLoss)
	tp := mqlToGoExpr(mr.TakeProfit)
	sl = g.convertParams(sl)
	tp = g.convertParams(tp)
	g.emitf("ctx.Broker().PositionModify(ctx, %s, %s, %s)", magic, wrapDecimal(sl), wrapDecimal(tp))
	if mr.Condition != "" {
		g.indent--
		g.emit("}")
	}
}

// ── Order loop (MQL4: OrdersTotal + OrderSelect) ──────────────────

func (g *generator) emitOrderLoop(loop OrderLoopRule) {
	g.emit("// MQL4 order iteration: OrdersTotal() + OrderSelect()")
	g.emitf("for _, pos := range ctx.Broker().Positions(s.magic) {")
	g.indent++
	if loop.HasSymbolFilter {
		g.emit("if pos.Symbol != ctx.Symbol() {")
		g.indent++
		g.emit("continue")
		g.indent--
		g.emit("}")
	}
	for _, action := range loop.BodyActions {
		switch {
		case action == "position_close":
			g.emitf("ctx.Broker().PositionClose(ctx, pos.Ticket)")
		case action == "order_delete":
			g.emitf("ctx.Broker().OrderDelete(ctx, pos.Ticket)")
		case action == "position_close_by":
			g.emitf("ctx.Broker().PositionCloseBy(ctx, pos.Ticket, pos.Ticket)")
		case action == "order_modify:trailing_stop":
			g.emit("// trailing stop modify")
			g.emitf("ctx.Broker().PositionModify(ctx, pos.Ticket, pos.StopLoss, pos.TakeProfit)")
		case action == "order_modify":
			g.emitf("ctx.Broker().PositionModify(ctx, pos.Ticket, pos.StopLoss, pos.TakeProfit)")
		}
	}
	g.indent--
	g.emit("}")
}

// ── Position loop (MQL5: PositionsTotal + PositionGetTicket) ──────

func (g *generator) emitPositionLoop(loop PositionLoopRule) {
	g.emit("// MQL5 position iteration: PositionsTotal() + PositionGetTicket()")
	g.emitf("for _, pos := range ctx.Broker().Positions(s.magic) {")
	g.indent++
	if loop.HasSymbolFilter {
		g.emit("if pos.Symbol != ctx.Symbol() {")
		g.indent++
		g.emit("continue")
		g.indent--
		g.emit("}")
	}
	for _, action := range loop.BodyActions {
		switch {
		case action == "position_close":
			g.emitf("ctx.Broker().PositionClose(ctx, pos.Ticket)")
		case action == "position_close_partial":
			g.emitf("ctx.Broker().PositionClosePartial(ctx, pos.Ticket, decimal.Zero)")
		case action == "position_close_by":
			g.emitf("ctx.Broker().PositionCloseBy(ctx, pos.Ticket, pos.Ticket)")
		case action == "position_modify:trailing_stop":
			g.emit("// trailing stop modify")
			g.emitf("ctx.Broker().PositionModify(ctx, pos.Ticket, pos.StopLoss, pos.TakeProfit)")
		case action == "position_modify":
			g.emitf("ctx.Broker().PositionModify(ctx, pos.Ticket, pos.StopLoss, pos.TakeProfit)")
		case action == "order_delete":
			g.emitf("ctx.Broker().OrderDelete(ctx, pos.Ticket)")
		}
	}
	g.indent--
	g.emit("}")
}

// ── Risk checks ────────────────────────────────────────────────────

func (g *generator) emitRiskCheck(rc RiskCheck) {
	if rc.Condition == "" {
		return
	}
	cond := g.convertParams(mqlToGoExpr(rc.Condition))
	cond = convertComparisons(cond)
	g.emitf("if %s {", cond)
	g.indent++
	switch rc.Action {
	case "skip_order":
		g.emit("return nil, nil")
	case "close_all":
		g.emit("s.closeAll(ctx)")
	case "log":
		g.emitf("ctx.Log(\"%s\")", rc.Condition)
	}
	g.indent--
	g.emit("}")
}

// ── on_tick (pure tick strategies — no bar guard) ─────────────────

func (g *generator) genOnTick() {
	name := g.goStructName()
	g.emitf("func (s *%s) OnTick(ctx sdk.Context, bid, ask decimal.Decimal) (*sdk.Signal, error) {", name)
	g.indent++
	for _, rc := range g.intent.Risk {
		g.emitRiskCheck(rc)
	}
	for _, e := range g.intent.Exit {
		g.emitExit(e)
	}
	for _, e := range g.intent.Entry {
		g.emitEntry(e)
	}
	g.emit("return nil, nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── on_timer ────────────────────────────────────────────────────

func (g *generator) genOnTimer() {
	name := g.goStructName()
	g.emit("")
	g.emitf("func (s *%s) OnTimer(ctx sdk.Context) (*sdk.Signal, error) {", name)
	g.indent++
	g.emit("return nil, nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── on_deinit ────────────────────────────────────────────────────

func (g *generator) genOnDeinit() {
	name := g.goStructName()
	g.emitf("func (s *%s) OnDeinit(ctx sdk.Context, reason string) error {", name)
	g.indent++
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── Helpers ──────────────────────────────────────────────────────

func (g *generator) genHelpers() {
	name := g.goStructName()
	g.emitf("func (s *%s) closeAll(ctx sdk.Context) {", name)
	g.indent++
	g.emit("for _, pos := range ctx.Broker().Positions(s.magic) {")
	g.indent++
	g.emit("ctx.Broker().PositionClose(ctx, pos.Ticket)")
	g.indent--
	g.emit("}")
	g.indent--
	g.emit("}")
}

// ── Output helpers ───────────────────────────────────────────────

func (g *generator) emit(s string) {
	g.b.WriteString(strings.Repeat("\t", g.indent))
	g.b.WriteString(s)
	g.b.WriteByte('\n')
}

func (g *generator) emitf(format string, args ...interface{}) {
	g.emit(fmt.Sprintf(format, args...))
}

func (g *generator) goStructName() string {
	if g.intent.Meta.Name != "" {
		return g.intent.Meta.Name
	}
	return "ImportedStrategy"
}

func (g *generator) goPkgName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	if b.Len() == 0 {
		return "strategy"
	}
	return b.String()
}
