package mql2go

import (
	"fmt"
	"strings"
	"unicode"
)

// Generate produces Go strategy source code from a StrategyIntent.
func Generate(intent *StrategyIntent) string {
	g := &generator{intent: intent}
	return g.generate()
}

type generator struct {
	intent *StrategyIntent
	b      strings.Builder
	indent int
}

func (g *generator) generate() string {
	g.b.Reset()
	g.genHeader()
	g.genStruct()
	g.genOnInit()
	g.genOnBar()
	if g.intent.Timer != nil {
		g.genOnTimer()
	}
	g.genOnDeinit()
	g.genHelpers()
	return g.b.String()
}

// ── Header ────────────────────────────────────────────────────────

func (g *generator) genHeader() {
	name := g.goStructName()
	pkg := g.goPkgName(name)
	g.emit("// Code generated by mql2go. DO NOT EDIT.")
	g.emitf("// Source: %s strategy", g.intent.Meta.MQLVersion)
	g.emitf("package %s", pkg)
	g.emit("")
	g.emit("import (")
	g.indent++
	g.emit(`"github.com/shopspring/decimal"`)
	g.emit(`"anttrader/strategy/sdk"`)
	g.indent--
	g.emit(")")
	g.emit("")
}

// ── Struct ────────────────────────────────────────────────────────

func (g *generator) genStruct() {
	name := g.goStructName()
	g.emitf("// %s is an imported strategy.", name)
	g.emitf("type %s struct {", name)
	g.indent++
	for _, sv := range g.intent.State {
		goType := mqlToGoType(sv.GoType)
		g.emitf("%s %s", sv.Name, goType)
	}
	for _, p := range g.intent.Params {
		g.emitf("%s %s", p.Name, paramGoType(p.Type))
	}
	g.emit("magic int32")
	g.emit("lotSize decimal.Decimal")
	g.emit("hedging bool")
	g.indent--
	g.emit("}")
	g.emit("")
	g.emitf("var _ sdk.Strategy = (*%s)(nil)", name)
	g.emit("")
}

// ── on_init ──────────────────────────────────────────────────────

func (g *generator) genOnInit() {
	name := g.goStructName()
	g.emitf("func (s *%s) OnInit(ctx sdk.Context) error {", name)
	g.indent++

	for _, p := range g.intent.Params {
		g.emitParam(p)
	}

	if g.intent.Timer != nil {
		g.emitf("ctx.SetTimer(%d)", g.intent.Timer.IntervalSeconds)
	}

	g.emit("s.hedging = ctx.Mode() == sdk.ModeHedging")
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── on_bar ────────────────────────────────────────────────────────

func (g *generator) genOnBar() {
	name := g.goStructName()
	g.emitf("func (s *%s) OnBar(ctx sdk.Context, tf string) (*sdk.Signal, error) {", name)
	g.indent++

	if g.intent.Execution.Kind == ExecOnBar {
		g.emit("if tf != ctx.Timeframe() {")
		g.emit("    return nil, nil")
		g.emit("}")
	}
	// ExecOnTick: no timeframe filter — execute on every tick

	g.emit("bars := ctx.Bars()")
	g.emit("_ = bars")
	g.emit("")

	// Indicators
	for _, spec := range g.intent.Indicators {
		g.emitIndicator(spec)
	}

	// Exits
	for _, exit := range g.intent.Exit {
		g.emitExit(exit)
	}

	// Modifies (OrderModify / PositionModify)
	for _, mr := range g.intent.Modifies {
		g.emitModify(mr)
	}

	// Entries
	for _, entry := range g.intent.Entry {
		g.emitEntry(entry)
	}

	g.emit("return nil, nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── Entry ─────────────────────────────────────────────────────────

func (g *generator) emitEntry(e EntryRule) {
	condParts := nonEmpty(e.Conditions)
	if len(condParts) > 0 {
		cond := strings.Join(condParts, " && ")
		cond = pyToGoExpr(g.convertParams(cond))
		g.emitf("if %s {", cond)
		g.indent++
	}

	action := goSignalAction(e.Action)
	volume := prefixRef(pyToGoExpr(e.Volume))
	magic := prefixRef(pyToGoExpr(e.Magic))
	if volume == "" || volume == "s." {
		volume = "s.lotSize"
	}
	if magic == "" || magic == "s." {
		magic = "s.magic"
	}
	fill := goFillPolicy(e.Action)

	g.emit("sig := &sdk.Signal{")
	g.emitf("    Action: %s,", action)
	if volume == "s.lotSize" {
		g.emitf("    Volume: %s,", volume)
	} else {
		g.emitf("    Volume: decimal.NewFromFloat(float64(%s)),", volume)
	}
	if e.StopLoss != "" && e.StopLoss != "0" && e.StopLoss != "0.0" {
		slExpr := pyToGoExpr(g.convertParams(e.StopLoss))
		g.emitf("    StopLoss: decimal.NewFromFloat(%s),", slExpr)
	}
	if e.TakeProfit != "" && e.TakeProfit != "0" && e.TakeProfit != "0.0" {
		tpExpr := pyToGoExpr(g.convertParams(e.TakeProfit))
		g.emitf("    TakeProfit: decimal.NewFromFloat(%s),", tpExpr)
	}
	if e.Comment != "" {
		g.emitf("    Comment: \"%s\",", stripQuotes(e.Comment))
	}
	g.emitf("    Magic: %s,", magic)
	g.emitf("    FillPolicy: %s,", fill)
	g.emit("}")
	g.emit("return sig, nil")

	if len(condParts) > 0 {
		g.indent--
		g.emit("}")
	}
}

// ── Exit ──────────────────────────────────────────────────────────

func (g *generator) emitExit(e ExitRule) {
	magic := pyToGoExpr(e.MagicVal)
	if magic == "" {
		magic = "s.magic"
	}

	switch e.Trigger {
	case TriggerMagic:
		g.emitf("for _, pos := range ctx.Broker().Positions(%s) {", magic)
		g.emit("    ctx.Broker().PositionClose(pos.Ticket, decimal.Zero)")
		g.emit("}")
	case TriggerDelete:
		g.emitf("for _, ord := range ctx.Broker().Orders(%s) {", magic)
		g.emit("    ctx.Broker().OrderDelete(ord.Ticket)")
		g.emit("}")
	case TriggerAll:
		g.emit("s.closeAll(ctx)")
	}
}

// ── Modify (OrderModify / PositionModify) ─────────────────────────

func (g *generator) emitModify(mr ModifyRule) {
	magic := pyToGoExpr(mr.MagicVal)
	if magic == "" {
		magic = "s.magic"
	}

	if mr.Condition != "" {
		cond := pyToGoExpr(g.convertParams(mr.Condition))
		g.emitf("if %s {", cond)
		g.indent++
	}

	g.emitf("for _, pos := range ctx.Broker().Positions(%s) {", magic)
	g.indent++

	slExpr := "decimal.Zero"
	tpExpr := "decimal.Zero"
	if mr.StopLoss != "" && mr.StopLoss != "0" && mr.StopLoss != "0.0" {
		slExpr = "decimal.NewFromFloat(" + pyToGoExpr(g.convertParams(mr.StopLoss)) + ")"
	}
	if mr.TakeProfit != "" && mr.TakeProfit != "0" && mr.TakeProfit != "0.0" {
		tpExpr = "decimal.NewFromFloat(" + pyToGoExpr(g.convertParams(mr.TakeProfit)) + ")"
	}

	g.emitf("ctx.Broker().PositionModify(pos.Ticket, %s, %s)", slExpr, tpExpr)
	g.indent--
	g.emit("}")

	if mr.Condition != "" {
		g.indent--
		g.emit("}")
	}
}

// ── on_timer ────────────────────────────────────────────────────

func (g *generator) genOnTimer() {
	name := g.goStructName()
	g.emit("")
	g.emitf("func (s *%s) OnTimer(ctx sdk.Context) error {", name)
	g.indent++
	g.emit("margin := ctx.Broker().Account().MarginLevel")
	g.emit(`threshold := ctx.ParamDecimal("MarginThreshold", decimal.NewFromInt(50))`)
	g.emit("if margin.LessThan(threshold) {")
	g.emit("    s.closeAll(ctx)")
	g.emit("}")
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── on_deinit ────────────────────────────────────────────────────

func (g *generator) genOnDeinit() {
	name := g.goStructName()
	g.emitf("func (s *%s) OnDeinit(ctx sdk.Context, reason string) error {", name)
	g.indent++
	if g.intent.Timer != nil {
		g.emit("ctx.KillTimer()")
	}
	g.emit(`if reason != "user_stop" && reason != "kill_switch" {`)
	g.emit("    return nil")
	g.emit("}")
	g.emit("s.closeAll(ctx)")
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── Helpers ──────────────────────────────────────────────────────

func (g *generator) genHelpers() {
	name := g.goStructName()
	g.emitf("func (s *%s) closeAll(ctx sdk.Context) {", name)
	g.indent++
	g.emit("for _, pos := range ctx.Broker().Positions(s.magic) {")
	g.emit("    ctx.Broker().PositionClose(pos.Ticket, decimal.Zero)")
	g.emit("}")
	g.emit("for _, ord := range ctx.Broker().Orders(s.magic) {")
	g.emit("    ctx.Broker().OrderDelete(ord.Ticket)")
	g.emit("}")
	g.indent--
	g.emit("}")
}

// ── Parameter emission ───────────────────────────────────────────

func (g *generator) emitParam(p ParamSpec) {
	dflt := p.Default
	switch p.Type {
	case ParamInt:
		if dflt == "" {
			dflt = "0"
		}
		g.emitf("s.%s = int32(ctx.ParamInt(\"%s\", %s))",
			p.Name, p.Name, dflt)
	case ParamDouble:
		if dflt == "" {
			dflt = "0"
		}
		g.emitf("s.%s = ctx.ParamDecimal(\"%s\", decimal.NewFromFloat(%s)).InexactFloat64()",
			p.Name, p.Name, dflt)
	case ParamString:
		if dflt == "" {
			dflt = `""`
		}
		g.emitf("s.%s = ctx.ParamString(\"%s\", \"%s\")",
			p.Name, p.Name, stripQuotes(dflt))
	case ParamBool:
		if dflt == "true" || dflt == "1" {
			dflt = "true"
		} else {
			dflt = "false"
		}
		g.emitf("s.%s = ctx.ParamBool(\"%s\", %s)", p.Name, p.Name, dflt)
	}
}

// ── Indicator emission ────────────────────────────────────────

func (g *generator) emitIndicator(spec IndicatorSpec) {
	if spec.ResultVar == "" {
		return
	}
	varName := pyToGoExpr(spec.ResultVar)
	period := spec.Params["period"]
	if period == "" {
		period = "14"
	}
	shift := spec.Params["shift"]
	if shift == "" || shift == "0" {
		shift = "1" // default: most recent completed bar
	}
	period = pyToGoExpr(period)
	if !isNumeric(period) {
		period = prefixRef(period)
	}
	shift = pyToGoExpr(shift)

	switch spec.SDKMethod {
	case "ma", "ema":
		g.emitf("%s := ctx.Indicators().EMA(%s, %s)", varName, period, shift)
	case "rsi":
		g.emitf("%s := ctx.Indicators().RSI(%s, %s)", varName, period, shift)
	case "atr":
		g.emitf("%s := ctx.Indicators().ATR(%s, %s)", varName, period, shift)
	case "macd":
		fast := pyToGoExpr(spec.Params["fast"])
		slow := pyToGoExpr(spec.Params["slow"])
		sig := pyToGoExpr(spec.Params["signal"])
		if fast == "" {
			fast = "12"
		}
		if slow == "" {
			slow = "26"
		}
		if sig == "" {
			sig = "9"
		}
		g.emitf("%s := ctx.Indicators().MACD(%s, %s, %s, %s)", varName, fast, slow, sig, shift)
	case "bands":
		deviation := pyToGoExpr(spec.Params["deviation"])
		if deviation == "" {
			deviation = "2.0"
		}
		g.emitf("%sUpper, %sMid, %sLower := ctx.Indicators().Bollinger(%s, %s, %s)",
			varName, varName, varName, period, deviation, shift)
		g.emitf("_ = %sUpper", varName)
		g.emitf("_ = %sMid", varName)
		g.emitf("_ = %sLower", varName)
	case "stochastic":
		kPeriod := pyToGoExpr(spec.Params["kperiod"])
		dPeriod := pyToGoExpr(spec.Params["dperiod"])
		slowing := pyToGoExpr(spec.Params["slowing"])
		if kPeriod == "" {
			kPeriod = "5"
		}
		if dPeriod == "" {
			dPeriod = "3"
		}
		if slowing == "" {
			slowing = "3"
		}
		g.emitf("%sK, %sD := ctx.Indicators().Stochastic(%s, %s, %s, %s)",
			varName, varName, kPeriod, dPeriod, slowing, shift)
		g.emitf("_ = %sK", varName)
		g.emitf("_ = %sD", varName)
	case "cci":
		g.emitf("%s := ctx.Indicators().CCI(%s, %s)", varName, period, shift)
	case "adx":
		g.emitf("%s := ctx.Indicators().ADX(%s, %s)", varName, period, shift)
	case "momentum":
		g.emitf("%s := ctx.Indicators().Momentum(%s, %s)", varName, period, shift)
	case "wpr":
		g.emitf("%s := ctx.Indicators().WPR(%s, %s)", varName, period, shift)
	case "mfi":
		g.emitf("%s := ctx.Indicators().MFI(%s, %s)", varName, period, shift)
	case "obv":
		g.emitf("%s := ctx.Indicators().OBV(%s)", varName, shift)
	case "sar":
		step := pyToGoExpr(spec.Params["step"])
		maximum := pyToGoExpr(spec.Params["maximum"])
		if step == "" {
			step = "0.02"
		}
		if maximum == "" {
			maximum = "0.2"
		}
		g.emitf("%s := ctx.Indicators().SAR(%s, %s, %s)", varName, step, maximum, shift)
	case "stddev":
		g.emitf("%s := ctx.Indicators().StdDev(%s, %s)", varName, period, shift)
	case "alligator":
		jaw := pyToGoExpr(spec.Params["jaw_period"])
		teeth := pyToGoExpr(spec.Params["teeth_period"])
		lips := pyToGoExpr(spec.Params["lips_period"])
		if jaw == "" {
			jaw = "13"
		}
		if teeth == "" {
			teeth = "8"
		}
		if lips == "" {
			lips = "5"
		}
		g.emitf("// TODO: iAlligator(%s, %s, %s) — SDK IndicatorSet.Alligator not yet implemented", jaw, teeth, lips)
		g.emitf("_ = %s", varName)
	case "ichimoku":
		tenkan := pyToGoExpr(spec.Params["tenkan"])
		kijun := pyToGoExpr(spec.Params["kijun"])
		senkouB := pyToGoExpr(spec.Params["senkou_b"])
		if tenkan == "" {
			tenkan = "9"
		}
		if kijun == "" {
			kijun = "26"
		}
		if senkouB == "" {
			senkouB = "52"
		}
		g.emitf("// TODO: iIchimoku(%s, %s, %s) — SDK IndicatorSet.Ichimoku not yet implemented", tenkan, kijun, senkouB)
		g.emitf("_ = %s", varName)
	case "envelopes":
		deviation := pyToGoExpr(spec.Params["deviation"])
		if deviation == "" {
			deviation = "0.1"
		}
		g.emitf("// TODO: iEnvelopes(%s, %s) — SDK IndicatorSet.Envelopes not yet implemented", period, deviation)
		g.emitf("_ = %s", varName)
	case "demarker":
		g.emitf("// TODO: iDeMarker(%s) — SDK IndicatorSet.DeMarker not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "osma":
		fast := pyToGoExpr(spec.Params["fast"])
		slow := pyToGoExpr(spec.Params["slow"])
		sig := pyToGoExpr(spec.Params["signal"])
		if fast == "" {
			fast = "12"
		}
		if slow == "" {
			slow = "26"
		}
		if sig == "" {
			sig = "9"
		}
		g.emitf("// TODO: iOsMA(%s, %s, %s) — SDK IndicatorSet.OsMA not yet implemented", fast, slow, sig)
		g.emitf("_ = %s", varName)
	case "rvi":
		g.emitf("// TODO: iRVI(%s) — SDK IndicatorSet.RVI not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "force":
		g.emitf("// TODO: iForce(%s) — SDK IndicatorSet.Force not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "fractals":
		g.emitf("// TODO: iFractals() — SDK IndicatorSet.Fractals not yet implemented")
		g.emitf("_ = %s", varName)
	case "gator":
		jaw := pyToGoExpr(spec.Params["jaw_period"])
		teeth := pyToGoExpr(spec.Params["teeth_period"])
		lips := pyToGoExpr(spec.Params["lips_period"])
		if jaw == "" {
			jaw = "13"
		}
		if teeth == "" {
			teeth = "8"
		}
		if lips == "" {
			lips = "5"
		}
		g.emitf("// TODO: iGator(%s, %s, %s) — SDK IndicatorSet.Gator not yet implemented", jaw, teeth, lips)
		g.emitf("_ = %s", varName)
	case "ac":
		g.emitf("// TODO: iAC() — SDK IndicatorSet.AC not yet implemented")
		g.emitf("_ = %s", varName)
	case "ad":
		g.emitf("// TODO: iAD() — SDK IndicatorSet.AD not yet implemented")
		g.emitf("_ = %s", varName)
	case "ao":
		g.emitf("// TODO: iAO() — SDK IndicatorSet.AO not yet implemented")
		g.emitf("_ = %s", varName)
	case "bears_power":
		g.emitf("// TODO: iBearsPower(%s) — SDK IndicatorSet.BearsPower not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "bulls_power":
		g.emitf("// TODO: iBullsPower(%s) — SDK IndicatorSet.BullsPower not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "bwmfi":
		g.emitf("// TODO: iBWMFI() — SDK IndicatorSet.BWMFI not yet implemented")
		g.emitf("_ = %s", varName)
	case "ama":
		fast := pyToGoExpr(spec.Params["fast"])
		slow := pyToGoExpr(spec.Params["slow"])
		if fast == "" {
			fast = "2"
		}
		if slow == "" {
			slow = "30"
		}
		g.emitf("// TODO: iAMA(%s, %s, %s) — SDK IndicatorSet.AMA not yet implemented", period, fast, slow)
		g.emitf("_ = %s", varName)
	case "dema":
		g.emitf("// TODO: iDEMA(%s) — SDK IndicatorSet.DEMA not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "tema":
		g.emitf("// TODO: iTEMA(%s) — SDK IndicatorSet.TEMA not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "frama":
		g.emitf("// TODO: iFrAMA(%s) — SDK IndicatorSet.FrAMA not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "vidya":
		cmoPeriod := pyToGoExpr(spec.Params["cmo_period"])
		if cmoPeriod == "" {
			cmoPeriod = "9"
		}
		g.emitf("// TODO: iVIDyA(%s, %s) — SDK IndicatorSet.VIDyA not yet implemented", cmoPeriod, period)
		g.emitf("_ = %s", varName)
	case "trix":
		g.emitf("// TODO: iTriX(%s) — SDK IndicatorSet.TriX not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "adx_wilder":
		g.emitf("// TODO: iADXWilder(%s) — SDK IndicatorSet.ADXWilder not yet implemented", period)
		g.emitf("_ = %s", varName)
	case "chaikin":
		fast := pyToGoExpr(spec.Params["fast"])
		slow := pyToGoExpr(spec.Params["slow"])
		if fast == "" {
			fast = "3"
		}
		if slow == "" {
			slow = "10"
		}
		g.emitf("// TODO: iChaikin(%s, %s) — SDK IndicatorSet.Chaikin not yet implemented", fast, slow)
		g.emitf("_ = %s", varName)
	case "volumes":
		g.emitf("// TODO: iVolumes() — SDK IndicatorSet.Volumes not yet implemented")
		g.emitf("_ = %s", varName)
	}
}

// ── Output helpers ───────────────────────────────────────────────

func (g *generator) emit(s string) {
	g.b.WriteString(strings.Repeat("\t", g.indent))
	g.b.WriteString(s)
	g.b.WriteByte('\n')
}

func (g *generator) emitf(format string, args ...interface{}) {
	g.emit(fmt.Sprintf(format, args...))
}

func (g *generator) goStructName() string {
	if g.intent.Meta.Name != "" {
		return g.intent.Meta.Name
	}
	return "ImportedStrategy"
}

func (g *generator) goPkgName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	if b.Len() == 0 {
		return "strategy"
	}
	return b.String()
}

// ── Expression helpers ───────────────────────────────────────────

func nonEmpty(ss []string) []string {
	var out []string
	for _, s := range ss {
		if s != "" {
			out = append(out, s)
		}
	}
	return out
}

func stripQuotes(s string) string {
	if len(s) >= 2 && s[0] == '\'' && s[len(s)-1] == '\'' {
		return s[1 : len(s)-1]
	}
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

func mqlToGoType(t string) string {
	switch t {
	case "int", "long", "uint":
		return "int"
	case "double", "float":
		return "decimal.Decimal"
	case "bool":
		return "bool"
	default:
		return "string"
	}
}

func goSignalAction(a OrderAction) string {
	switch a {
	case ActionMarketBuy:
		return "sdk.ActionBuy"
	case ActionMarketSell:
		return "sdk.ActionSell"
	case ActionBuyLimit:
		return "sdk.ActionBuyLimit"
	case ActionSellLimit:
		return "sdk.ActionSellLimit"
	case ActionBuyStop:
		return "sdk.ActionBuyStop"
	case ActionSellStop:
		return "sdk.ActionSellStop"
	}
	return "sdk.ActionNone"
}

func goFillPolicy(a OrderAction) string {
	switch a {
	case ActionMarketBuy, ActionMarketSell:
		return "sdk.FillIOC"
	}
	return "sdk.FillReturn"
}

func prefixRef(expr string) string {
	// If a bare identifier (no prefix), add "s."
	if expr == "" || strings.HasPrefix(expr, "s.") || strings.HasPrefix(expr, "ctx.") {
		return expr
	}
	if strings.Contains(expr, ".") || strings.Contains(expr, "(") || strings.Contains(expr, "\"") {
		return expr // already qualified or literal
	}
	return "s." + expr
}

func pyToGoExpr(expr string) string {
	if expr == "" {
		return expr
	}
	// self. → s.
	expr = strings.ReplaceAll(expr, "self.", "s.")
	// Python logical operators → Go
	expr = strings.ReplaceAll(expr, " and ", " && ")
	expr = strings.ReplaceAll(expr, " or ", " || ")
	expr = strings.ReplaceAll(expr, " not ", " ! ")
	// Remove Decimal(str(...)) wrapper
	expr = strings.ReplaceAll(expr, "Decimal(str(", "")
	expr = strings.ReplaceAll(expr, "'", "")
	// MQL builtins → ctx methods
	expr = replaceWord(expr, "Ask", "ctx.Ask().InexactFloat64()")
	expr = replaceWord(expr, "Bid", "ctx.Bid().InexactFloat64()")
	expr = replaceWord(expr, "Point", "ctx.Point().InexactFloat64()")
	expr = strings.ReplaceAll(expr, "Symbol()", "ctx.Symbol()")
	return expr
}

func paramGoType(t ParamType) string {
	switch t {
	case ParamInt:
		return "int32"
	case ParamDouble:
		return "float64"
	case ParamString:
		return "string"
	case ParamBool:
		return "bool"
	default:
		return "string"
	}
}

func isNumeric(s string) bool {
	if s == "" {
		return false
	}
	for _, c := range s {
		if (c < '0' || c > '9') && c != '.' && c != '-' {
			return false
		}
	}
	return true
}

func replaceWord(s, old, new string) string {
	var b strings.Builder
	i := 0
	for i < len(s) {
		if i+len(old) <= len(s) && s[i:i+len(old)] == old {
			before := i == 0 || !isWordChar(s[i-1])
			after := i+len(old) == len(s) || !isWordChar(s[i+len(old)])
			if before && after {
				b.WriteString(new)
				i += len(old)
				continue
			}
		}
		b.WriteByte(s[i])
		i++
	}
	return b.String()
}

func isWordChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

func (g *generator) convertParams(expr string) string {
	for _, p := range g.intent.Params {
		if p.Type == ParamInt {
			expr = replaceWord(expr, p.Name, "float64(s."+p.Name+")")
		} else {
			expr = replaceWord(expr, p.Name, "s."+p.Name)
		}
	}
	return expr
}
