package mql2go

import (
	"fmt"
	"strings"
	"unicode"

	"anttrader/tools/mql2go/interp"
)

// GenerateFromIR produces Go strategy source code from an interp.IR.
// This is the single source of truth for Go export — no StrategyIntent involved.
// The output is a read-only export preview; execution goes through the interpreter.
func GenerateFromIR(ir *interp.IR, name string) string {
	if name == "" {
		name = "ImportedStrategy"
	}
	g := &irGenerator{
		ir:         ir,
		name:       name,
		pkg:        irPkgName(name),
		param:      make(map[string]bool),
		intVars:    make(map[string]bool),
		stdImports: make(map[string]bool),
	}
	return g.generate()
}

type irGenerator struct {
	ir         *interp.IR
	name       string
	pkg        string
	b          strings.Builder
	indent     int
	param      map[string]bool // param names for s. prefix
	intVars    map[string]bool // variables known to be integers
	posLoopVar string         // current position loop variable ("" = not in pos loop)
	curFunc    string         // current function name ("OnInit", "OnTick", "userFunc", "")
	stdImports map[string]bool // stdlib packages used in generated code
}

func (g *irGenerator) generate() string {
	// Generate body first to track which stdlib imports are needed.
	var body strings.Builder
	oldB := g.b
	g.b = body
	g.genStruct()
	g.genOnInit()
	g.genOnBar()
	g.genOnTick()
	g.genOnTimer()
	g.genOnDeinit()
	g.genUserFuncs()
	body = g.b
	g.b = oldB

	// Now emit header with tracked imports, then body.
	g.genHeader()
	g.b.WriteString(body.String())
	return g.b.String()
}

// ── Header ────────────────────────────────────────────────────────

func (g *irGenerator) genHeader() {
	g.emit("// Code generated by mql2go from interp.IR. DO NOT EDIT.")
	g.emitf("package %s", g.pkg)
	g.emit("")
	g.emit("import (")
	g.emitf("\t\"anttrader/strategy/sdk\"")
	g.emit("")
	g.emit("\t\"github.com/shopspring/decimal\"")
	// Conditionally import stdlib packages used by generated builtins.
	stdPkgs := []string{"fmt", "math", "strings", "time"}
	for _, pkg := range stdPkgs {
		if g.stdImports[pkg] {
			g.emitf("\t\"%s\"", pkg)
		}
	}
	g.emit(")")
	g.emit("")
}

// ── Struct ────────────────────────────────────────────────────────

func (g *irGenerator) genStruct() {
	g.emitf("// %s is an imported MQL strategy (read-only export preview).", g.name)
	g.emitf("type %s struct {", g.name)
	g.indent++
	for _, p := range g.ir.Params {
		g.param[p.Name] = true
		g.emitf("%s %s", p.Name, irParamGoType(p.Type))
		if isIntType(p.Type) {
			g.intVars[p.Name] = true
		}
	}
	for _, gl := range g.ir.Globals {
		if g.param[gl.Name] {
			continue
		}
		g.param[gl.Name] = true
		if !isMQLPrimitiveType(gl.Type) {
			continue
		}
		goType := irParamGoType(gl.Type)
		if goType == "interface{}" {
			goType = "decimal.Decimal"
		}
		g.emitf("%s %s", gl.Name, goType)
		if isIntType(gl.Type) {
			g.intVars[gl.Name] = true
		}
	}
	g.indent--
	g.emit("}")
	g.emitf("var _ sdk.Strategy = (*%s)(nil)", g.name)
	if len(g.ir.OnTick) > 0 {
		g.emitf("var _ sdk.TickStrategy = (*%s)(nil)", g.name)
	}
	if len(g.ir.OnTimer) > 0 {
		g.emitf("var _ sdk.TimerStrategy = (*%s)(nil)", g.name)
	}
	g.emit("")
}

// ── OnInit ────────────────────────────────────────────────────────

func (g *irGenerator) genOnInit() {
	g.curFunc = "OnInit"
	g.emitf("func (s *%s) OnInit(ctx sdk.Context) error {", g.name)
	g.indent++
	for _, p := range g.ir.Params {
		g.emitIRParamInit(p)
	}
	if len(g.ir.OnInit) > 0 {
		g.emitStmts(g.ir.OnInit)
	}
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

func (g *irGenerator) emitIRParamInit(p interp.ParamDecl) {
	switch p.Type {
	case "int", "long":
		def := "0"
		if p.Default != nil {
			def = g.expr(p.Default)
		}
		g.emitf("s.%s = int32(ctx.ParamInt(%q, %s))", p.Name, p.Name, def)
	case "double", "float":
		def := "decimal.Zero"
		if p.Default != nil {
			def = g.expr(p.Default)
		}
		g.emitf("s.%s = ctx.ParamDecimal(%q, %s)", p.Name, p.Name, def)
	case "string":
		def := `""`
		if p.Default != nil {
			def = g.expr(p.Default)
		}
		g.emitf("s.%s = ctx.ParamString(%q, %s)", p.Name, p.Name, def)
	case "bool":
		def := "false"
		if p.Default != nil {
			def = g.expr(p.Default)
		}
		g.emitf("s.%s = ctx.ParamBool(%q, %s)", p.Name, p.Name, def)
	}
}

// ── OnBar ─────────────────────────────────────────────────────────

func (g *irGenerator) genOnBar() {
	g.curFunc = "OnBar"
	g.emitf("func (s *%s) OnBar(ctx sdk.Context, tf string) (*sdk.Signal, error) {", g.name)
	g.indent++
	if len(g.ir.OnBar) > 0 {
		g.emitStmts(g.ir.OnBar)
	}
	g.emit("return nil, nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── OnTick ────────────────────────────────────────────────────────

func (g *irGenerator) genOnTick() {
	g.curFunc = "OnTick"
	if len(g.ir.OnTick) == 0 {
		return
	}
	g.emitf("func (s *%s) OnTick(ctx sdk.Context, bid, ask decimal.Decimal) (*sdk.Signal, error) {", g.name)
	g.indent++
	g.emitStmts(g.ir.OnTick)
	g.emit("return nil, nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── OnTimer ───────────────────────────────────────────────────────

func (g *irGenerator) genOnTimer() {
	g.curFunc = "OnTimer"
	if len(g.ir.OnTimer) == 0 {
		return
	}
	g.emitf("func (s *%s) OnTimer(ctx sdk.Context) (*sdk.Signal, error) {", g.name)
	g.indent++
	g.emitStmts(g.ir.OnTimer)
	g.emit("return nil, nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── OnDeinit ──────────────────────────────────────────────────────

func (g *irGenerator) genOnDeinit() {
	g.curFunc = "OnDeinit"
	g.emitf("func (s *%s) OnDeinit(ctx sdk.Context, reason string) error {", g.name)
	g.indent++
	if len(g.ir.OnDeinit) > 0 {
		g.emitStmts(g.ir.OnDeinit)
	}
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── User-defined functions ────────────────────────────────────────

func (g *irGenerator) genUserFuncs() {
	for name, fn := range g.ir.Funcs {
		g.emitUserFunc(name, fn)
	}
}

func (g *irGenerator) emitUserFunc(name string, fn *interp.FuncDef) {
	g.curFunc = "userFunc"
	params := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		params[i] = fmt.Sprintf("%s %s", p.Name, irParamGoType(p.Type))
	}
	g.emitf("func (s *%s) %s(%s) interface{} {", g.name, name, strings.Join(params, ", "))
	g.indent++
	if len(fn.Body) > 0 {
		g.emitStmts(fn.Body)
	}
	g.emit("return nil")
	g.indent--
	g.emit("}")
	g.emit("")
}

// ── Output helpers ────────────────────────────────────────────────

func (g *irGenerator) emit(s string) {
	g.b.WriteString(strings.Repeat("\t", g.indent))
	g.b.WriteString(s)
	g.b.WriteByte('\n')
}

func (g *irGenerator) emitf(format string, args ...interface{}) {
	g.emit(fmt.Sprintf(format, args...))
}

func (g *irGenerator) emitStmts(stmts []interp.Statement) {
	for i := range stmts {
		g.emitStmt(&stmts[i])
	}
}

// irParamGoType maps MQL type strings to Go types for struct fields.
func irParamGoType(t string) string {
	switch t {
	case "int", "long", "uint":
		return "int32"
	case "double", "float":
		return "decimal.Decimal"
	case "bool":
		return "bool"
	case "string":
		return "string"
	default:
		return "interface{}"
	}
}

func irPkgName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	if b.Len() == 0 {
		return "strategy"
	}
	return b.String()
}

func isIntType(t string) bool {
	switch t {
	case "int", "long", "uint", "short", "char", "uchar", "ushort", "ulong":
		return true
	}
	return false
}
