// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to en
const Common = {
  "common": {
    "unknownError": "Unknown error",
    "copied": "Copy All",
    "deleteFailed": "Delete failed",
    "operationFailed": "Operation failed",
    "saveSuccess": "Saved successfully",
    "refresh": "刷新",
    "loading": "加载中...",
    "saveFailed": "Save failed",
    "noData": "No logs found",
    "confirm": "确认",
    "cancel": "取消"
  }
} as const;
export default Common;
