// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to en
const Common = {
  "common": {
    "unknownError": "Unknown error",
    "copied": "Copy All",
    "deleteFailed": "Delete failed",
    "operationFailed": "Operation failed",
    "saveSuccess": "Saved successfully",
    "refresh": "Refresh",
    "loading": "Loading...",
    "saveFailed": "Save failed",
    "noData": "No logs found",
    "confirm": "Confirm",
    "cancel": "Cancel",
    "active": "Active",
    "inactive": "Inactive",
    "submit": "Submit"
  },
  "feedback": {
    "rateSession": "Rate this session",
    "good": "Good",
    "bad": "Bad",
    "addReason": "Add reason",
    "reasonPlaceholder": "What went well or what could be better?"
  },
  "credit": {
    "balance": "Credit Balance",
    "frozen": "Frozen",
    "credits": "credits",
    "history": "Transaction History",
    "type": "Type",
    "amount": "Amount",
    "balanceAfter": "Balance After",
    "description": "Description",
    "time": "Time"
  }
} as const;
export default Common;
