// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to en
const Common = {
  "common": {
    "unknownError": "Unknown error",
    "copied": "Copy All",
    "deleteFailed": "Delete failed",
    "operationFailed": "Operation failed",
    "saveSuccess": "Saved successfully",
    "refresh": "Refresh",
    "loading": "Loading...",
    "saveFailed": "Save failed",
    "noData": "No logs found",
    "confirm": "Confirm",
    "cancel": "Cancel",
    "active": "Active",
    "inactive": "Inactive"
  }
} as const;
export default Common;
