// Auto-generated by scripts/generate-missing-i18n.mjs
const Market = {
  "market": {
    "allSymbols": "All Symbols",
    "selectSymbol": "Select symbol",
    "loadingSymbols": "No symbols found"
  }
} as const;
export default Market;
