// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to en
const SharePage = {
  "sharePage": {
    "noPositions": "No open positions",
    "positionsLocked": "Positions hidden by creator"
  }
} as const;
export default SharePage;
