// Auto-generated by scripts/generate-missing-i18n.mjs + manual share keys
const SharePage = {
  "sharePage": {
    "noPositions": "No open positions",
    "positionsLocked": "Positions hidden by creator",
    "notFound": "Strategy not found or no longer available",
    "backtestReturn": "Backtest Return",
    "maxDrawdown": "Max Drawdown",
    "livePerformance": "Live Performance",
    "liveReturn": "Live Return",
    "liveMaxDD": "Live Max DD",
    "codePreview": "Code Preview"
  }
} as const;
export default SharePage;
