# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import account_entity_pb2 as account__entity__pb2
import account_crud_pb2 as account__crud__pb2
import account_connection_pb2 as account__connection__pb2
import account_permission_pb2 as account__permission__pb2

from account_entity_pb2 import *
from account_crud_pb2 import *
from account_connection_pb2 import *
from account_permission_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x06\x61nt.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14\x61\x63\x63ount_entity.proto\x1a\x12\x61\x63\x63ount_crud.proto\x1a\x18\x61\x63\x63ount_connection.proto\x1a\x18\x61\x63\x63ount_permission.proto2\xae\x07\n\x0e\x41\x63\x63ountService\x12I\n\x0cListAccounts\x12\x1b.ant.v1.ListAccountsRequest\x1a\x1c.ant.v1.ListAccountsResponse\x12\x38\n\nGetAccount\x12\x19.ant.v1.GetAccountRequest\x1a\x0f.ant.v1.Account\x12>\n\rCreateAccount\x12\x1c.ant.v1.CreateAccountRequest\x1a\x0f.ant.v1.Account\x12>\n\rUpdateAccount\x12\x1c.ant.v1.UpdateAccountRequest\x1a\x0f.ant.v1.Account\x12\x45\n\rDeleteAccount\x12\x1c.ant.v1.DeleteAccountRequest\x1a\x16.google.protobuf.Empty\x12O\n\x0e\x43onnectAccount\x12\x1d.ant.v1.ConnectAccountRequest\x1a\x1e.ant.v1.ConnectAccountResponse\x12M\n\x11\x44isconnectAccount\x12 .ant.v1.DisconnectAccountRequest\x1a\x16.google.protobuf.Empty\x12K\n\x10ReconnectAccount\x12\x1f.ant.v1.ReconnectAccountRequest\x1a\x16.google.protobuf.Empty\x12I\n\x0cSearchBroker\x12\x1b.ant.v1.SearchBrokerRequest\x1a\x1c.ant.v1.SearchBrokerResponse\x12\x64\n\x15VerifyTradePermission\x12$.ant.v1.VerifyTradePermissionRequest\x1a%.ant.v1.VerifyTradePermissionResponse\x12\x64\n\x15UpdateTradingPassword\x12$.ant.v1.UpdateTradingPasswordRequest\x1a%.ant.v1.UpdateTradingPasswordResponse\x12L\n\rVerifyAccount\x12\x1c.ant.v1.VerifyAccountRequest\x1a\x1d.ant.v1.VerifyAccountResponseB\"Z anttrader/gen/proto/ant/v1;antv1P\x01P\x02P\x03P\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _ACCOUNTSERVICE._serialized_start=149
  _ACCOUNTSERVICE._serialized_end=1091
# @@protoc_insertion_point(module_scope)
