# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_entity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x63\x63ount_entity.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x04\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05login\x18\x03 \x01(\t\x12\x0f\n\x07mt_type\x18\x04 \x01(\t\x12\x16\n\x0e\x62roker_company\x18\x05 \x01(\t\x12\x15\n\rbroker_server\x18\x06 \x01(\t\x12\x13\n\x0b\x62roker_host\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\r\n\x05token\x18\t \x01(\t\x12\x13\n\x0bis_disabled\x18\n \x01(\x08\x12\x12\n\nlast_error\x18\x0b \x01(\t\x12\x30\n\x0c\x63onnected_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x62\x61lance\x18\x0f \x01(\x01\x12\x0e\n\x06\x63redit\x18\x10 \x01(\x01\x12\x0e\n\x06\x65quity\x18\x11 \x01(\x01\x12\x0e\n\x06margin\x18\x12 \x01(\x01\x12\x13\n\x0b\x66ree_margin\x18\x13 \x01(\x01\x12\x14\n\x0cmargin_level\x18\x14 \x01(\x01\x12\x10\n\x08leverage\x18\x15 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x16 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_type\x18\x17 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_method\x18\x18 \x01(\t\x12\x13\n\x0bis_investor\x18\x19 \x01(\x08\x12\r\n\x05\x61lias\x18\x1a \x01(\t\x12\x0e\n\x06profit\x18\x1b \x01(\x01\x12\x16\n\x0eprofit_percent\x18\x1c \x01(\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_entity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _ACCOUNT._serialized_start=66
  _ACCOUNT._serialized_end=688
# @@protoc_insertion_point(module_scope)
