# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61\x63\x63ount_connection.proto\x12\x06\x61nt.v1\"#\n\x15\x43onnectAccountRequest\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x16\x43onnectAccountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x18\x44isconnectAccountRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x17ReconnectAccountRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x13SearchBrokerRequest\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\x12\x0f\n\x07mt_type\x18\x02 \x01(\t\"@\n\x14SearchBrokerResponse\x12(\n\tcompanies\x18\x01 \x03(\x0b\x32\x15.ant.v1.BrokerCompany\"L\n\rBrokerCompany\x12\x14\n\x0c\x63ompany_name\x18\x01 \x01(\t\x12%\n\x07servers\x18\x02 \x03(\x0b\x32\x14.ant.v1.BrokerServer\",\n\x0c\x42rokerServer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x02 \x03(\tB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _CONNECTACCOUNTREQUEST._serialized_start=36
  _CONNECTACCOUNTREQUEST._serialized_end=71
  _CONNECTACCOUNTRESPONSE._serialized_start=73
  _CONNECTACCOUNTRESPONSE._serialized_end=131
  _DISCONNECTACCOUNTREQUEST._serialized_start=133
  _DISCONNECTACCOUNTREQUEST._serialized_end=171
  _RECONNECTACCOUNTREQUEST._serialized_start=173
  _RECONNECTACCOUNTREQUEST._serialized_end=210
  _SEARCHBROKERREQUEST._serialized_start=212
  _SEARCHBROKERREQUEST._serialized_end=267
  _SEARCHBROKERRESPONSE._serialized_start=269
  _SEARCHBROKERRESPONSE._serialized_end=333
  _BROKERCOMPANY._serialized_start=335
  _BROKERCOMPANY._serialized_end=411
  _BROKERSERVER._serialized_start=413
  _BROKERSERVER._serialized_end=457
# @@protoc_insertion_point(module_scope)
