# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_permission.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61\x63\x63ount_permission.proto\x12\x06\x61nt.v1\"*\n\x1cVerifyTradePermissionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"u\n\x1dVerifyTradePermissionResponse\x12\x1c\n\x14has_trade_permission\x18\x01 \x01(\x08\x12\x13\n\x0bis_investor\x18\x02 \x01(\x08\x12\x10\n\x08verified\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"V\n\x1cUpdateTradingPasswordRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cnew_password\x18\x02 \x01(\t\x12\x14\n\x0cold_password\x18\x03 \x01(\t\"t\n\x1dUpdateTradingPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x14has_trade_permission\x18\x02 \x01(\x08\x12\x13\n\x0bis_investor\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"]\n\x14VerifyAccountRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07mt_type\x18\x03 \x01(\t\x12\x13\n\x0b\x62roker_host\x18\x04 \x01(\t\"\xba\x01\n\x15VerifyAccountResponse\x12\x10\n\x08verified\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x01\x12\x0e\n\x06\x65quity\x18\x04 \x01(\x01\x12\x0e\n\x06margin\x18\x05 \x01(\x01\x12\x13\n\x0b\x66ree_margin\x18\x06 \x01(\x01\x12\x10\n\x08leverage\x18\x07 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x08 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_type\x18\t \x01(\tB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_permission_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _VERIFYTRADEPERMISSIONREQUEST._serialized_start=36
  _VERIFYTRADEPERMISSIONREQUEST._serialized_end=78
  _VERIFYTRADEPERMISSIONRESPONSE._serialized_start=80
  _VERIFYTRADEPERMISSIONRESPONSE._serialized_end=197
  _UPDATETRADINGPASSWORDREQUEST._serialized_start=199
  _UPDATETRADINGPASSWORDREQUEST._serialized_end=285
  _UPDATETRADINGPASSWORDRESPONSE._serialized_start=287
  _UPDATETRADINGPASSWORDRESPONSE._serialized_end=403
  _VERIFYACCOUNTREQUEST._serialized_start=405
  _VERIFYACCOUNTREQUEST._serialized_end=498
  _VERIFYACCOUNTRESPONSE._serialized_start=501
  _VERIFYACCOUNTRESPONSE._serialized_end=687
# @@protoc_insertion_point(module_scope)
