# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_crud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import account_entity_pb2 as account__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x63\x63ount_crud.proto\x12\x06\x61nt.v1\x1a\x14\x61\x63\x63ount_entity.proto\"\x15\n\x13ListAccountsRequest\"9\n\x14ListAccountsResponse\x12!\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x0f.ant.v1.Account\"\x1f\n\x11GetAccountRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x8c\x01\n\x14\x43reateAccountRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07mt_type\x18\x03 \x01(\t\x12\x16\n\x0e\x62roker_company\x18\x04 \x01(\t\x12\x15\n\rbroker_server\x18\x05 \x01(\t\x12\x13\n\x0b\x62roker_host\x18\x06 \x01(\t\"\xd4\x01\n\x14UpdateAccountRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x0e\x62roker_company\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rbroker_server\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x62roker_host\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0bis_disabled\x18\x05 \x01(\x08H\x03\x88\x01\x01\x42\x11\n\x0f_broker_companyB\x10\n\x0e_broker_serverB\x0e\n\x0c_broker_hostB\x0e\n\x0c_is_disabled\"4\n\x14\x44\x65leteAccountRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\tB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_crud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LISTACCOUNTSREQUEST._serialized_start=52
  _LISTACCOUNTSREQUEST._serialized_end=73
  _LISTACCOUNTSRESPONSE._serialized_start=75
  _LISTACCOUNTSRESPONSE._serialized_end=132
  _GETACCOUNTREQUEST._serialized_start=134
  _GETACCOUNTREQUEST._serialized_end=165
  _CREATEACCOUNTREQUEST._serialized_start=168
  _CREATEACCOUNTREQUEST._serialized_end=308
  _UPDATEACCOUNTREQUEST._serialized_start=311
  _UPDATEACCOUNTREQUEST._serialized_end=523
  _DELETEACCOUNTREQUEST._serialized_start=525
  _DELETEACCOUNTREQUEST._serialized_end=577
# @@protoc_insertion_point(module_scope)
