# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x64min_config.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n\x0cSystemConfig\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x14\n\x12ListConfigsRequest\"<\n\x13ListConfigsResponse\x12%\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32\x14.ant.v1.SystemConfig\"C\n\x10SetConfigRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x13\n\x11SetConfigResponse\":\n\x1aToggleConfigEnabledRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\"\x1d\n\x1bToggleConfigEnabledResponse2\xfe\x01\n\x12\x41\x64minConfigService\x12\x46\n\x0bListConfigs\x12\x1a.ant.v1.ListConfigsRequest\x1a\x1b.ant.v1.ListConfigsResponse\x12@\n\tSetConfig\x12\x18.ant.v1.SetConfigRequest\x1a\x19.ant.v1.SetConfigResponse\x12^\n\x13ToggleConfigEnabled\x12\".ant.v1.ToggleConfigEnabledRequest\x1a#.ant.v1.ToggleConfigEnabledResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _SYSTEMCONFIG._serialized_start=64
  _SYSTEMCONFIG._serialized_end=240
  _LISTCONFIGSREQUEST._serialized_start=242
  _LISTCONFIGSREQUEST._serialized_end=262
  _LISTCONFIGSRESPONSE._serialized_start=264
  _LISTCONFIGSRESPONSE._serialized_end=324
  _SETCONFIGREQUEST._serialized_start=326
  _SETCONFIGREQUEST._serialized_end=393
  _SETCONFIGRESPONSE._serialized_start=395
  _SETCONFIGRESPONSE._serialized_end=414
  _TOGGLECONFIGENABLEDREQUEST._serialized_start=416
  _TOGGLECONFIGENABLEDREQUEST._serialized_end=474
  _TOGGLECONFIGENABLEDRESPONSE._serialized_start=476
  _TOGGLECONFIGENABLEDRESPONSE._serialized_end=505
  _ADMINCONFIGSERVICE._serialized_start=508
  _ADMINCONFIGSERVICE._serialized_end=762
# @@protoc_insertion_point(module_scope)
