# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin_system.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x64min_system.proto\x12\x06\x61nt.v1\"\x14\n\x12HealthCheckRequest\"c\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tdb_status\x18\x02 \x01(\t\x12\x14\n\x0credis_status\x18\x03 \x01(\t\x12\x13\n\x0bnats_status\x18\x04 \x01(\t\"\x8a\x01\n\x0bMetricPoint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12/\n\x06labels\x18\x03 \x03(\x0b\x32\x1f.ant.v1.MetricPoint.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x13\n\x11GetMetricsRequest\":\n\x12GetMetricsResponse\x12$\n\x07metrics\x18\x01 \x03(\x0b\x32\x13.ant.v1.MetricPoint\"\'\n\x13ResolveAlertRequest\x12\x10\n\x08\x61lert_id\x18\x01 \x01(\t\"\x16\n\x14ResolveAlertResponse\"\x13\n\x11\x43learCacheRequest\"\x14\n\x12\x43learCacheResponse\"&\n\x16InvalidateCacheRequest\x12\x0c\n\x04tags\x18\x01 \x03(\t\"\x19\n\x17InvalidateCacheResponse2\x85\x03\n\x12\x41\x64minSystemService\x12\x46\n\x0bHealthCheck\x12\x1a.ant.v1.HealthCheckRequest\x1a\x1b.ant.v1.HealthCheckResponse\x12\x43\n\nGetMetrics\x12\x19.ant.v1.GetMetricsRequest\x1a\x1a.ant.v1.GetMetricsResponse\x12I\n\x0cResolveAlert\x12\x1b.ant.v1.ResolveAlertRequest\x1a\x1c.ant.v1.ResolveAlertResponse\x12\x43\n\nClearCache\x12\x19.ant.v1.ClearCacheRequest\x1a\x1a.ant.v1.ClearCacheResponse\x12R\n\x0fInvalidateCache\x12\x1e.ant.v1.InvalidateCacheRequest\x1a\x1f.ant.v1.InvalidateCacheResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_system_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _METRICPOINT_LABELSENTRY._options = None
  _METRICPOINT_LABELSENTRY._serialized_options = b'8\001'
  _HEALTHCHECKREQUEST._serialized_start=30
  _HEALTHCHECKREQUEST._serialized_end=50
  _HEALTHCHECKRESPONSE._serialized_start=52
  _HEALTHCHECKRESPONSE._serialized_end=151
  _METRICPOINT._serialized_start=154
  _METRICPOINT._serialized_end=292
  _METRICPOINT_LABELSENTRY._serialized_start=247
  _METRICPOINT_LABELSENTRY._serialized_end=292
  _GETMETRICSREQUEST._serialized_start=294
  _GETMETRICSREQUEST._serialized_end=313
  _GETMETRICSRESPONSE._serialized_start=315
  _GETMETRICSRESPONSE._serialized_end=373
  _RESOLVEALERTREQUEST._serialized_start=375
  _RESOLVEALERTREQUEST._serialized_end=414
  _RESOLVEALERTRESPONSE._serialized_start=416
  _RESOLVEALERTRESPONSE._serialized_end=438
  _CLEARCACHEREQUEST._serialized_start=440
  _CLEARCACHEREQUEST._serialized_end=459
  _CLEARCACHERESPONSE._serialized_start=461
  _CLEARCACHERESPONSE._serialized_end=481
  _INVALIDATECACHEREQUEST._serialized_start=483
  _INVALIDATECACHEREQUEST._serialized_end=521
  _INVALIDATECACHERESPONSE._serialized_start=523
  _INVALIDATECACHERESPONSE._serialized_end=548
  _ADMINSYSTEMSERVICE._serialized_start=551
  _ADMINSYSTEMSERVICE._serialized_end=940
# @@protoc_insertion_point(module_scope)
