# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin_trading.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x64min_trading.proto\x12\x06\x61nt.v1\"@\n\x18GetTradingSummaryRequest\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\"\x92\x02\n\x0eTradingSummary\x12%\n\x06period\x18\x01 \x01(\x0b\x32\x15.ant.v1.TradingPeriod\x12)\n\x08overview\x18\x02 \x01(\x0b\x32\x17.ant.v1.TradingOverview\x12%\n\x07trading\x18\x03 \x01(\x0b\x32\x14.ant.v1.TradingStats\x12;\n\x0b\x62y_platform\x18\x04 \x03(\x0b\x32&.ant.v1.TradingSummary.ByPlatformEntry\x1aJ\n\x0f\x42yPlatformEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.ant.v1.PlatformSummary:\x02\x38\x01\"5\n\rTradingPeriod\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\"p\n\x0fTradingOverview\x12\x13\n\x0btotal_users\x18\x01 \x01(\x03\x12\x14\n\x0c\x61\x63tive_users\x18\x02 \x01(\x03\x12\x16\n\x0etotal_accounts\x18\x03 \x01(\x03\x12\x1a\n\x12\x63onnected_accounts\x18\x04 \x01(\x03\"\xa7\x01\n\x0cTradingStats\x12\x14\n\x0ctotal_orders\x18\x01 \x01(\x03\x12\x15\n\rclosed_orders\x18\x02 \x01(\x03\x12\x16\n\x0epending_orders\x18\x03 \x01(\x03\x12\x14\n\x0ctotal_volume\x18\x04 \x01(\x01\x12\x14\n\x0ctotal_profit\x18\x05 \x01(\x01\x12\x12\n\ntotal_loss\x18\x06 \x01(\x01\x12\x12\n\nnet_profit\x18\x07 \x01(\x01\"C\n\x0fPlatformSummary\x12\x10\n\x08\x61\x63\x63ounts\x18\x01 \x01(\x03\x12\x0e\n\x06orders\x18\x02 \x01(\x03\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x32\x64\n\x13\x41\x64minTradingService\x12M\n\x11GetTradingSummary\x12 .ant.v1.GetTradingSummaryRequest\x1a\x16.ant.v1.TradingSummaryB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_trading_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _TRADINGSUMMARY_BYPLATFORMENTRY._options = None
  _TRADINGSUMMARY_BYPLATFORMENTRY._serialized_options = b'8\001'
  _GETTRADINGSUMMARYREQUEST._serialized_start=31
  _GETTRADINGSUMMARYREQUEST._serialized_end=95
  _TRADINGSUMMARY._serialized_start=98
  _TRADINGSUMMARY._serialized_end=372
  _TRADINGSUMMARY_BYPLATFORMENTRY._serialized_start=298
  _TRADINGSUMMARY_BYPLATFORMENTRY._serialized_end=372
  _TRADINGPERIOD._serialized_start=374
  _TRADINGPERIOD._serialized_end=427
  _TRADINGOVERVIEW._serialized_start=429
  _TRADINGOVERVIEW._serialized_end=541
  _TRADINGSTATS._serialized_start=544
  _TRADINGSTATS._serialized_end=711
  _PLATFORMSUMMARY._serialized_start=713
  _PLATFORMSUMMARY._serialized_end=780
  _ADMINTRADINGSERVICE._serialized_start=782
  _ADMINTRADINGSERVICE._serialized_end=882
# @@protoc_insertion_point(module_scope)
