# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin_log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61\x64min_log.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n\x08\x41\x64minLog\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x64min_id\x18\x02 \x01(\t\x12\x0e\n\x06module\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x04 \x01(\t\x12\x13\n\x0btarget_type\x18\x05 \x01(\t\x12\x11\n\ttarget_id\x18\x06 \x01(\t\x12\x12\n\nip_address\x18\x07 \x01(\t\x12\x12\n\nuser_agent\x18\x08 \x01(\t\x12\x16\n\x0erequest_method\x18\t \x01(\t\x12\x14\n\x0crequest_path\x18\n \x01(\t\x12\x0f\n\x07success\x18\x0b \x01(\x08\x12\x15\n\rerror_message\x18\x0c \x01(\t\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8f\x01\n\x0fListLogsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x0e\n\x06module\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x04 \x01(\t\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\x12\x10\n\x08\x61\x64min_id\x18\x07 \x01(\t\"A\n\x10ListLogsResponse\x12\x1e\n\x04logs\x18\x01 \x03(\x0b\x32\x10.ant.v1.AdminLog\x12\r\n\x05total\x18\x02 \x01(\x03\x32P\n\x0f\x41\x64minLogService\x12=\n\x08ListLogs\x12\x17.ant.v1.ListLogsRequest\x1a\x18.ant.v1.ListLogsResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _ADMINLOG._serialized_start=61
  _ADMINLOG._serialized_end=352
  _LISTLOGSREQUEST._serialized_start=355
  _LISTLOGSREQUEST._serialized_end=498
  _LISTLOGSRESPONSE._serialized_start=500
  _LISTLOGSRESPONSE._serialized_end=565
  _ADMINLOGSERVICE._serialized_start=567
  _ADMINLOGSERVICE._serialized_end=647
# @@protoc_insertion_point(module_scope)
