# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ai_conversation_pb2 as ai__conversation__pb2
import ai_chat_requests_pb2 as ai__chat__requests__pb2

from ai_conversation_pb2 import *
from ai_chat_requests_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rai_chat.proto\x12\x06\x61nt.v1\x1a\x15\x61i_conversation.proto\x1a\x16\x61i_chat_requests.protoB\"Z anttrader/gen/proto/ant/v1;antv1P\x00P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
# @@protoc_insertion_point(module_scope)
