# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_gate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rai_gate.proto\x12\x06\x61nt.v1\"\xda\x01\n\x18RunGateEvaluationRequest\x12\x17\n\x0f\x62\x61\x63ktest_run_id\x18\x01 \x01(\t\x12\x12\n\nexpression\x18\x02 \x01(\t\x12\x14\n\x0cnum_attempts\x18\x03 \x01(\x05\x12\x12\n\npaper_days\x18\x04 \x01(\x05\x12\x15\n\rpaper_net_pnl\x18\x05 \x01(\x01\x12\x18\n\x10paper_net_return\x18\x06 \x01(\x01\x12\x1b\n\x13\x62\x61\x63ktest_net_return\x18\x07 \x01(\x01\x12\x19\n\x11paper_trade_count\x18\x08 \x01(\x05\"h\n\x14GateEvaluationUpdate\x12 \n\x04gate\x18\x01 \x01(\x0b\x32\x12.ant.v1.GateResult\x12.\n\tcompleted\x18\x02 \x01(\x0b\x32\x1b.ant.v1.GatePipelineSummary\"o\n\nGateResult\x12\x0c\n\x04gate\x18\x01 \x01(\t\x12\x0e\n\x06passed\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x03\x12\x0f\n\x07skipped\x18\x06 \x01(\x08\"e\n\x13GatePipelineSummary\x12\x0e\n\x06passed\x18\x01 \x01(\x08\x12\x12\n\nfirst_fail\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x19\n\x11total_duration_ms\x18\x04 \x01(\x03\x32`\n\x0bGateService\x12Q\n\rRunEvaluation\x12 .ant.v1.RunGateEvaluationRequest\x1a\x1c.ant.v1.GateEvaluationUpdate0\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_gate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _RUNGATEEVALUATIONREQUEST._serialized_start=26
  _RUNGATEEVALUATIONREQUEST._serialized_end=244
  _GATEEVALUATIONUPDATE._serialized_start=246
  _GATEEVALUATIONUPDATE._serialized_end=350
  _GATERESULT._serialized_start=352
  _GATERESULT._serialized_end=463
  _GATEPIPELINESUMMARY._serialized_start=465
  _GATEPIPELINESUMMARY._serialized_end=566
  _GATESERVICE._serialized_start=568
  _GATESERVICE._serialized_end=664
# @@protoc_insertion_point(module_scope)
