# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"l\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\x12\x1a\n\x04user\x18\x04 \x01(\x0b\x32\x0c.ant.v1.User\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"W\n\x14RefreshTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\"+\n\rGetMeResponse\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.ant.v1.User\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\".\n\x10RegisterResponse\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.ant.v1.User\"\xcf\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bpermissions\x18\x07 \x03(\t\x12\x17\n\x0f\x63\x61pability_tier\x18\x08 \x01(\x05\x32\xbf\x02\n\x0b\x41uthService\x12\x34\n\x05Login\x12\x14.ant.v1.LoginRequest\x1a\x15.ant.v1.LoginResponse\x12\x38\n\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12I\n\x0cRefreshToken\x12\x1b.ant.v1.RefreshTokenRequest\x1a\x1c.ant.v1.RefreshTokenResponse\x12\x36\n\x05GetMe\x12\x16.google.protobuf.Empty\x1a\x15.ant.v1.GetMeResponse\x12=\n\x08Register\x12\x17.ant.v1.RegisterRequest\x1a\x18.ant.v1.RegisterResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LOGINREQUEST._serialized_start=84
  _LOGINREQUEST._serialized_end=131
  _LOGINRESPONSE._serialized_start=133
  _LOGINRESPONSE._serialized_end=241
  _REFRESHTOKENREQUEST._serialized_start=243
  _REFRESHTOKENREQUEST._serialized_end=287
  _REFRESHTOKENRESPONSE._serialized_start=289
  _REFRESHTOKENRESPONSE._serialized_end=376
  _GETMERESPONSE._serialized_start=378
  _GETMERESPONSE._serialized_end=421
  _REGISTERREQUEST._serialized_start=423
  _REGISTERREQUEST._serialized_end=491
  _REGISTERRESPONSE._serialized_start=493
  _REGISTERRESPONSE._serialized_end=539
  _USER._serialized_start=542
  _USER._serialized_end=749
  _AUTHSERVICE._serialized_start=752
  _AUTHSERVICE._serialized_end=1071
# @@protoc_insertion_point(module_scope)
