# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auto_trading_logs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61uto_trading_logs.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n\x15GetTradingLogsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x10\n\x08log_type\x18\x04 \x01(\t\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\"I\n\x16GetTradingLogsResponse\x12 \n\x04logs\x18\x01 \x03(\x0b\x32\x12.ant.v1.TradingLog\x12\r\n\x05total\x18\x02 \x01(\x05\"=\n\x1bGetRecentTradingLogsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"@\n\x1cGetRecentTradingLogsResponse\x12 \n\x04logs\x18\x01 \x03(\x0b\x32\x12.ant.v1.TradingLog\"\x84\x02\n\nTradingLog\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x04 \x01(\t\x12\x10\n\x08log_type\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\x12\x0e\n\x06symbol\x18\x07 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x08 \x01(\t\x12\x0e\n\x06volume\x18\t \x01(\x01\x12\r\n\x05price\x18\n \x01(\x01\x12\x0e\n\x06ticket\x18\x0b \x01(\x03\x12\x0e\n\x06profit\x18\x0c \x01(\x01\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.TimestampB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto_trading_logs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _GETTRADINGLOGSREQUEST._serialized_start=69
  _GETTRADINGLOGSREQUEST._serialized_end=198
  _GETTRADINGLOGSRESPONSE._serialized_start=200
  _GETTRADINGLOGSRESPONSE._serialized_end=273
  _GETRECENTTRADINGLOGSREQUEST._serialized_start=275
  _GETRECENTTRADINGLOGSREQUEST._serialized_end=336
  _GETRECENTTRADINGLOGSRESPONSE._serialized_start=338
  _GETRECENTTRADINGLOGSRESPONSE._serialized_end=402
  _TRADINGLOG._serialized_start=405
  _TRADINGLOG._serialized_end=665
# @@protoc_insertion_point(module_scope)
