# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auto_trading_risk_check.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61uto_trading_risk_check.proto\x12\x06\x61nt.v1\"\x95\x01\n\x16\x43heckRiskLimitsRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\x17\n\x0f\x63urrent_balance\x18\x04 \x01(\x01\x12\x16\n\x0e\x63urrent_equity\x18\x05 \x01(\x01\x12\x16\n\x0eopen_positions\x18\x06 \x01(\x05\"\xee\x01\n\x17\x43heckRiskLimitsResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x18\n\x10is_within_limits\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x15\n\rmax_positions\x18\x04 \x01(\x05\x12\x16\n\x0eposition_count\x18\x05 \x01(\x05\x12\x18\n\x10\x64\x61ily_loss_limit\x18\x06 \x01(\x01\x12\x17\n\x0f\x64\x61ily_loss_used\x18\x07 \x01(\x01\x12\x1c\n\x14max_drawdown_percent\x18\x08 \x01(\x01\x12\x18\n\x10\x64rawdown_percent\x18\t \x01(\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto_trading_risk_check_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _CHECKRISKLIMITSREQUEST._serialized_start=42
  _CHECKRISKLIMITSREQUEST._serialized_end=191
  _CHECKRISKLIMITSRESPONSE._serialized_start=194
  _CHECKRISKLIMITSRESPONSE._serialized_end=432
# @@protoc_insertion_point(module_scope)
