# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auto_trading_position_size.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n auto_trading_position_size.proto\x12\x06\x61nt.v1\"\x89\x01\n\x1c\x43\x61lculatePositionSizeRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x17\n\x0f\x61\x63\x63ount_balance\x18\x03 \x01(\x01\x12\x16\n\x0estop_loss_pips\x18\x04 \x01(\x01\x12\x14\n\x0crisk_percent\x18\x05 \x01(\x01\"\x7f\n\x1d\x43\x61lculatePositionSizeResponse\x12\x0e\n\x06volume\x18\x01 \x01(\x01\x12\x13\n\x0brisk_amount\x18\x02 \x01(\x01\x12\x11\n\tpip_value\x18\x03 \x01(\x01\x12\x12\n\nmin_volume\x18\x04 \x01(\x01\x12\x12\n\nmax_volume\x18\x05 \x01(\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto_trading_position_size_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _CALCULATEPOSITIONSIZEREQUEST._serialized_start=45
  _CALCULATEPOSITIONSIZEREQUEST._serialized_end=182
  _CALCULATEPOSITIONSIZERESPONSE._serialized_start=184
  _CALCULATEPOSITIONSIZERESPONSE._serialized_end=311
# @@protoc_insertion_point(module_scope)
