# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auto_trading.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import auto_trading_settings_pb2 as auto__trading__settings__pb2
import auto_trading_risk_pb2 as auto__trading__risk__pb2
try:
  auto__trading__risk__config__pb2 = auto__trading__risk__pb2.auto__trading__risk__config__pb2
except AttributeError:
  auto__trading__risk__config__pb2 = auto__trading__risk__pb2.auto_trading_risk_config_pb2
try:
  auto__trading__risk__check__pb2 = auto__trading__risk__pb2.auto__trading__risk__check__pb2
except AttributeError:
  auto__trading__risk__check__pb2 = auto__trading__risk__pb2.auto_trading_risk_check_pb2
try:
  auto__trading__position__size__pb2 = auto__trading__risk__pb2.auto__trading__position__size__pb2
except AttributeError:
  auto__trading__position__size__pb2 = auto__trading__risk__pb2.auto_trading_position_size_pb2
import auto_trading_logs_pb2 as auto__trading__logs__pb2

from auto_trading_settings_pb2 import *
from auto_trading_risk_pb2 import *
from auto_trading_logs_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uto_trading.proto\x12\x06\x61nt.v1\x1a\x1b\x61uto_trading_settings.proto\x1a\x17\x61uto_trading_risk.proto\x1a\x17\x61uto_trading_logs.proto2\xde\x06\n\x12\x41utoTradingService\x12M\n\x11GetGlobalSettings\x12 .ant.v1.GetGlobalSettingsRequest\x1a\x16.ant.v1.GlobalSettings\x12S\n\x14UpdateGlobalSettings\x12#.ant.v1.UpdateGlobalSettingsRequest\x1a\x16.ant.v1.GlobalSettings\x12R\n\x0fToggleAutoTrade\x12\x1e.ant.v1.ToggleAutoTradeRequest\x1a\x1f.ant.v1.ToggleAutoTradeResponse\x12\x41\n\rGetRiskConfig\x12\x1c.ant.v1.GetRiskConfigRequest\x1a\x12.ant.v1.RiskConfig\x12G\n\x10UpdateRiskConfig\x12\x1f.ant.v1.UpdateRiskConfigRequest\x1a\x12.ant.v1.RiskConfig\x12R\n\x0f\x43heckRiskLimits\x12\x1e.ant.v1.CheckRiskLimitsRequest\x1a\x1f.ant.v1.CheckRiskLimitsResponse\x12\x64\n\x15\x43\x61lculatePositionSize\x12$.ant.v1.CalculatePositionSizeRequest\x1a%.ant.v1.CalculatePositionSizeResponse\x12V\n\x14GetAutoTradingStatus\x12#.ant.v1.GetAutoTradingStatusRequest\x1a\x19.ant.v1.AutoTradingStatus\x12O\n\x0eGetTradingLogs\x12\x1d.ant.v1.GetTradingLogsRequest\x1a\x1e.ant.v1.GetTradingLogsResponse\x12\x61\n\x14GetRecentTradingLogs\x12#.ant.v1.GetRecentTradingLogsRequest\x1a$.ant.v1.GetRecentTradingLogsResponseB\"Z anttrader/gen/proto/ant/v1;antv1P\x00P\x01P\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto_trading_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _AUTOTRADINGSERVICE._serialized_start=110
  _AUTOTRADINGSERVICE._serialized_end=972
# @@protoc_insertion_point(module_scope)
