# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backtest_run_start.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import backtest_run_pb2 as backtest__run__pb2
import backtest_execution_config_pb2 as backtest__execution__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62\x61\x63ktest_run_start.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12\x62\x61\x63ktest_run.proto\x1a\x1f\x62\x61\x63ktest_execution_config.proto\"\xe4\x03\n\x17StartBacktestRunRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x11\n\ttimeframe\x18\x04 \x01(\t\x12\x17\n\x0finitial_capital\x18\x05 \x01(\x01\x12%\n\x04mode\x18\x06 \x01(\x0e\x32\x17.ant.v1.BacktestRunMode\x12-\n\x04\x66rom\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12+\n\x02to\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12\x17\n\ndataset_id\x18\t \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0btemplate_id\x18\n \x01(\tH\x03\x88\x01\x01\x12\x1e\n\x11template_draft_id\x18\x0b \x01(\tH\x04\x88\x01\x01\x12\x15\n\rextra_symbols\x18\x0c \x03(\t\x12\x39\n\x10\x65xecution_config\x18\r \x01(\x0b\x32\x1f.ant.v1.BacktestExecutionConfigB\x07\n\x05_fromB\x05\n\x03_toB\r\n\x0b_dataset_idB\x0e\n\x0c_template_idB\x14\n\x12_template_draft_id\"*\n\x18StartBacktestRunResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\tB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backtest_run_start_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _STARTBACKTESTRUNREQUEST._serialized_start=123
  _STARTBACKTESTRUNREQUEST._serialized_end=607
  _STARTBACKTESTRUNRESPONSE._serialized_start=609
  _STARTBACKTESTRUNRESPONSE._serialized_end=651
# @@protoc_insertion_point(module_scope)
