# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backtest_trades.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61\x63ktest_trades.proto\x12\x06\x61nt.v1\".\n\x1cListBacktestRunTradesRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"u\n\x1dListBacktestRunTradesResponse\x12%\n\x06trades\x18\x01 \x03(\x0b\x32\x15.ant.v1.BacktestTrade\x12-\n\x07summary\x18\x02 \x01(\x0b\x32\x1c.ant.v1.BacktestTradeSummary\"\xba\x01\n\rBacktestTrade\x12\x0e\n\x06ticket\x18\x01 \x01(\x03\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\x0f\n\x07open_ts\x18\x04 \x01(\x03\x12\x12\n\nopen_price\x18\x05 \x01(\x01\x12\x10\n\x08\x63lose_ts\x18\x06 \x01(\x03\x12\x13\n\x0b\x63lose_price\x18\x07 \x01(\x01\x12\x0b\n\x03pnl\x18\x08 \x01(\x01\x12\x12\n\ncommission\x18\t \x01(\x01\x12\x0e\n\x06reason\x18\n \x01(\t\"T\n\x14\x42\x61\x63ktestTradeSummary\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0c\n\x04wins\x18\x02 \x01(\x05\x12\x0e\n\x06losses\x18\x03 \x01(\x05\x12\x0f\n\x07net_pnl\x18\x04 \x01(\x01\x32}\n\x15\x42\x61\x63ktestTradesService\x12\x64\n\x15ListBacktestRunTrades\x12$.ant.v1.ListBacktestRunTradesRequest\x1a%.ant.v1.ListBacktestRunTradesResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backtest_trades_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LISTBACKTESTRUNTRADESREQUEST._serialized_start=33
  _LISTBACKTESTRUNTRADESREQUEST._serialized_end=79
  _LISTBACKTESTRUNTRADESRESPONSE._serialized_start=81
  _LISTBACKTESTRUNTRADESRESPONSE._serialized_end=198
  _BACKTESTTRADE._serialized_start=201
  _BACKTESTTRADE._serialized_end=387
  _BACKTESTTRADESUMMARY._serialized_start=389
  _BACKTESTTRADESUMMARY._serialized_end=473
  _BACKTESTTRADESSERVICE._serialized_start=475
  _BACKTESTTRADESSERVICE._serialized_end=600
# @@protoc_insertion_point(module_scope)
