# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backtest_run_control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import backtest_run_pb2 as backtest__run__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62\x61\x63ktest_run_control.proto\x12\x06\x61nt.v1\x1a\x12\x62\x61\x63ktest_run.proto\"*\n\x18\x43\x61ncelBacktestRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"=\n\x19\x43\x61ncelBacktestRunResponse\x12 \n\x03run\x18\x01 \x01(\x0b\x32\x13.ant.v1.BacktestRun\"*\n\x18\x44\x65leteBacktestRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\",\n\x19\x44\x65leteBacktestRunResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backtest_run_control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _CANCELBACKTESTRUNREQUEST._serialized_start=58
  _CANCELBACKTESTRUNREQUEST._serialized_end=100
  _CANCELBACKTESTRUNRESPONSE._serialized_start=102
  _CANCELBACKTESTRUNRESPONSE._serialized_end=163
  _DELETEBACKTESTRUNREQUEST._serialized_start=165
  _DELETEBACKTESTRUNREQUEST._serialized_end=207
  _DELETEBACKTESTRUNRESPONSE._serialized_start=209
  _DELETEBACKTESTRUNRESPONSE._serialized_end=253
# @@protoc_insertion_point(module_scope)
