# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x61nt.v1\"\x86\x02\n\x0f\x42\x61\x63ktestMetrics\x12\x14\n\x0ctotal_return\x18\x01 \x01(\x01\x12\x15\n\rannual_return\x18\x02 \x01(\x01\x12\x14\n\x0cmax_drawdown\x18\x03 \x01(\x01\x12\x14\n\x0csharpe_ratio\x18\x04 \x01(\x01\x12\x10\n\x08win_rate\x18\x05 \x01(\x01\x12\x15\n\rprofit_factor\x18\x06 \x01(\x01\x12\x14\n\x0ctotal_trades\x18\x07 \x01(\x05\x12\x16\n\x0ewinning_trades\x18\x08 \x01(\x05\x12\x15\n\rlosing_trades\x18\t \x01(\x05\x12\x16\n\x0e\x61verage_profit\x18\n \x01(\x01\x12\x14\n\x0c\x61verage_loss\x18\x0b \x01(\x01\"d\n\x0c\x42\x61\x63ktestRisk\x12\r\n\x05score\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07reasons\x18\x03 \x03(\t\x12\x10\n\x08warnings\x18\x04 \x03(\t\x12\x13\n\x0bis_reliable\x18\x05 \x01(\x08\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _BACKTESTMETRICS._serialized_start=25
  _BACKTESTMETRICS._serialized_end=287
  _BACKTESTRISK._serialized_start=289
  _BACKTESTRISK._serialized_end=389
# @@protoc_insertion_point(module_scope)
