# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: economic_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65\x63onomic_data.proto\x12\x06\x61nt.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x80\x01\n!ListEconomicCalendarEventsRequest\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x12\n\nimportance\x18\x05 \x01(\t\x12\x0c\n\x04lang\x18\x06 \x01(\t\"S\n\"ListEconomicCalendarEventsResponse\x12-\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1d.ant.v1.EconomicCalendarEvent\"\xe3\x01\n\x15\x45\x63onomicCalendarEvent\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\r\n\x05\x65vent\x18\x04 \x01(\t\x12\x17\n\x0flocalized_event\x18\x05 \x01(\t\x12\x0e\n\x06impact\x18\x06 \x01(\t\x12\x0e\n\x06\x61\x63tual\x18\x07 \x01(\t\x12\x10\n\x08previous\x18\x08 \x01(\t\x12\x10\n\x08\x65stimate\x18\t \x01(\t\x12\x0c\n\x04unit\x18\n \x01(\t\x12\x10\n\x08\x63urrency\x18\x0b \x01(\t\x12\x11\n\ttimestamp\x18\x0c \x01(\x03\"O\n\x1eListEconomicIndicatorsResponse\x12-\n\nindicators\x18\x01 \x03(\x0b\x32\x19.ant.v1.EconomicIndicator\"\xc0\x01\n\x11\x45\x63onomicIndicator\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\tseries_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05units\x18\x04 \x01(\t\x12\x11\n\tfrequency\x18\x05 \x01(\t\x12\x13\n\x0blatest_date\x18\x06 \x01(\t\x12\x14\n\x0clatest_value\x18\x07 \x01(\x01\x12/\n\x07history\x18\x08 \x03(\x0b\x32\x1e.ant.v1.EconomicIndicatorPoint\"5\n\x16\x45\x63onomicIndicatorPoint\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x32\xe4\x01\n\x13\x45\x63onomicDataService\x12s\n\x1aListEconomicCalendarEvents\x12).ant.v1.ListEconomicCalendarEventsRequest\x1a*.ant.v1.ListEconomicCalendarEventsResponse\x12X\n\x16ListEconomicIndicators\x12\x16.google.protobuf.Empty\x1a&.ant.v1.ListEconomicIndicatorsResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'economic_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LISTECONOMICCALENDAREVENTSREQUEST._serialized_start=61
  _LISTECONOMICCALENDAREVENTSREQUEST._serialized_end=189
  _LISTECONOMICCALENDAREVENTSRESPONSE._serialized_start=191
  _LISTECONOMICCALENDAREVENTSRESPONSE._serialized_end=274
  _ECONOMICCALENDAREVENT._serialized_start=277
  _ECONOMICCALENDAREVENT._serialized_end=504
  _LISTECONOMICINDICATORSRESPONSE._serialized_start=506
  _LISTECONOMICINDICATORSRESPONSE._serialized_end=585
  _ECONOMICINDICATOR._serialized_start=588
  _ECONOMICINDICATOR._serialized_end=780
  _ECONOMICINDICATORPOINT._serialized_start=782
  _ECONOMICINDICATORPOINT._serialized_end=835
  _ECONOMICDATASERVICE._serialized_start=838
  _ECONOMICDATASERVICE._serialized_end=1066
# @@protoc_insertion_point(module_scope)
