# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indicator_catalog.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17indicator_catalog.proto\x12\x06\x61nt.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x80\x01\n\x18IndicatorCatalogResponse\x12\x30\n\nindicators\x18\x01 \x03(\x0b\x32\x1c.ant.v1.IndicatorCatalogItem\x12\x32\n\x0brisk_params\x18\x02 \x03(\x0b\x32\x1d.ant.v1.IndicatorCatalogParam\"\x84\x01\n\x14IndicatorCatalogItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x61ll_signature\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x31\n\nparam_keys\x18\x04 \x03(\x0b\x32\x1d.ant.v1.IndicatorCatalogParam\"\x81\x01\n\x15IndicatorCatalogParam\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x04 \x01(\x01\x12\x0b\n\x03min\x18\x05 \x01(\x01\x12\x0b\n\x03max\x18\x06 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t2j\n\x17IndicatorCatalogService\x12O\n\x13GetIndicatorCatalog\x12\x16.google.protobuf.Empty\x1a .ant.v1.IndicatorCatalogResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indicator_catalog_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _INDICATORCATALOGRESPONSE._serialized_start=65
  _INDICATORCATALOGRESPONSE._serialized_end=193
  _INDICATORCATALOGITEM._serialized_start=196
  _INDICATORCATALOGITEM._serialized_end=328
  _INDICATORCATALOGPARAM._serialized_start=331
  _INDICATORCATALOGPARAM._serialized_end=460
  _INDICATORCATALOGSERVICE._serialized_start=462
  _INDICATORCATALOGSERVICE._serialized_end=568
# @@protoc_insertion_point(module_scope)
