# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tjob.proto\x12\x06\x61nt.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x03\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08progress\x18\x05 \x01(\x01\x12\r\n\x05stage\x18\x06 \x01(\t\x12\x17\n\x0frequest_summary\x18\x07 \x01(\t\x12\x12\n\nresult_ref\x18\x08 \x01(\t\x12\x16\n\x0eresult_summary\x18\t \x01(\t\x12\x12\n\nerror_code\x18\n \x01(\t\x12\x15\n\rerror_message\x18\x0b \x01(\t\x12\x17\n\x0fidempotency_key\x18\x0c \x01(\t\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nstarted_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x66inished_at\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\x10 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xd1\x01\n\x08JobEvent\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08progress\x18\x05 \x01(\x01\x12\r\n\x05stage\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\x12(\n\x07payload\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1f\n\rGetJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\"\n\x10\x43\x61ncelJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"8\n\x13SubscribeJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x11\n\tafter_seq\x18\x02 \x01(\x03\x32\xaf\x01\n\nJobService\x12,\n\x06GetJob\x12\x15.ant.v1.GetJobRequest\x1a\x0b.ant.v1.Job\x12\x32\n\tCancelJob\x12\x18.ant.v1.CancelJobRequest\x1a\x0b.ant.v1.Job\x12?\n\x0cSubscribeJob\x12\x1b.ant.v1.SubscribeJobRequest\x1a\x10.ant.v1.JobEvent0\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _JOB._serialized_start=85
  _JOB._serialized_end=512
  _JOBEVENT._serialized_start=515
  _JOBEVENT._serialized_end=724
  _GETJOBREQUEST._serialized_start=726
  _GETJOBREQUEST._serialized_end=757
  _CANCELJOBREQUEST._serialized_start=759
  _CANCELJOBREQUEST._serialized_end=793
  _SUBSCRIBEJOBREQUEST._serialized_start=795
  _SUBSCRIBEJOBREQUEST._serialized_end=851
  _JOBSERVICE._serialized_start=854
  _JOBSERVICE._serialized_end=1029
# @@protoc_insertion_point(module_scope)
