# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_schedule.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12log_schedule.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n\x19GetScheduleRunLogsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x13\n\x0bschedule_id\x18\x03 \x01(\t\"Q\n\x1aGetScheduleRunLogsResponse\x12$\n\x04logs\x18\x01 \x03(\x0b\x32\x16.ant.v1.ScheduleRunLog\x12\r\n\x05total\x18\x02 \x01(\x05\"\xd2\x01\n\x0eScheduleRunLog\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x03\x12\x15\n\rerror_message\x18\x06 \x01(\t\x12\x13\n\x0bsignal_type\x18\x07 \x01(\t\x12\x15\n\rsignal_volume\x18\x08 \x01(\x01\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_schedule_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _GETSCHEDULERUNLOGSREQUEST._serialized_start=63
  _GETSCHEDULERUNLOGSREQUEST._serialized_end=144
  _GETSCHEDULERUNLOGSRESPONSE._serialized_start=146
  _GETSCHEDULERUNLOGSRESPONSE._serialized_end=227
  _SCHEDULERUNLOG._serialized_start=230
  _SCHEDULERUNLOG._serialized_end=440
# @@protoc_insertion_point(module_scope)
