# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14log_connection.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n\x18GetConnectionLogsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\"O\n\x19GetConnectionLogsResponse\x12#\n\x04logs\x18\x01 \x03(\x0b\x32\x15.ant.v1.ConnectionLog\x12\r\n\x05total\x18\x02 \x01(\x05\"\x8b\x02\n\rConnectionLog\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x14\n\x0c\x65rror_detail\x18\x06 \x01(\t\x12\x13\n\x0bserver_host\x18\x07 \x01(\t\x12\x13\n\x0bserver_port\x18\x08 \x01(\x05\x12\x10\n\x08login_id\x18\t \x01(\x03\x12#\n\x1b\x63onnection_duration_seconds\x18\n \x01(\x03\x12.\n\ncreated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.TimestampB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _GETCONNECTIONLOGSREQUEST._serialized_start=66
  _GETCONNECTIONLOGSREQUEST._serialized_end=199
  _GETCONNECTIONLOGSRESPONSE._serialized_start=201
  _GETCONNECTIONLOGSRESPONSE._serialized_end=280
  _CONNECTIONLOG._serialized_start=283
  _CONNECTIONLOG._serialized_end=550
# @@protoc_insertion_point(module_scope)
