# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_execution.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13log_execution.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n\x17GetExecutionLogsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x13\n\x0bschedule_id\x18\x08 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\"M\n\x18GetExecutionLogsResponse\x12\"\n\x04logs\x18\x01 \x03(\x0b\x32\x14.ant.v1.ExecutionLog\x12\r\n\x05total\x18\x02 \x01(\x05\"\xac\x03\n\x0c\x45xecutionLog\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x13\n\x0bschedule_id\x18\x12 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x11\n\ttimeframe\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0bsignal_type\x18\x06 \x01(\t\x12\x14\n\x0csignal_price\x18\x07 \x01(\x01\x12\x15\n\rsignal_volume\x18\x08 \x01(\x01\x12\x18\n\x10signal_stop_loss\x18\t \x01(\x01\x12\x1a\n\x12signal_take_profit\x18\n \x01(\x01\x12\x19\n\x11\x65xecuted_order_id\x18\x0b \x01(\t\x12\x16\n\x0e\x65xecuted_price\x18\x0c \x01(\x01\x12\x17\n\x0f\x65xecuted_volume\x18\r \x01(\x01\x12\x0e\n\x06profit\x18\x0e \x01(\x01\x12\x15\n\rerror_message\x18\x0f \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x10 \x01(\x03\x12.\n\ncreated_at\x18\x11 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_execution_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _GETEXECUTIONLOGSREQUEST._serialized_start=65
  _GETEXECUTIONLOGSREQUEST._serialized_end=234
  _GETEXECUTIONLOGSRESPONSE._serialized_start=236
  _GETEXECUTIONLOGSRESPONSE._serialized_end=313
  _EXECUTIONLOG._serialized_start=316
  _EXECUTIONLOG._serialized_end=744
# @@protoc_insertion_point(module_scope)
