# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flog_order.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n\x19GetOrderLogHistoryRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\x12\x13\n\x0bschedule_id\x18\x07 \x01(\t\"W\n\x1aGetOrderLogHistoryResponse\x12*\n\x06orders\x18\x01 \x03(\x0b\x32\x1a.ant.v1.OrderHistoryRecord\x12\r\n\x05total\x18\x02 \x01(\x05\"\xa3\x02\n\x12OrderHistoryRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x13\n\x0bschedule_id\x18\x0c \x01(\t\x12\x0e\n\x06ticket\x18\x03 \x01(\x03\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x12\n\norder_type\x18\x05 \x01(\t\x12\x0c\n\x04lots\x18\x06 \x01(\x01\x12\x12\n\nopen_price\x18\x07 \x01(\x01\x12\x13\n\x0b\x63lose_price\x18\x08 \x01(\x01\x12\x0e\n\x06profit\x18\t \x01(\x01\x12-\n\topen_time\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nclose_time\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.TimestampB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _GETORDERLOGHISTORYREQUEST._serialized_start=61
  _GETORDERLOGHISTORYREQUEST._serialized_end=216
  _GETORDERLOGHISTORYRESPONSE._serialized_start=218
  _GETORDERLOGHISTORYRESPONSE._serialized_end=305
  _ORDERHISTORYRECORD._serialized_start=308
  _ORDERHISTORYRECORD._serialized_end=599
# @@protoc_insertion_point(module_scope)
