# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import log_connection_pb2 as log__connection__pb2
import log_execution_pb2 as log__execution__pb2
import log_order_pb2 as log__order__pb2
import log_operation_pb2 as log__operation__pb2
import log_schedule_pb2 as log__schedule__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x06\x61nt.v1\x1a\x14log_connection.proto\x1a\x13log_execution.proto\x1a\x0flog_order.proto\x1a\x13log_operation.proto\x1a\x12log_schedule.proto2\xce\x03\n\nLogService\x12X\n\x11GetConnectionLogs\x12 .ant.v1.GetConnectionLogsRequest\x1a!.ant.v1.GetConnectionLogsResponse\x12U\n\x10GetExecutionLogs\x12\x1f.ant.v1.GetExecutionLogsRequest\x1a .ant.v1.GetExecutionLogsResponse\x12[\n\x12GetOrderLogHistory\x12!.ant.v1.GetOrderLogHistoryRequest\x1a\".ant.v1.GetOrderLogHistoryResponse\x12U\n\x10GetOperationLogs\x12\x1f.ant.v1.GetOperationLogsRequest\x1a .ant.v1.GetOperationLogsResponse\x12[\n\x12GetScheduleRunLogs\x12!.ant.v1.GetScheduleRunLogsRequest\x1a\".ant.v1.GetScheduleRunLogsResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LOGSERVICE._serialized_start=123
  _LOGSERVICE._serialized_end=585
# @@protoc_insertion_point(module_scope)
