# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_regime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13market_regime.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n\x19\x44\x65tectMarketRegimeRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimeframe\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x12(\n\x04\x66rom\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"B\n\x1a\x44\x65tectMarketRegimeResponse\x12$\n\x06regime\x18\x01 \x01(\x0b\x32\x14.ant.v1.MarketRegime\"+\n\x16GetMarketRegimeRequest\x12\x11\n\tregime_id\x18\x01 \x01(\t\"?\n\x17GetMarketRegimeResponse\x12$\n\x06regime\x18\x01 \x01(\x0b\x32\x14.ant.v1.MarketRegime\"\xe8\x02\n\x0cMarketRegime\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x11\n\ttimeframe\x18\x05 \x01(\t\x12\x0e\n\x06regime\x18\x06 \x01(\t\x12\x12\n\nconfidence\x18\x07 \x01(\x01\x12\x10\n\x08\x66\x65\x61tures\x18\x08 \x01(\t\x12\x10\n\x08segments\x18\t \x01(\t\x12\x19\n\x11strategy_families\x18\n \x03(\t\x12-\n\tfrom_time\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07to_time\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rmodel_version\x18\r \x01(\t\x12.\n\ncreated_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xc6\x01\n\x13MarketRegimeService\x12[\n\x12\x44\x65tectMarketRegime\x12!.ant.v1.DetectMarketRegimeRequest\x1a\".ant.v1.DetectMarketRegimeResponse\x12R\n\x0fGetMarketRegime\x12\x1e.ant.v1.GetMarketRegimeRequest\x1a\x1f.ant.v1.GetMarketRegimeResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_regime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _DETECTMARKETREGIMEREQUEST._serialized_start=65
  _DETECTMARKETREGIMEREQUEST._serialized_end=244
  _DETECTMARKETREGIMERESPONSE._serialized_start=246
  _DETECTMARKETREGIMERESPONSE._serialized_end=312
  _GETMARKETREGIMEREQUEST._serialized_start=314
  _GETMARKETREGIMEREQUEST._serialized_end=357
  _GETMARKETREGIMERESPONSE._serialized_start=359
  _GETMARKETREGIMERESPONSE._serialized_end=422
  _MARKETREGIME._serialized_start=425
  _MARKETREGIME._serialized_end=785
  _MARKETREGIMESERVICE._serialized_start=788
  _MARKETREGIMESERVICE._serialized_end=986
# @@protoc_insertion_point(module_scope)
