# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import mthub_service_pb2 as mthub__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14market_service.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13mthub_service.proto\"\xa6\x01\n\x10GetKlinesRequest\x12\x11\n\tcanonical\x18\x01 \x01(\t\x12\x0e\n\x06\x62roker\x18\x02 \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\t\x12(\n\x04\x66rom\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05limit\x18\x06 \x01(\x05\"0\n\x11GetKlinesResponse\x12\x1b\n\x04\x62\x61rs\x18\x01 \x03(\x0b\x32\r.ant.v1.OHLCV\":\n\x15GetSymbolStatsRequest\x12\x11\n\tcanonical\x18\x01 \x01(\t\x12\x0e\n\x06\x62roker\x18\x02 \x01(\t\"\x80\x01\n\x16GetSymbolStatsResponse\x12\x13\n\x0b\x63urrent_bid\x18\x01 \x01(\t\x12\x13\n\x0b\x63urrent_ask\x18\x02 \x01(\t\x12\x16\n\x0e\x63hange_24h_pct\x18\x03 \x01(\t\x12\x0e\n\x06spread\x18\x04 \x01(\t\x12\x14\n\x0ctick_rate_1m\x18\x05 \x01(\x04\"8\n\x12StreamTicksRequest\x12\x12\n\ncanonicals\x18\x01 \x03(\t\x12\x0e\n\x06\x62roker\x18\x02 \x01(\t\"Z\n\x07TickMsg\x12\x11\n\tcanonical\x18\x01 \x01(\t\x12\x0e\n\x06\x62roker\x18\x02 \x01(\t\x12\x12\n\nts_unix_ms\x18\x03 \x01(\x03\x12\x0b\n\x03\x62id\x18\x04 \x01(\t\x12\x0b\n\x03\x61sk\x18\x05 \x01(\t2\xe0\x01\n\rMarketService\x12@\n\tGetKlines\x12\x18.ant.v1.GetKlinesRequest\x1a\x19.ant.v1.GetKlinesResponse\x12O\n\x0eGetSymbolStats\x12\x1d.ant.v1.GetSymbolStatsRequest\x1a\x1e.ant.v1.GetSymbolStatsResponse\x12<\n\x0bStreamTicks\x12\x1a.ant.v1.StreamTicksRequest\x1a\x0f.ant.v1.TickMsg0\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _GETKLINESREQUEST._serialized_start=87
  _GETKLINESREQUEST._serialized_end=253
  _GETKLINESRESPONSE._serialized_start=255
  _GETKLINESRESPONSE._serialized_end=303
  _GETSYMBOLSTATSREQUEST._serialized_start=305
  _GETSYMBOLSTATSREQUEST._serialized_end=363
  _GETSYMBOLSTATSRESPONSE._serialized_start=366
  _GETSYMBOLSTATSRESPONSE._serialized_end=494
  _STREAMTICKSREQUEST._serialized_start=496
  _STREAMTICKSREQUEST._serialized_end=552
  _TICKMSG._serialized_start=554
  _TICKMSG._serialized_end=644
  _MARKETSERVICE._serialized_start=647
  _MARKETSERVICE._serialized_end=871
# @@protoc_insertion_point(module_scope)
