# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anotification_service.proto\x12\x06\x61nt.v1\"\x91\x01\n\x0cNotification\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x11\n\tdata_json\x18\x06 \x01(\t\x12\x0f\n\x07is_read\x18\x07 \x01(\x08\x12\x12\n\ncreated_at\x18\x08 \x01(\t\"N\n\x18ListNotificationsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x13\n\x0bunread_only\x18\x03 \x01(\x08\"^\n\x19ListNotificationsResponse\x12+\n\rnotifications\x18\x01 \x03(\x0b\x32\x14.ant.v1.Notification\x12\x14\n\x0ctotal_unread\x18\x02 \x01(\x05\"\x1d\n\x0fMarkReadRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x12\n\x10MarkReadResponse\"\x14\n\x12MarkAllReadRequest\"\x15\n\x13MarkAllReadResponse2\xf6\x01\n\x13NotificationService\x12X\n\x11ListNotifications\x12 .ant.v1.ListNotificationsRequest\x1a!.ant.v1.ListNotificationsResponse\x12=\n\x08MarkRead\x12\x17.ant.v1.MarkReadRequest\x1a\x18.ant.v1.MarkReadResponse\x12\x46\n\x0bMarkAllRead\x12\x1a.ant.v1.MarkAllReadRequest\x1a\x1b.ant.v1.MarkAllReadResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _NOTIFICATION._serialized_start=39
  _NOTIFICATION._serialized_end=184
  _LISTNOTIFICATIONSREQUEST._serialized_start=186
  _LISTNOTIFICATIONSREQUEST._serialized_end=264
  _LISTNOTIFICATIONSRESPONSE._serialized_start=266
  _LISTNOTIFICATIONSRESPONSE._serialized_end=360
  _MARKREADREQUEST._serialized_start=362
  _MARKREADREQUEST._serialized_end=391
  _MARKREADRESPONSE._serialized_start=393
  _MARKREADRESPONSE._serialized_end=411
  _MARKALLREADREQUEST._serialized_start=413
  _MARKALLREADREQUEST._serialized_end=433
  _MARKALLREADRESPONSE._serialized_start=435
  _MARKALLREADRESPONSE._serialized_end=456
  _NOTIFICATIONSERVICE._serialized_start=459
  _NOTIFICATIONSERVICE._serialized_end=705
# @@protoc_insertion_point(module_scope)
