# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objective_score.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15objective_score.proto\x12\x06\x61nt.v1\"\x97\x01\n\x0eObjectiveKline\x12\x11\n\topen_time\x18\x01 \x01(\t\x12\x12\n\nclose_time\x18\x02 \x01(\t\x12\x12\n\nopen_price\x18\x03 \x01(\x01\x12\x12\n\nhigh_price\x18\x04 \x01(\x01\x12\x11\n\tlow_price\x18\x05 \x01(\x01\x12\x13\n\x0b\x63lose_price\x18\x06 \x01(\x01\x12\x0e\n\x06volume\x18\x07 \x01(\x01\"b\n\x15ObjectiveScoreRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12&\n\x06klines\x18\x03 \x03(\x0b\x32\x16.ant.v1.ObjectiveKline\"\x85\x01\n\x16ObjectiveScoreResponse\x12\x10\n\x08\x64\x65\x63ision\x18\x01 \x01(\t\x12\x15\n\roverall_score\x18\x02 \x01(\x01\x12\x17\n\x0ftechnical_score\x18\x03 \x01(\x01\x12)\n\x07signals\x18\x04 \x01(\x0b\x32\x18.ant.v1.ObjectiveSignals\"r\n\x10ObjectiveSignals\x12\x1e\n\x03rsi\x18\x01 \x01(\x0b\x32\x11.ant.v1.RSISignal\x12 \n\x04macd\x18\x02 \x01(\x0b\x32\x12.ant.v1.MACDSignal\x12\x1c\n\x02ma\x18\x03 \x01(\x0b\x32\x10.ant.v1.MASignal\"*\n\tRSISignal\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0e\n\x06signal\x18\x02 \x01(\t\"b\n\nMACDSignal\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x13\n\x0bsignal_line\x18\x02 \x01(\x01\x12\x11\n\thistogram\x18\x03 \x01(\x01\x12\x0e\n\x06signal\x18\x04 \x01(\t\x12\r\n\x05trend\x18\x05 \x01(\t\"B\n\x08MASignal\x12\x0b\n\x03ma5\x18\x01 \x01(\x01\x12\x0c\n\x04ma10\x18\x02 \x01(\x01\x12\x0c\n\x04ma20\x18\x03 \x01(\x01\x12\r\n\x05trend\x18\x04 \x01(\t2q\n\x15ObjectiveScoreService\x12X\n\x17\x43\x61lculateObjectiveScore\x12\x1d.ant.v1.ObjectiveScoreRequest\x1a\x1e.ant.v1.ObjectiveScoreResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objective_score_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _OBJECTIVEKLINE._serialized_start=34
  _OBJECTIVEKLINE._serialized_end=185
  _OBJECTIVESCOREREQUEST._serialized_start=187
  _OBJECTIVESCOREREQUEST._serialized_end=285
  _OBJECTIVESCORERESPONSE._serialized_start=288
  _OBJECTIVESCORERESPONSE._serialized_end=421
  _OBJECTIVESIGNALS._serialized_start=423
  _OBJECTIVESIGNALS._serialized_end=537
  _RSISIGNAL._serialized_start=539
  _RSISIGNAL._serialized_end=581
  _MACDSIGNAL._serialized_start=583
  _MACDSIGNAL._serialized_end=681
  _MASIGNAL._serialized_start=683
  _MASIGNAL._serialized_end=749
  _OBJECTIVESCORESERVICE._serialized_start=751
  _OBJECTIVESCORESERVICE._serialized_end=864
# @@protoc_insertion_point(module_scope)
