# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: risk_gate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frisk_gate.proto\x12\x06\x61nt.v1\"\xfc\x01\n\x0bOrderIntent\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0c\n\x04side\x18\x04 \x01(\t\x12\x0e\n\x06volume\x18\x05 \x01(\t\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\t\x12\n\n\x02sl\x18\x08 \x01(\t\x12\n\n\x02tp\x18\t \x01(\t\x12\r\n\x05magic\x18\n \x01(\x03\x12)\n\x06source\x18\x0b \x01(\x0e\x32\x19.ant.v1.OrderIntentSource\x12\x0f\n\x07\x63omment\x18\x0c \x01(\t\x12\x1a\n\x12\x63reated_at_unix_ms\x18\r \x01(\x03\"q\n\x0cRiskDecision\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x1c\n\x0f\x61\x64justed_volume\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08rule_hit\x18\x04 \x01(\tB\x12\n\x10_adjusted_volume\"~\n\x11OrderIntentResult\x12#\n\x06intent\x18\x01 \x01(\x0b\x32\x13.ant.v1.OrderIntent\x12&\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0b\x32\x14.ant.v1.RiskDecision\x12\x1c\n\x14\x65valuated_at_unix_ms\x18\x03 \x01(\x03*s\n\x11OrderIntentSource\x12#\n\x1fORDER_INTENT_SOURCE_UNSPECIFIED\x10\x00\x12\x1b\n\x17ORDER_INTENT_SOURCE_SIM\x10\x01\x12\x1c\n\x18ORDER_INTENT_SOURCE_LIVE\x10\x02\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'risk_gate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _ORDERINTENTSOURCE._serialized_start=525
  _ORDERINTENTSOURCE._serialized_end=640
  _ORDERINTENT._serialized_start=28
  _ORDERINTENT._serialized_end=280
  _RISKDECISION._serialized_start=282
  _RISKDECISION._serialized_end=395
  _ORDERINTENTRESULT._serialized_start=397
  _ORDERINTENTRESULT._serialized_end=523
# @@protoc_insertion_point(module_scope)
