# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bshare.proto\x12\x06\x61nt.v1\"W\n\x17\x43reateShareTokenRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0b\x65xpire_days\x18\x03 \x01(\x05\"P\n\x18\x43reateShareTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tshare_url\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\t\",\n\x1bGetSharedPerformanceRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\xfd\x01\n\x1cGetSharedPerformanceResponse\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_info\x18\x02 \x01(\t\x12\x14\n\x0ctotal_return\x18\x03 \x01(\x01\x12\x10\n\x08win_rate\x18\x04 \x01(\x01\x12\x14\n\x0cmax_drawdown\x18\x05 \x01(\x01\x12\x14\n\x0csharpe_ratio\x18\x06 \x01(\x01\x12\x14\n\x0ctotal_trades\x18\x07 \x01(\x05\x12\x14\n\x0c\x65quity_curve\x18\x08 \x03(\x01\x12#\n\x06trades\x18\t \x03(\x0b\x32\x13.ant.v1.SharedTrade\x12\x0f\n\x07\x65xpired\x18\n \x01(\x08\"b\n\x0bSharedTrade\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\x0e\n\x06profit\x18\x04 \x01(\x01\x12\x15\n\rclose_time_ms\x18\x05 \x01(\x03\x32\xc8\x01\n\x0cShareService\x12U\n\x10\x43reateShareToken\x12\x1f.ant.v1.CreateShareTokenRequest\x1a .ant.v1.CreateShareTokenResponse\x12\x61\n\x14GetSharedPerformance\x12#.ant.v1.GetSharedPerformanceRequest\x1a$.ant.v1.GetSharedPerformanceResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'share_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _CREATESHARETOKENREQUEST._serialized_start=23
  _CREATESHARETOKENREQUEST._serialized_end=110
  _CREATESHARETOKENRESPONSE._serialized_start=112
  _CREATESHARETOKENRESPONSE._serialized_end=192
  _GETSHAREDPERFORMANCEREQUEST._serialized_start=194
  _GETSHAREDPERFORMANCEREQUEST._serialized_end=238
  _GETSHAREDPERFORMANCERESPONSE._serialized_start=241
  _GETSHAREDPERFORMANCERESPONSE._serialized_end=494
  _SHAREDTRADE._serialized_start=496
  _SHAREDTRADE._serialized_end=594
  _SHARESERVICE._serialized_start=597
  _SHARESERVICE._serialized_end=797
# @@protoc_insertion_point(module_scope)
