# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy_template_requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import strategy_template_entity_pb2 as strategy__template__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n strategy_template_requests.proto\x12\x06\x61nt.v1\x1a\x1estrategy_template_entity.proto\"\x16\n\x14ListTemplatesRequest\"D\n\x15ListTemplatesResponse\x12+\n\ttemplates\x18\x01 \x03(\x0b\x32\x18.ant.v1.StrategyTemplate\" \n\x12GetTemplateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x98\x01\n\x15\x43reateTemplateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12-\n\nparameters\x18\x04 \x03(\x0b\x32\x19.ant.v1.TemplateParameter\x12\x11\n\tis_public\x18\x05 \x01(\x08\x12\x0c\n\x04tags\x18\x06 \x03(\t\"*\n\x1a\x43reateTemplateDraftRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xc7\x01\n\x1aUpdateTemplateDraftRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04\x63ode\x18\x04 \x01(\tH\x02\x88\x01\x01\x12-\n\nparameters\x18\x05 \x03(\x0b\x32\x19.ant.v1.TemplateParameter\x12\x0c\n\x04tags\x18\x06 \x03(\tB\x07\n\x05_nameB\x0e\n\x0c_descriptionB\x07\n\x05_code\")\n\x1bPublishTemplateDraftRequest\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x1a\x43\x61ncelTemplateDraftRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\xe8\x01\n\x15UpdateTemplateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04\x63ode\x18\x04 \x01(\tH\x02\x88\x01\x01\x12-\n\nparameters\x18\x05 \x03(\x0b\x32\x19.ant.v1.TemplateParameter\x12\x16\n\tis_public\x18\x06 \x01(\x08H\x03\x88\x01\x01\x12\x0c\n\x04tags\x18\x07 \x03(\tB\x07\n\x05_nameB\x0e\n\x0c_descriptionB\x07\n\x05_codeB\x0c\n\n_is_public\"#\n\x15\x44\x65leteTemplateRequest\x12\n\n\x02id\x18\x01 \x01(\tB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_template_requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LISTTEMPLATESREQUEST._serialized_start=76
  _LISTTEMPLATESREQUEST._serialized_end=98
  _LISTTEMPLATESRESPONSE._serialized_start=100
  _LISTTEMPLATESRESPONSE._serialized_end=168
  _GETTEMPLATEREQUEST._serialized_start=170
  _GETTEMPLATEREQUEST._serialized_end=202
  _CREATETEMPLATEREQUEST._serialized_start=205
  _CREATETEMPLATEREQUEST._serialized_end=357
  _CREATETEMPLATEDRAFTREQUEST._serialized_start=359
  _CREATETEMPLATEDRAFTREQUEST._serialized_end=401
  _UPDATETEMPLATEDRAFTREQUEST._serialized_start=404
  _UPDATETEMPLATEDRAFTREQUEST._serialized_end=603
  _PUBLISHTEMPLATEDRAFTREQUEST._serialized_start=605
  _PUBLISHTEMPLATEDRAFTREQUEST._serialized_end=646
  _CANCELTEMPLATEDRAFTREQUEST._serialized_start=648
  _CANCELTEMPLATEDRAFTREQUEST._serialized_end=688
  _UPDATETEMPLATEREQUEST._serialized_start=691
  _UPDATETEMPLATEREQUEST._serialized_end=923
  _DELETETEMPLATEREQUEST._serialized_start=925
  _DELETETEMPLATEREQUEST._serialized_end=960
# @@protoc_insertion_point(module_scope)
