# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14strategy_state.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x03\n\rStrategyState\x12\x15\n\rstrategy_name\x18\x01 \x01(\t\x12\x18\n\x10strategy_version\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x12\n\naccount_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x0f\n\x07symbols\x18\x06 \x03(\t\x12\x39\n\nparameters\x18\x07 \x03(\x0b\x32%.ant.v1.StrategyState.ParametersEntry\x12(\n\tpositions\x18\x08 \x03(\x0b\x32\x15.ant.v1.StatePosition\x12%\n\x07metrics\x18\t \x01(\x0b\x32\x14.ant.v1.StateMetrics\x12\x14\n\x0c\x63ustom_state\x18\n \x01(\x0c\x12\x32\n\x0esnapshotted_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0eschema_version\x18\x0c \x01(\x05\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"m\n\rStatePosition\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\x13\n\x0b\x65ntry_price\x18\x04 \x01(\x01\x12\x19\n\x11open_time_unix_ms\x18\x05 \x01(\x03\"\x9a\x01\n\x0cStateMetrics\x12\x14\n\x0ctotal_trades\x18\x01 \x01(\x05\x12\x10\n\x08win_rate\x18\x02 \x01(\x01\x12\x14\n\x0csharpe_ratio\x18\x03 \x01(\x01\x12\x0f\n\x07net_pnl\x18\x04 \x01(\x01\x12\x11\n\tgross_pnl\x18\x05 \x01(\x01\x12\x14\n\x0cmax_drawdown\x18\x06 \x01(\x01\x12\x12\n\ntotal_cost\x18\x07 \x01(\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _STRATEGYSTATE_PARAMETERSENTRY._options = None
  _STRATEGYSTATE_PARAMETERSENTRY._serialized_options = b'8\001'
  _STRATEGYSTATE._serialized_start=66
  _STRATEGYSTATE._serialized_end=494
  _STRATEGYSTATE_PARAMETERSENTRY._serialized_start=445
  _STRATEGYSTATE_PARAMETERSENTRY._serialized_end=494
  _STATEPOSITION._serialized_start=496
  _STATEPOSITION._serialized_end=605
  _STATEMETRICS._serialized_start=608
  _STATEMETRICS._serialized_end=762
# @@protoc_insertion_point(module_scope)
