# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy_schedule_control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import strategy_schedule_entity_pb2 as strategy__schedule__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fstrategy_schedule_control.proto\x12\x06\x61nt.v1\x1a\x1estrategy_schedule_entity.proto\"\xaf\x02\n\x15\x43reateScheduleRequest\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x11\n\ttimeframe\x18\x05 \x01(\t\x12\x41\n\nparameters\x18\x06 \x03(\x0b\x32-.ant.v1.CreateScheduleRequest.ParametersEntry\x12\x15\n\rschedule_type\x18\x07 \x01(\t\x12/\n\x0fschedule_config\x18\x08 \x01(\x0b\x32\x16.ant.v1.ScheduleConfig\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xda\x02\n\x15UpdateScheduleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06symbol\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x16\n\ttimeframe\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x41\n\nparameters\x18\x05 \x03(\x0b\x32-.ant.v1.UpdateScheduleRequest.ParametersEntry\x12\x1a\n\rschedule_type\x18\x06 \x01(\tH\x03\x88\x01\x01\x12/\n\x0fschedule_config\x18\x07 \x01(\x0b\x32\x16.ant.v1.ScheduleConfig\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x07\n\x05_nameB\t\n\x07_symbolB\x0c\n\n_timeframeB\x10\n\x0e_schedule_type\"#\n\x15\x44\x65leteScheduleRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x15ToggleScheduleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_schedule_control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _CREATESCHEDULEREQUEST_PARAMETERSENTRY._options = None
  _CREATESCHEDULEREQUEST_PARAMETERSENTRY._serialized_options = b'8\001'
  _UPDATESCHEDULEREQUEST_PARAMETERSENTRY._options = None
  _UPDATESCHEDULEREQUEST_PARAMETERSENTRY._serialized_options = b'8\001'
  _CREATESCHEDULEREQUEST._serialized_start=76
  _CREATESCHEDULEREQUEST._serialized_end=379
  _CREATESCHEDULEREQUEST_PARAMETERSENTRY._serialized_start=330
  _CREATESCHEDULEREQUEST_PARAMETERSENTRY._serialized_end=379
  _UPDATESCHEDULEREQUEST._serialized_start=382
  _UPDATESCHEDULEREQUEST._serialized_end=728
  _UPDATESCHEDULEREQUEST_PARAMETERSENTRY._serialized_start=330
  _UPDATESCHEDULEREQUEST_PARAMETERSENTRY._serialized_end=379
  _DELETESCHEDULEREQUEST._serialized_start=730
  _DELETESCHEDULEREQUEST._serialized_end=765
  _TOGGLESCHEDULEREQUEST._serialized_start=767
  _TOGGLESCHEDULEREQUEST._serialized_end=818
# @@protoc_insertion_point(module_scope)
