# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy_schedule_requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import strategy_schedule_query_pb2 as strategy__schedule__query__pb2
import strategy_schedule_control_pb2 as strategy__schedule__control__pb2
import strategy_schedule_backtest_pb2 as strategy__schedule__backtest__pb2

from strategy_schedule_query_pb2 import *
from strategy_schedule_control_pb2 import *
from strategy_schedule_backtest_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n strategy_schedule_requests.proto\x12\x06\x61nt.v1\x1a\x1dstrategy_schedule_query.proto\x1a\x1fstrategy_schedule_control.proto\x1a strategy_schedule_backtest.protoB\"Z anttrader/gen/proto/ant/v1;antv1P\x00P\x01P\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_schedule_requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
# @@protoc_insertion_point(module_scope)
