# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy_schedule_backtest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n strategy_schedule_backtest.proto\x12\x06\x61nt.v1\x1a\x0c\x63ommon.proto\"\x94\x02\n\x12RunBacktestRequest\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x11\n\ttimeframe\x18\x04 \x01(\t\x12>\n\nparameters\x18\x05 \x03(\x0b\x32*.ant.v1.RunBacktestRequest.ParametersEntry\x12\x17\n\x0finitial_capital\x18\x06 \x01(\x01\x12\x17\n\ndataset_id\x18\x07 \x01(\tH\x00\x88\x01\x01\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\r\n\x0b_dataset_id\"\xf1\x01\n\x13RunBacktestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12(\n\x07metrics\x18\x02 \x01(\x0b\x32\x17.ant.v1.BacktestMetrics\x12\x12\n\nrisk_score\x18\x03 \x01(\x05\x12\x12\n\nrisk_level\x18\x04 \x01(\t\x12\x14\n\x0crisk_reasons\x18\x05 \x03(\t\x12\x15\n\rrisk_warnings\x18\x06 \x03(\t\x12\x13\n\x0bis_reliable\x18\x07 \x01(\x08\x12\r\n\x05\x65rror\x18\x08 \x01(\t\x12\x17\n\ndataset_id\x18\t \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_dataset_idB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_schedule_backtest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _RUNBACKTESTREQUEST_PARAMETERSENTRY._options = None
  _RUNBACKTESTREQUEST_PARAMETERSENTRY._serialized_options = b'8\001'
  _RUNBACKTESTREQUEST._serialized_start=59
  _RUNBACKTESTREQUEST._serialized_end=335
  _RUNBACKTESTREQUEST_PARAMETERSENTRY._serialized_start=271
  _RUNBACKTESTREQUEST_PARAMETERSENTRY._serialized_end=320
  _RUNBACKTESTRESPONSE._serialized_start=338
  _RUNBACKTESTRESPONSE._serialized_end=579
# @@protoc_insertion_point(module_scope)
