# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy_schedule_query.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import strategy_schedule_entity_pb2 as strategy__schedule__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstrategy_schedule_query.proto\x12\x06\x61nt.v1\x1a\x1estrategy_schedule_entity.proto\"\x16\n\x14ListSchedulesRequest\"D\n\x15ListSchedulesResponse\x12+\n\tschedules\x18\x01 \x03(\x0b\x32\x18.ant.v1.StrategySchedule\" \n\x12GetScheduleRequest\x12\n\n\x02id\x18\x01 \x01(\tB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_schedule_query_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LISTSCHEDULESREQUEST._serialized_start=73
  _LISTSCHEDULESREQUEST._serialized_end=95
  _LISTSCHEDULESRESPONSE._serialized_start=97
  _LISTSCHEDULESRESPONSE._serialized_end=165
  _GETSCHEDULEREQUEST._serialized_start=167
  _GETSCHEDULEREQUEST._serialized_end=199
# @@protoc_insertion_point(module_scope)
