# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream_event_sync.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stream_event_sync.proto\x12\x06\x61nt.v1\"e\n\tSyncEvent\x12\x0f\n\x07sync_id\x18\x01 \x01(\t\x12 \n\x05phase\x18\x02 \x01(\x0e\x32\x11.ant.v1.SyncPhase\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x15\n\rlast_event_id\x18\x04 \x01(\t*Y\n\tSyncPhase\x12\x1a\n\x16SYNC_PHASE_UNSPECIFIED\x10\x00\x12\x16\n\x12SYNC_PHASE_STARTED\x10\x01\x12\x18\n\x14SYNC_PHASE_COMPLETED\x10\x02\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_event_sync_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _SYNCPHASE._serialized_start=138
  _SYNCPHASE._serialized_end=227
  _SYNCEVENT._serialized_start=35
  _SYNCEVENT._serialized_end=136
# @@protoc_insertion_point(module_scope)
