# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream_event_indicator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstream_event_indicator.proto\x12\x06\x61nt.v1\"!\n\x0fIndicatorSeries\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x82\x02\n\x14IndicatorUpdateEvent\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x14\n\x0cindicator_id\x18\x03 \x01(\t\x12\x0e\n\x06values\x18\x04 \x03(\x01\x12\x38\n\x06series\x18\x05 \x03(\x0b\x32(.ant.v1.IndicatorUpdateEvent.SeriesEntry\x12\x0c\n\x04pane\x18\x06 \x01(\t\x12\x11\n\tbar_count\x18\x07 \x01(\x05\x1a\x46\n\x0bSeriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.ant.v1.IndicatorSeries:\x02\x38\x01\"\xc5\x01\n\x1aSubscribeIndicatorsRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x15\n\rindicator_ids\x18\x03 \x03(\t\x12>\n\x06params\x18\x04 \x03(\x0b\x32..ant.v1.SubscribeIndicatorsRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_event_indicator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _INDICATORUPDATEEVENT_SERIESENTRY._options = None
  _INDICATORUPDATEEVENT_SERIESENTRY._serialized_options = b'8\001'
  _SUBSCRIBEINDICATORSREQUEST_PARAMSENTRY._options = None
  _SUBSCRIBEINDICATORSREQUEST_PARAMSENTRY._serialized_options = b'8\001'
  _INDICATORSERIES._serialized_start=40
  _INDICATORSERIES._serialized_end=73
  _INDICATORUPDATEEVENT._serialized_start=76
  _INDICATORUPDATEEVENT._serialized_end=334
  _INDICATORUPDATEEVENT_SERIESENTRY._serialized_start=264
  _INDICATORUPDATEEVENT_SERIESENTRY._serialized_end=334
  _SUBSCRIBEINDICATORSREQUEST._serialized_start=337
  _SUBSCRIBEINDICATORSREQUEST._serialized_end=534
  _SUBSCRIBEINDICATORSREQUEST_PARAMSENTRY._serialized_start=489
  _SUBSCRIBEINDICATORSREQUEST_PARAMSENTRY._serialized_end=534
# @@protoc_insertion_point(module_scope)
