# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream_event_command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astream_event_command.proto\x12\x06\x61nt.v1\"\x8d\x01\n\x11TradeCommandEvent\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\x12\x12\n\naccount_id\x18\n \x01(\t\x12\x0e\n\x06symbol\x18\x0b \x01(\t\x12\x14\n\x0cpayload_json\x18\x14 \x01(\t\"\xa8\x01\n\x11TradeReceiptEvent\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\x12\x12\n\naccount_id\x18\n \x01(\t\x12\x0f\n\x07retcode\x18\x14 \x01(\x05\x12\x0f\n\x07message\x18\x15 \x01(\t\x12\r\n\x05\x65rror\x18\x16 \x01(\t\x12\x0e\n\x06ticket\x18\x1e \x01(\x03\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_event_command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _TRADECOMMANDEVENT._serialized_start=39
  _TRADECOMMANDEVENT._serialized_end=180
  _TRADERECEIPTEVENT._serialized_start=183
  _TRADERECEIPTEVENT._serialized_end=351
# @@protoc_insertion_point(module_scope)
