# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_ai_query.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import system_ai_entity_pb2 as system__ai__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15system_ai_query.proto\x12\x06\x61nt.v1\x1a\x16system_ai_entity.proto\"\x1c\n\x1aListSystemAIConfigsRequest\"D\n\x1bListSystemAIConfigsResponse\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.ant.v1.SystemAIConfig\"/\n\x18GetSystemAIConfigRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\"A\n\x19GetSystemAIConfigResponse\x12$\n\x04item\x18\x01 \x01(\x0b\x32\x16.ant.v1.SystemAIConfigB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_ai_query_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LISTSYSTEMAICONFIGSREQUEST._serialized_start=57
  _LISTSYSTEMAICONFIGSREQUEST._serialized_end=85
  _LISTSYSTEMAICONFIGSRESPONSE._serialized_start=87
  _LISTSYSTEMAICONFIGSRESPONSE._serialized_end=155
  _GETSYSTEMAICONFIGREQUEST._serialized_start=157
  _GETSYSTEMAICONFIGREQUEST._serialized_end=204
  _GETSYSTEMAICONFIGRESPONSE._serialized_start=206
  _GETSYSTEMAICONFIGRESPONSE._serialized_end=271
# @@protoc_insertion_point(module_scope)
