# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_ai_requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import system_ai_query_pb2 as system__ai__query__pb2
import system_ai_update_pb2 as system__ai__update__pb2
import system_ai_probe_pb2 as system__ai__probe__pb2

from system_ai_query_pb2 import *
from system_ai_update_pb2 import *
from system_ai_probe_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18system_ai_requests.proto\x12\x06\x61nt.v1\x1a\x15system_ai_query.proto\x1a\x16system_ai_update.proto\x1a\x15system_ai_probe.protoB\"Z anttrader/gen/proto/ant/v1;antv1P\x00P\x01P\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_ai_requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
# @@protoc_insertion_point(module_scope)
