# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_ai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import system_ai_entity_pb2 as system__ai__entity__pb2
import system_ai_requests_pb2 as system__ai__requests__pb2
try:
  system__ai__query__pb2 = system__ai__requests__pb2.system__ai__query__pb2
except AttributeError:
  system__ai__query__pb2 = system__ai__requests__pb2.system_ai_query_pb2
try:
  system__ai__update__pb2 = system__ai__requests__pb2.system__ai__update__pb2
except AttributeError:
  system__ai__update__pb2 = system__ai__requests__pb2.system_ai_update_pb2
try:
  system__ai__probe__pb2 = system__ai__requests__pb2.system__ai__probe__pb2
except AttributeError:
  system__ai__probe__pb2 = system__ai__requests__pb2.system_ai_probe_pb2

from system_ai_entity_pb2 import *
from system_ai_requests_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsystem_ai.proto\x12\x06\x61nt.v1\x1a\x16system_ai_entity.proto\x1a\x18system_ai_requests.proto2\xef\x04\n\x0fSystemAIService\x12^\n\x13ListSystemAIConfigs\x12\".ant.v1.ListSystemAIConfigsRequest\x1a#.ant.v1.ListSystemAIConfigsResponse\x12X\n\x11GetSystemAIConfig\x12 .ant.v1.GetSystemAIConfigRequest\x1a!.ant.v1.GetSystemAIConfigResponse\x12\x61\n\x14UpdateSystemAIConfig\x12#.ant.v1.UpdateSystemAIConfigRequest\x1a$.ant.v1.UpdateSystemAIConfigResponse\x12\x61\n\x14UpdateSystemAISecret\x12#.ant.v1.UpdateSystemAISecretRequest\x1a$.ant.v1.UpdateSystemAISecretResponse\x12g\n\x16\x44iscoverSystemAIModels\x12%.ant.v1.DiscoverSystemAIModelsRequest\x1a&.ant.v1.DiscoverSystemAIModelsResponse\x12s\n\x1aValidateSystemAIConnection\x12).ant.v1.ValidateSystemAIConnectionRequest\x1a*.ant.v1.ValidateSystemAIConnectionResponseB\"Z anttrader/gen/proto/ant/v1;antv1P\x00P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_ai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _SYSTEMAISERVICE._serialized_start=78
  _SYSTEMAISERVICE._serialized_end=701
# @@protoc_insertion_point(module_scope)
