# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_ai_probe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15system_ai_probe.proto\x12\x06\x61nt.v1\"4\n\x1d\x44iscoverSystemAIModelsRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\"\\\n\x1e\x44iscoverSystemAIModelsResponse\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x0e\n\x06models\x18\x02 \x03(\t\x12\x15\n\rdefault_model\x18\x03 \x01(\t\"8\n!ValidateSystemAIConnectionRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\"Z\n\"ValidateSystemAIConnectionResponse\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x13\n\x0bmodel_count\x18\x03 \x01(\x05\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_ai_probe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _DISCOVERSYSTEMAIMODELSREQUEST._serialized_start=33
  _DISCOVERSYSTEMAIMODELSREQUEST._serialized_end=85
  _DISCOVERSYSTEMAIMODELSRESPONSE._serialized_start=87
  _DISCOVERSYSTEMAIMODELSRESPONSE._serialized_end=179
  _VALIDATESYSTEMAICONNECTIONREQUEST._serialized_start=181
  _VALIDATESYSTEMAICONNECTIONREQUEST._serialized_end=237
  _VALIDATESYSTEMAICONNECTIONRESPONSE._serialized_start=239
  _VALIDATESYSTEMAICONNECTIONRESPONSE._serialized_end=329
# @@protoc_insertion_point(module_scope)
