# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_ai_update.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16system_ai_update.proto\x12\x06\x61nt.v1\"\x89\x02\n\x1bUpdateSystemAIConfigRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62\x61se_url\x18\x03 \x01(\t\x12\x14\n\x0corganization\x18\x04 \x01(\t\x12\x0e\n\x06models\x18\x05 \x03(\t\x12\x15\n\rdefault_model\x18\x06 \x01(\t\x12\x13\n\x0btemperature\x18\x07 \x01(\x01\x12\x17\n\x0ftimeout_seconds\x18\x08 \x01(\x05\x12\x12\n\nmax_tokens\x18\t \x01(\x05\x12\x10\n\x08purposes\x18\n \x03(\t\x12\x13\n\x0bprimary_for\x18\x0b \x03(\t\x12\x0f\n\x07\x65nabled\x18\x0c \x01(\x08\"3\n\x1cUpdateSystemAIConfigResponse\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\"B\n\x1bUpdateSystemAISecretRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\"K\n\x1cUpdateSystemAISecretResponse\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x16\n\x0esecret_updated\x18\x02 \x01(\x08\x42\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_ai_update_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _UPDATESYSTEMAICONFIGREQUEST._serialized_start=35
  _UPDATESYSTEMAICONFIGREQUEST._serialized_end=300
  _UPDATESYSTEMAICONFIGRESPONSE._serialized_start=302
  _UPDATESYSTEMAICONFIGRESPONSE._serialized_end=353
  _UPDATESYSTEMAISECRETREQUEST._serialized_start=355
  _UPDATESYSTEMAISECRETREQUEST._serialized_end=421
  _UPDATESYSTEMAISECRETRESPONSE._serialized_start=423
  _UPDATESYSTEMAISECRETRESPONSE._serialized_end=498
# @@protoc_insertion_point(module_scope)
