# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x06\x61nt.v1\"x\n\x06Wallet\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\t\x12\x16\n\x0e\x66rozen_balance\x18\x04 \x01(\t\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x06 \x01(\t\"\xb3\x01\n\x11WalletTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07tx_type\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t\x12\x16\n\x0e\x62\x61lance_before\x18\x04 \x01(\t\x12\x15\n\rbalance_after\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x13\n\x0boperator_id\x18\x07 \x01(\t\x12\x18\n\x10\x63reated_at_ts_ms\x18\x08 \x01(\x03\"#\n\x10GetWalletRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"3\n\x11GetWalletResponse\x12\x1e\n\x06wallet\x18\x01 \x01(\x0b\x32\x0e.ant.v1.Wallet\"Q\n\x1dListWalletTransactionsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"`\n\x1eListWalletTransactionsResponse\x12/\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x19.ant.v1.WalletTransaction\x12\r\n\x05total\x18\x02 \x01(\x03\"L\n\x14\x41\x64justBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"7\n\x15\x41\x64justBalanceResponse\x12\x1e\n\x06wallet\x18\x01 \x01(\x0b\x32\x0e.ant.v1.Wallet2\x82\x02\n\rWalletService\x12@\n\tGetWallet\x12\x18.ant.v1.GetWalletRequest\x1a\x19.ant.v1.GetWalletResponse\x12\x61\n\x10ListTransactions\x12%.ant.v1.ListWalletTransactionsRequest\x1a&.ant.v1.ListWalletTransactionsResponse\x12L\n\rAdjustBalance\x12\x1c.ant.v1.AdjustBalanceRequest\x1a\x1d.ant.v1.AdjustBalanceResponseB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _WALLET._serialized_start=24
  _WALLET._serialized_end=144
  _WALLETTRANSACTION._serialized_start=147
  _WALLETTRANSACTION._serialized_end=326
  _GETWALLETREQUEST._serialized_start=328
  _GETWALLETREQUEST._serialized_end=363
  _GETWALLETRESPONSE._serialized_start=365
  _GETWALLETRESPONSE._serialized_end=416
  _LISTWALLETTRANSACTIONSREQUEST._serialized_start=418
  _LISTWALLETTRANSACTIONSREQUEST._serialized_end=499
  _LISTWALLETTRANSACTIONSRESPONSE._serialized_start=501
  _LISTWALLETTRANSACTIONSRESPONSE._serialized_end=597
  _ADJUSTBALANCEREQUEST._serialized_start=599
  _ADJUSTBALANCEREQUEST._serialized_end=675
  _ADJUSTBALANCERESPONSE._serialized_start=677
  _ADJUSTBALANCERESPONSE._serialized_end=732
  _WALLETSERVICE._serialized_start=735
  _WALLETSERVICE._serialized_end=993
# @@protoc_insertion_point(module_scope)
