// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Auth = {
  "auth": {
    "validation": {
      "loginRequired": "Please enter your email or account number"
    },
    "fields": {
      "login": "Email/Account"
    },
    "seo": {
      "login": {
        "title": "Login",
        "description": "Log in to AlphaForge to manage your MT4/MT5 trading strategies."
      },
      "register": {
        "title": "Register",
        "description": "Create a free AlphaForge account to start backtesting and auto-trading MT4/MT5 strategies."
      },
      "forgotPassword": {
        "title": "Forgot Password",
        "description": "Reset your AlphaForge account password."
      },
      "resetPassword": {
        "title": "Reset Password",
        "description": "Reset your AlphaForge account password."
      },
      "verifyEmail": {
        "title": "Verify Email",
        "description": "Verify your email address"
      }
    }
  }
} as const;
export default Auth;
