// Auto-generated by scripts/generate-missing-i18n.mjs
const ImportAnalysis = {
  "importAnalysis": {
    "execution": {
      "onBar": "Bar確定イベント駆動",
      "onInitGrid": "初期グリッド"
    },
    "sizing": {
      "fixed": "固定ロット",
      "percentBalance": "残高のパーセント"
    },
    "analyzing": "戦略構造を分析中...",
    "tradeLogicComplete": "取引ロジック完全認識",
    "guiNoiseDesc": "以下のブラインドスポットはチャート表示/ボタン機能であり、サーバー側実行時はスキップされ、取引結果に影響しません。インポート可能です。",
    "cannotImport": "自動インポート不可",
    "incompleteCoverage": "取引ロジックのカバレッジ不完全",
    "goodCoverage": "インポートカバレッジ良好",
    "goodCoverageDesc": "戦略メインロジック認識済み。インポート可能。使用前にパラメータリストを確認してください。",
    "coverageTitle": "インポートカバレッジ",
    "userActionRequired": "手動確認が必要です",
    "noBlindSpots": "確認が必要なロジックなし",
    "noBlindSpotsDesc": "全戦略ロジック自動認識済み。インポート可能。"
  }
} as const;
export default ImportAnalysis;
