// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to ja
const Monitoring = {
  "monitoring": {
    "title": "System Monitoring",
    "sseConnected": "SSE Connected",
    "streamError": "Stream Error",
    "waitingData": "Waiting for data...",
    "serviceHealth": "Service Health",
    "diskUsage": "Disk Usage",
    "goRuntime": "Go Runtime",
    "gcCount": "GC Count",
    "gcPauseAvg": "GC Pause Avg",
    "stackUsage": "Stack Usage",
    "heapMemory": "Heap Memory",
    "dbPool": "DB Connection Pool",
    "mdGateway": "MD Gateway",
    "spillFiles": "Spill Files",
    "droppedBars": "Dropped Bars",
    "droppedSignals": "Dropped Signals",
    "consumerLag": "Consumer Lag",
    "staleAccounts": "Stale Accounts",
    "deadAccounts": "Dead Accounts",
    "avgGapSec": "Avg Gap (s)",
    "maxGapSec": "Max Gap (s)",
    "dlq": "Dead Letter Queue (DLQ)",
    "parseErrors": "Parse Errors",
    "bidGtAsk": "Bid>Ask",
    "pushInterval": "Last update"
  }
} as const;
export default Monitoring;
