// Auto-generated by scripts/generate-missing-i18n.mjs
const Monitoring = {
  "monitoring": {
    "title": "システム監視",
    "sseConnected": "SSE接続済み",
    "streamError": "ストリームエラー",
    "waitingData": "データ待機中...",
    "serviceHealth": "サービス健全性",
    "diskUsage": "ディスク使用量",
    "goRuntime": "Goランタイム",
    "gcCount": "GC回数",
    "gcPauseAvg": "GC平均一時停止",
    "stackUsage": "スタック使用量",
    "heapMemory": "ヒープメモリ",
    "dbPool": "DB接続プール",
    "mdGateway": "MDゲートウェイ",
    "spillFiles": "スピルファイル",
    "droppedBars": "ドロップバー",
    "droppedSignals": "ドロップシグナル",
    "consumerLag": "コンシューマ遅延",
    "staleAccounts": "古いアカウント",
    "deadAccounts": "停止アカウント",
    "avgGapSec": "平均ギャップ (秒)",
    "maxGapSec": "最大ギャップ (秒)",
    "dlq": "デッドレター_queue (DLQ)",
    "parseErrors": "解析エラー",
    "bidGtAsk": "Bid>Ask",
    "pushInterval": "最終更新"
  }
} as const;
export default Monitoring;
