// Auto-generated by scripts/generate-missing-i18n.mjs
const Notifications = {
  "notifications": {
    "prefs": {
      "saveFailed": "設定の保存に失敗",
      "newStrategy": "新戦略が公開されました",
      "priceChange": "戦略価格が変更されました",
      "subExpiring": "サブスクリプションの期限が近づいています",
      "performance": "戦略パフォーマンス異常",
      "newRating": "新しい評価またはコメントを受信",
      "title": "通知設定"
    }
  }
} as const;
export default Notifications;
