// Auto-generated by scripts/generate-missing-i18n.mjs
const Onboarding = {
  "onboarding": {
    "step1": {
      "title": "アカウントを接続",
      "desc": "MT4/MT5取引アカウントを連携して開始。",
      "action": "アカウント連携"
    },
    "step2": {
      "title": "最初の戦略を作成",
      "desc": "AIを使って自然言語から取引戦略を生成。",
      "action": "ワークスペースを開く"
    },
    "step3": {
      "title": "プランをアップグレード",
      "desc": "Proでより多くのAIトークン、戦略、実盤取引を利用可能。",
      "action": "プランを見る"
    },
    "welcome": "AlphaForgeへようこそ、{{name}}さん！",
    "subtitle": "3つの簡単なステップで開始",
    "dismiss": "了解、閉じる"
  }
} as const;
export default Onboarding;
