// Auto-generated by scripts/generate-missing-i18n.mjs + manual share keys
const SharePage = {
  "sharePage": {
    "noPositions": "ポジションなし",
    "positionsLocked": "ポジションは作成者により非表示",
    "notFound": "戦略が見つからないか、利用できません",
    "backtestReturn": "バックテスト収益",
    "maxDrawdown": "最大ドローダウン",
    "livePerformance": "ライブパフォーマンス",
    "liveReturn": "ライブ収益",
    "liveMaxDD": "ライブ最大DD",
    "codePreview": "コードプレビュー"
  }
} as const;
export default SharePage;
