// Auto-generated by scripts/generate-missing-i18n.mjs
const Share = {
  "share": {
    "token": "共有リンク",
    "deleteConfirm": "この共有リンクを削除しますか？",
    "title": "共有管理",
    "createNew": "新規共有リンク作成",
    "empty": "共有リンクがまだありません"
  }
} as const;
export default Share;
