// Auto-generated by scripts/generate-missing-i18n.mjs
const Sre = {
  "sre": {
    "breakers": {
      "stateHalfOpen": "半開（プローブ中）",
      "columns": {
        "strategyId": "戦略ID",
        "totalPnl": "総損益",
        "lossPercent": "損失 %",
        "trippedAt": "トリップ時刻",
        "tripReason": "トリップ理由"
      },
      "confirmReset": "このブレーカーをリセットしますか？",
      "title": "戦略ブレーカー",
      "description": "戦略ブレーカーステータス概覧 — 異常損失を自動検出してトリップ",
      "noBreakers": "登録されたブレーカーがありません"
    },
    "canary": {
      "columns": {
        "strategyId": "戦略ID",
        "versionTag": "バージョンタグ",
        "accounts": "カナリアアカウント",
        "startAt": "開始時刻"
      },
      "confirmDelete": "このカナリア設定を削除しますか？",
      "title": "カナリア設定",
      "description": "新戦略バージョンは少数アカウントでN日間実行後、全アカウントに昇格",
      "newCanary": "新規カナリア",
      "noCanaries": "カナリア設定がありません",
      "newCanaryTitle": "新規カナリア",
      "accountIdsLabel": "カナリアアカウントID（カンマまたは改行区切り）",
      "durationDays": "カナリア日数"
    },
    "killSwitch": {
      "title": "キルスイッチ",
      "description": "ワンクリックで全取引停止 — KILL確認が必要；5分以内に取り消し可能",
      "engaged": "キルスイッチ作動 — 全取引停止中",
      "disarmed": "キルスイッチ解除 — 取引正常",
      "engagedAt": "作動時刻",
      "undo": "キルスイッチ取り消し",
      "disengage": "キルスイッチ解除",
      "engage": "キルスイッチ作動",
      "confirmTitle": "キルスイッチ作動 — 確認",
      "confirmEngage": "作動を確認",
      "confirmWarning": "すべてのアカウントの全取引活動を即座に停止します（保留中・送信済み注文含む）。理由を入力し、KILLと入力して確認してください。",
      "reasonLabel": "理由（必須）",
      "reasonPlaceholder": "例：異常な市場ボラティリティを検出、緊急全取引停止",
      "typeKill": "確認のためKILLと入力",
      "typeKillPlaceholder": "KILLと入力（大文字）"
    }
  }
} as const;
export default Sre;
