// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Subscription = {
  "subscription": {
    "subscribeSuccess": "サブスクリプションが有効化されました！",
    "charged": "引き落とし: ${res.amountCharged}, 残高: ${res.balanceAfter}",
    "insufficientBalance": "ウォレット残高が不足しています。先にチャージしてください。",
    "subscribeFailed": "サブスクリプションに失敗しました。再試行してください。",
    "cancelSuccess": "自動更新をキャンセルしました。現在の期間終了までサブスクリプションは有効です。",
    "cancelFailed": "キャンセルに失敗しました。再試行してください。",
    "changeSuccess": "プラン変更成功！",
    "changeFailed": "プラン変更に失敗しました。再試行してください。",
    "title": "サブスクリプションプラン",
    "period": "現在の期間",
    "cancelAutoRenew": "自動更新をキャンセル",
    "usageTitle": "今月の使用量",
    "aiTokens": "AI トークン",
    "activeStrategies": "アクティブ戦略",
    "runtimeMinutes": "実行時間（分）",
    "walletBalance": "ウォレット残高",
    "freeForever": "永久無料",
    "currentPlan": "現在のプラン",
    "choosePlan": "プランを選択",
    "noPlans": "利用可能なプランがありません",
    "changePlanTitle": "プラン変更",
    "subscribeTitle": "プランに登録",
    "selectBillingCycle": "請求サイクル",
    "chargeNotice": "有料プランはウォレットから引き落とされます。無料プランは無料です。",
    "seoTitle": "サブスクリプション",
    "seoDesc": "サブスクリプションプランを管理"
  }
} as const;
export default Subscription;
