# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ant/v1/strategy_signal_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ant/v1/strategy_signal_messages.proto\x12\x06\x61nt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n\x12ListSignalsRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\">\n\x13ListSignalsResponse\x12\'\n\x07signals\x18\x01 \x03(\x0b\x32\x16.ant.v1.StrategySignal\"\xcb\x02\n\x0eStrategySignal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x13\n\x0bsignal_type\x18\x05 \x01(\t\x12\x0e\n\x06volume\x18\x06 \x01(\x01\x12\r\n\x05price\x18\x07 \x01(\x01\x12\x11\n\tstop_loss\x18\x08 \x01(\x01\x12\x13\n\x0btake_profit\x18\t \x01(\x01\x12\x0e\n\x06reason\x18\n \x01(\t\x12\x0e\n\x06status\x18\x0b \x01(\t\x12\x17\n\x0f\x65xecuted_ticket\x18\x0c \x01(\x03\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x65xecuted_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\")\n\x14\x45xecuteSignalRequest\x12\x11\n\tsignal_id\x18\x01 \x01(\t\"\x95\x01\n\x15\x45xecuteSignalResponse\x12\x0e\n\x06ticket\x18\x01 \x01(\x03\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06volume\x18\x04 \x01(\x01\x12\r\n\x05price\x18\x05 \x01(\x01\x12/\n\x0b\x65xecuted_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\")\n\x14\x43onfirmSignalRequest\x12\x11\n\tsignal_id\x18\x01 \x01(\t\"(\n\x13\x43\x61ncelSignalRequest\x12\x11\n\tsignal_id\x18\x01 \x01(\tB\"Z anttrader/gen/proto/ant/v1;antv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ant.v1.strategy_signal_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z anttrader/gen/proto/ant/v1;antv1'
  _LISTSIGNALSREQUEST._serialized_start=82
  _LISTSIGNALSREQUEST._serialized_end=138
  _LISTSIGNALSRESPONSE._serialized_start=140
  _LISTSIGNALSRESPONSE._serialized_end=202
  _STRATEGYSIGNAL._serialized_start=205
  _STRATEGYSIGNAL._serialized_end=536
  _EXECUTESIGNALREQUEST._serialized_start=538
  _EXECUTESIGNALREQUEST._serialized_end=579
  _EXECUTESIGNALRESPONSE._serialized_start=582
  _EXECUTESIGNALRESPONSE._serialized_end=731
  _CONFIRMSIGNALREQUEST._serialized_start=733
  _CONFIRMSIGNALREQUEST._serialized_end=774
  _CANCELSIGNALREQUEST._serialized_start=776
  _CANCELSIGNALREQUEST._serialized_end=816
# @@protoc_insertion_point(module_scope)
