// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, mt_type, broker_company, broker_server, broker_host, login, password, alias, is_disabled, balance, credit, equity, margin, free_margin, margin_level, leverage, currency, account_method, is_investor, account_status, stream_status, mt_token, last_error, last_connected_at, last_checked_at, created_at, updated_at, account_type, mtapi_port, mtapi_token_encrypted, password_encrypted, canonical_subscribed_symbols, broker_id, broker_margin_call_pct, broker_stop_out_pct FROM mt_accounts WHERE id = $1 AND user_id = $2
`

type GetAccountParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (MtAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i MtAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MtType,
		&i.BrokerCompany,
		&i.BrokerServer,
		&i.BrokerHost,
		&i.Login,
		&i.Password,
		&i.Alias,
		&i.IsDisabled,
		&i.Balance,
		&i.Credit,
		&i.Equity,
		&i.Margin,
		&i.FreeMargin,
		&i.MarginLevel,
		&i.Leverage,
		&i.Currency,
		&i.AccountMethod,
		&i.IsInvestor,
		&i.AccountStatus,
		&i.StreamStatus,
		&i.MtToken,
		&i.LastError,
		&i.LastConnectedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountType,
		&i.MtapiPort,
		&i.MtapiTokenEncrypted,
		&i.PasswordEncrypted,
		&i.CanonicalSubscribedSymbols,
		&i.BrokerID,
		&i.BrokerMarginCallPct,
		&i.BrokerStopOutPct,
	)
	return i, err
}

const getAccountCredentials = `-- name: GetAccountCredentials :one
SELECT login, password, mt_type, broker_host FROM mt_accounts WHERE id = $1 AND user_id = $2
`

type GetAccountCredentialsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetAccountCredentialsRow struct {
	Login      string
	Password   string
	MtType     string
	BrokerHost string
}

func (q *Queries) GetAccountCredentials(ctx context.Context, arg GetAccountCredentialsParams) (GetAccountCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getAccountCredentials, arg.ID, arg.UserID)
	var i GetAccountCredentialsRow
	err := row.Scan(
		&i.Login,
		&i.Password,
		&i.MtType,
		&i.BrokerHost,
	)
	return i, err
}

const getAccountSnapshots = `-- name: GetAccountSnapshots :many
SELECT id, balance, equity, credit, margin, free_margin, margin_level, account_status FROM mt_accounts WHERE user_id = $1
`

type GetAccountSnapshotsRow struct {
	ID            pgtype.UUID
	Balance       pgtype.Numeric
	Equity        pgtype.Numeric
	Credit        pgtype.Numeric
	Margin        pgtype.Numeric
	FreeMargin    pgtype.Numeric
	MarginLevel   pgtype.Numeric
	AccountStatus string
}

func (q *Queries) GetAccountSnapshots(ctx context.Context, userID pgtype.UUID) ([]GetAccountSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, getAccountSnapshots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountSnapshotsRow
	for rows.Next() {
		var i GetAccountSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Balance,
			&i.Equity,
			&i.Credit,
			&i.Margin,
			&i.FreeMargin,
			&i.MarginLevel,
			&i.AccountStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, mt_type, broker_company, broker_server, broker_host, login, password, alias, is_disabled, balance, credit, equity, margin, free_margin, margin_level, leverage, currency, account_method, is_investor, account_status, stream_status, mt_token, last_error, last_connected_at, last_checked_at, created_at, updated_at, account_type, mtapi_port, mtapi_token_encrypted, password_encrypted, canonical_subscribed_symbols, broker_id, broker_margin_call_pct, broker_stop_out_pct FROM mt_accounts WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAccounts(ctx context.Context, userID pgtype.UUID) ([]MtAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MtAccount
	for rows.Next() {
		var i MtAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MtType,
			&i.BrokerCompany,
			&i.BrokerServer,
			&i.BrokerHost,
			&i.Login,
			&i.Password,
			&i.Alias,
			&i.IsDisabled,
			&i.Balance,
			&i.Credit,
			&i.Equity,
			&i.Margin,
			&i.FreeMargin,
			&i.MarginLevel,
			&i.Leverage,
			&i.Currency,
			&i.AccountMethod,
			&i.IsInvestor,
			&i.AccountStatus,
			&i.StreamStatus,
			&i.MtToken,
			&i.LastError,
			&i.LastConnectedAt,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountType,
			&i.MtapiPort,
			&i.MtapiTokenEncrypted,
			&i.PasswordEncrypted,
			&i.CanonicalSubscribedSymbols,
			&i.BrokerID,
			&i.BrokerMarginCallPct,
			&i.BrokerStopOutPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountMetrics = `-- name: UpdateAccountMetrics :exec
UPDATE mt_accounts SET balance = $3, equity = $4, credit = $5, margin = $6, free_margin = $7, margin_level = $8, account_status = 'connected', updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND user_id = $2
`

type UpdateAccountMetricsParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Balance     pgtype.Numeric
	Equity      pgtype.Numeric
	Credit      pgtype.Numeric
	Margin      pgtype.Numeric
	FreeMargin  pgtype.Numeric
	MarginLevel pgtype.Numeric
}

func (q *Queries) UpdateAccountMetrics(ctx context.Context, arg UpdateAccountMetricsParams) error {
	_, err := q.db.Exec(ctx, updateAccountMetrics,
		arg.ID,
		arg.UserID,
		arg.Balance,
		arg.Equity,
		arg.Credit,
		arg.Margin,
		arg.FreeMargin,
		arg.MarginLevel,
	)
	return err
}

const userOwnsAccount = `-- name: UserOwnsAccount :one
SELECT EXISTS(SELECT 1 FROM mt_accounts WHERE id = $1 AND user_id = $2) AS owns
`

type UserOwnsAccountParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UserOwnsAccount(ctx context.Context, arg UserOwnsAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, userOwnsAccount, arg.ID, arg.UserID)
	var owns bool
	err := row.Scan(&owns)
	return owns, err
}
