// Code generated by sqlc. DO NOT EDIT.
// versions: sqlc v1.31.1
// source: broker_symbols.sql

package repository

import (
	"context"
)

const getCanonical = `-- name: GetCanonical :one
SELECT canonical FROM broker_symbols WHERE broker = $1 AND symbol_raw = $2 LIMIT 1
`

func (q *Queries) GetCanonical(ctx context.Context, broker string, symbolRaw string) (string, error) {
	row := q.db.QueryRow(ctx, getCanonical, broker, symbolRaw)
	var canonical string
	err := row.Scan(&canonical)
	return canonical, err
}

const listBrokerSymbols = `-- name: ListBrokerSymbols :many
SELECT broker, symbol_raw, canonical, digits, point_value, lot_size, lot_step, lot_min, lot_max, trade_mode
FROM broker_symbols WHERE broker = $1 ORDER BY symbol_raw
`

type ListBrokerSymbolsParams struct {
	Broker string
}

type ListBrokerSymbolsRow struct {
	Broker     string
	SymbolRaw  string
	Canonical  string
	Digits     int32
	PointValue string
	LotSize    string
	LotStep    string
	LotMin     string
	LotMax     string
	TradeMode  int32
}

func (q *Queries) ListBrokerSymbols(ctx context.Context, arg ListBrokerSymbolsParams) ([]ListBrokerSymbolsRow, error) {
	rows, err := q.db.Query(ctx, listBrokerSymbols, arg.Broker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBrokerSymbolsRow
	for rows.Next() {
		var i ListBrokerSymbolsRow
		if err := rows.Scan(&i.Broker, &i.SymbolRaw, &i.Canonical, &i.Digits, &i.PointValue, &i.LotSize, &i.LotStep, &i.LotMin, &i.LotMax, &i.TradeMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
