// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broker_symbols.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCanonical = `-- name: GetCanonical :one
SELECT canonical FROM broker_symbols WHERE broker_id = $1 AND symbol_raw = $2 LIMIT 1
`

type GetCanonicalParams struct {
	BrokerID  pgtype.UUID
	SymbolRaw string
}

func (q *Queries) GetCanonical(ctx context.Context, arg GetCanonicalParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getCanonical, arg.BrokerID, arg.SymbolRaw)
	var canonical pgtype.Text
	err := row.Scan(&canonical)
	return canonical, err
}

const listBrokerSymbols = `-- name: ListBrokerSymbols :many
SELECT broker_id, symbol_raw, canonical, digits, point, tick_size, contract_size, min_lot, max_lot, lot_step, trade_mode
FROM broker_symbols
WHERE broker_id = $1
ORDER BY symbol_raw
`

type ListBrokerSymbolsRow struct {
	BrokerID     pgtype.UUID
	SymbolRaw    string
	Canonical    pgtype.Text
	Digits       pgtype.Int2
	Point        pgtype.Numeric
	TickSize     pgtype.Numeric
	ContractSize pgtype.Numeric
	MinLot       pgtype.Numeric
	MaxLot       pgtype.Numeric
	LotStep      pgtype.Numeric
	TradeMode    int16
}

func (q *Queries) ListBrokerSymbols(ctx context.Context, brokerID pgtype.UUID) ([]ListBrokerSymbolsRow, error) {
	rows, err := q.db.Query(ctx, listBrokerSymbols, brokerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBrokerSymbolsRow
	for rows.Next() {
		var i ListBrokerSymbolsRow
		if err := rows.Scan(
			&i.BrokerID,
			&i.SymbolRaw,
			&i.Canonical,
			&i.Digits,
			&i.Point,
			&i.TickSize,
			&i.ContractSize,
			&i.MinLot,
			&i.MaxLot,
			&i.LotStep,
			&i.TradeMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
