// Code generated by sqlc. DO NOT EDIT.
// source: factor_definitions.sql

package repository

import (
	"context"
)

const listFactorDefinitions = `-- name: ListFactorDefinitions :many
SELECT id, user_id, name, expression, canonicals, periods, lookback, is_active
FROM factor_definitions WHERE user_id = $1 AND is_active = true ORDER BY name
`

type ListFactorDefinitionsRow struct {
	ID         string
	UserID     string
	Name       string
	Expression string
	Canonicals []string
	Periods    []string
	Lookback   int32
	IsActive   bool
}

func (q *Queries) ListFactorDefinitions(ctx context.Context, userID string) ([]ListFactorDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listFactorDefinitions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactorDefinitionsRow
	for rows.Next() {
		var i ListFactorDefinitionsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name, &i.Expression, &i.Canonicals, &i.Periods, &i.Lookback, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getFactorDefinition = `-- name: GetFactorDefinition :one
SELECT id, user_id, name, expression, canonicals, periods, lookback, is_active
FROM factor_definitions WHERE id = $1 LIMIT 1
`

type GetFactorDefinitionRow struct {
	ID         string
	UserID     string
	Name       string
	Expression string
	Canonicals []string
	Periods    []string
	Lookback   int32
	IsActive   bool
}

func (q *Queries) GetFactorDefinition(ctx context.Context, id string) (GetFactorDefinitionRow, error) {
	row := q.db.QueryRow(ctx, getFactorDefinition, id)
	var i GetFactorDefinitionRow
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.Expression, &i.Canonicals, &i.Periods, &i.Lookback, &i.IsActive)
	return i, err
}
