// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformFactor = `-- name: GetPlatformFactor :one
SELECT id, name, expression, canonicals, periods, lookback FROM platform_factors WHERE name = $1 LIMIT 1
`

type GetPlatformFactorRow struct {
	ID         pgtype.UUID
	Name       string
	Expression string
	Canonicals []string
	Periods    []string
	Lookback   int32
}

func (q *Queries) GetPlatformFactor(ctx context.Context, name string) (GetPlatformFactorRow, error) {
	row := q.db.QueryRow(ctx, getPlatformFactor, name)
	var i GetPlatformFactorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Expression,
		&i.Canonicals,
		&i.Periods,
		&i.Lookback,
	)
	return i, err
}

const listPlatformStrategies = `-- name: ListPlatformStrategies :many
SELECT id, name, description, expression, category FROM platform_strategies WHERE is_official = true ORDER BY name
`

type ListPlatformStrategiesRow struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Expression  string
	Category    string
}

func (q *Queries) ListPlatformStrategies(ctx context.Context) ([]ListPlatformStrategiesRow, error) {
	rows, err := q.db.Query(ctx, listPlatformStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformStrategiesRow
	for rows.Next() {
		var i ListPlatformStrategiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Expression,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT id, target_user_id, target_strategy_id, kind FROM user_subscriptions WHERE subscriber_user_id = $1 AND active = true
`

type ListUserSubscriptionsRow struct {
	ID               pgtype.UUID
	TargetUserID     pgtype.UUID
	TargetStrategyID pgtype.UUID
	Kind             string
}

func (q *Queries) ListUserSubscriptions(ctx context.Context, subscriberUserID pgtype.UUID) ([]ListUserSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSubscriptions, subscriberUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSubscriptionsRow
	for rows.Next() {
		var i ListUserSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetUserID,
			&i.TargetStrategyID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
