// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MtAccount struct {
	ID                         pgtype.UUID
	UserID                     pgtype.UUID
	MtType                     string
	BrokerCompany              pgtype.Text
	BrokerServer               pgtype.Text
	BrokerHost                 string
	Login                      string
	Password                   string
	Alias                      pgtype.Text
	IsDisabled                 pgtype.Bool
	Balance                    pgtype.Numeric
	Credit                     pgtype.Numeric
	Equity                     pgtype.Numeric
	Margin                     pgtype.Numeric
	FreeMargin                 pgtype.Numeric
	MarginLevel                pgtype.Numeric
	Leverage                   pgtype.Int4
	Currency                   pgtype.Text
	AccountMethod              pgtype.Text
	IsInvestor                 pgtype.Bool
	AccountStatus              string
	StreamStatus               string
	MtToken                    pgtype.Text
	LastError                  pgtype.Text
	LastConnectedAt            pgtype.Timestamp
	LastCheckedAt              pgtype.Timestamp
	CreatedAt                  pgtype.Timestamp
	UpdatedAt                  pgtype.Timestamp
	AccountType                pgtype.Text
	MtapiPort                  string
	MtapiTokenEncrypted        []byte
	PasswordEncrypted          []byte
	CanonicalSubscribedSymbols []string
	BrokerID                   pgtype.UUID
	BrokerMarginCallPct        float32
	BrokerStopOutPct           float32
}
