title: 'インジケーターカタログ'
param_key: 'キー'
param_label: 'ラベル'
param_type: 'タイプ'
param_default: 'デフォルト'
param_range: '範囲'
param_description: '説明'
risk_params_title: 'リスクパラメータ'
risk_params_desc: '組み込みリスク管理パラメータ'
indicators_title: 'インジケーター'
risk_section_title: 'リスク管理'
