title: '指標目錄'
param_key: '鍵'
param_label: '標籤'
param_type: '類型'
param_default: '預設值'
param_range: '範圍'
param_description: '描述'
risk_params_title: '風險參數'
risk_params_desc: '內建風險控制參數'
indicators_title: '指標'
risk_section_title: '風險控制'
