account_id: '口座ID'
action: '操作'
connection_logs: '接続ログ'
cost: 'コスト'
date_range: '日付範囲'
details: '詳細'
duration: '継続時間'
error: 'エラー'
event_type: 'イベント種別'
example_symbol_placeholder: '例: XAUUSD'
execution_logs: '実行ログ'
execution_price: '約定価格'
failed: '失敗'
ip: 'IP'
load_failed: 'ログの読み込みに失敗しました'
login_id: 'ログインID'
message: 'メッセージ'
module: 'モジュール'
operation_logs: '操作ログ'
order_history: '注文履歴'
order_table_close: '決済値'
order_table_lots: 'ロット'
order_table_open: '建値'
order_table_ticket: 'チケット'
order_table_type: 'タイプ'
period: '時間足'
product: '銘柄'
profit: '損益'
request_id: 'リクエストID'
reset: 'リセット'
result: '結果'
risk_code: 'リスクコード'
risk_log_quick_filter: 'リスクログクイックフィルター'
search: '検索'
server: 'サーバー'
signal: 'シグナル'
signal_price: 'シグナル価格'
status: 'ステータス'
success: '成功'
symbol: '銘柄'
time: '時間'
trigger_source: 'トリガーソース'
