account_id: 'Account ID'
action: 'Action'
connection_logs: 'Connection logs'
cost: 'Cost'
date_range: 'Date range'
details: 'Details'
duration: 'Duration'
error: 'Error'
event_type: 'Event type'
example_symbol_placeholder: 'e.g. EURUSD'
execution_logs: 'Execution logs'
execution_price: 'Execution price'
failed: 'Failed'
ip: 'IP'
load_failed: 'Failed to load logs'
login_id: 'Login ID'
message: 'Message'
module: 'Module'
operation_logs: 'Operation logs'
order_history: 'Order history'
order_table_close: 'Close'
order_table_lots: 'Lots'
order_table_open: 'Open'
order_table_ticket: 'Ticket'
order_table_type: 'Type'
period: 'Period'
product: 'Product'
profit: 'P/L'
request_id: 'Request ID'
reset: 'Reset'
result: 'Result'
risk_code: 'Risk Code'
risk_log_quick_filter: 'Risk Log Quick Filter'
search: 'Search'
server: 'Server'
signal: 'Signal'
signal_price: 'Signal price'
status: 'Status'
success: 'Success'
symbol: 'Symbol'
time: 'Time'
trigger_source: 'Trigger Source'
