clear_drawings: '清除所有标注'
drawing_extended_line: '延长线'
drawing_fibonacci: '斐波那契回撤'
drawing_horizontal_line: '水平线'
drawing_measure: '测量 (Shift+拖拽)'
drawing_parallel_channel: '平行通道'
drawing_price_channel: '价格通道'
drawing_price_line: '价格线'
drawing_ray: '射线'
drawing_trend_line: '趋势线'
drawing_vertical_line: '垂直线'
hide: '隐藏'
remove: '移除'
settings: '设置'
show: '显示'
