category__f_u_t_u_r_e__d_a_t_a__l_e_a_k: '未来数据泄露'
category__m_i_s_s_i_n_g__p_a_r_a_m: '缺少参数'
category__n_d_a_r_r_a_y__p_a_n_d_a_s__m_i_s_u_s_e: 'ndarray/pandas 误用'
category__n_o__e_n_t_r_y__p_c_t: '缺少入场百分比'
category__n_o__s_t_o_p__a_n_d__t_a_k_e__p_r_o_f_i_t: '缺少止损/止盈'
category__u_n_r_e_a_d__p_a_r_a_m: '未读取参数'
