category_f_u_t_u_r_e_d_a_t_a_l_e_a_k: '未来データ漏洩'
category_m_i_s_s_i_n_g_p_a_r_a_m: '不足パラメータ'
category_n_d_a_r_r_a_y_p_a_n_d_a_s_m_i_s_u_s_e: 'ndarray/pandas誤用'
category_n_o_e_n_t_r_y_p_c_t: 'エントリー%不足'
category_n_o_s_t_o_p_a_n_d_t_a_k_e_p_r_o_f_i_t: '損切り/利確不足'
category_u_n_r_e_a_d_p_a_r_a_m: '未読取パラメータ'
