category__f_u_t_u_r_e__d_a_t_a__l_e_a_k: '未来データ漏洩'
category__m_i_s_s_i_n_g__p_a_r_a_m: '不足パラメータ'
category__n_d_a_r_r_a_y__p_a_n_d_a_s__m_i_s_u_s_e: 'ndarray/pandas誤用'
category__n_o__e_n_t_r_y__p_c_t: 'エントリー%不足'
category__n_o__s_t_o_p__a_n_d__t_a_k_e__p_r_o_f_i_t: '損切り/利確不足'
category__u_n_r_e_a_d__p_a_r_a_m: '未読取パラメータ'
