clear_drawings: '清除所有標註'
drawing_extended_line: '延長線'
drawing_fibonacci: '斐波那契回撤'
drawing_horizontal_line: '水平線'
drawing_measure: '測量 (Shift+拖曳)'
drawing_parallel_channel: '平行通道'
drawing_price_channel: '價格通道'
drawing_price_line: '價格線'
drawing_ray: '射線'
drawing_trend_line: '趨勢線'
drawing_vertical_line: '垂直線'
hide: '隱藏'
remove: '移除'
settings: '設定'
show: '顯示'
