clear_drawings: '描画を全て消去'
drawing_extended_line: '延長線'
drawing_fibonacci: 'フィボナッチリトレースメント'
drawing_horizontal_line: '水平線'
drawing_measure: '測定 (Shift+ドラッグ)'
drawing_parallel_channel: '平行チャネル'
drawing_price_channel: 'プライスチャネル'
drawing_price_line: 'プライスライン'
drawing_ray: 'レイ'
drawing_trend_line: 'トレンドライン'
drawing_vertical_line: '垂直線'
hide: '非表示'
remove: '削除'
settings: '設定'
show: '表示'
