annual_return: '年化報酬'
equity_curve: '淨值曲線'
max_drawdown: '最大回撤'
sharpe: '夏普比率'
total_return: '總報酬'
total_trades: '總交易數'
trade_log: '交易紀錄'
trade_price: '價格'
trade_side: '方向'
trade_time: '時間'
trade_volume: '手數'
win_rate: '勝率'
backtest_records: '回測記錄'
