annual_return: '年化收益'
equity_curve: '净值曲线'
max_drawdown: '最大回撤'
sharpe: '夏普比率'
total_return: '总收益'
total_trades: '总交易数'
trade_log: '交易记录'
trade_price: '价格'
trade_side: '方向'
trade_time: '时间'
trade_volume: '手数'
win_rate: '胜率'
backtest_records: '回测记录'
