action_cleanup: '清理'
action_register: '註冊'
action_restart: '重启'
action_start: '啟動'
action_stop: '停止'
exec_status_completed: '已完成'
exec_status_failed: '失敗'
exec_status_pending: '待檢測'
exec_status_running: '運行中'
exec_status_skipped: '已略過'
exec_status_stopped: '已停止'
exec_status_success: '成功'
exec_table_action: '操作'
exec_table_duration_ms: '耗時(ms)'
exec_table_error: '錯誤'
exec_table_execute: '執行'
exec_table_status: '狀態'
exec_table_time: '時間'
messages_missing_schedule_id: '缺少排程 ID'
operation_status_failed: '失敗'
operation_status_running: '運行中'
operation_status_success: '成功'
order_side_buy: '市價買入'
order_side_buy_limit: '限價買入'
order_side_buy_stop: '突破買入'
order_side_buy_stop_limit: '限價突破買'
order_side_close: '平倉'
order_side_sell: '市價賣出'
order_side_sell_limit: '限價賣出'
order_side_sell_stop: '突破賣出'
order_side_sell_stop_limit: '卖出止損限价'
orders_table_close_price: '平倉價'
orders_table_lots: '手數(Lot)'
orders_table_open_price: '開倉價'
orders_table_profit: '盈虧'
orders_table_side: '方向'
orders_table_symbol: '品種'
orders_table_ticket: '訂單號'
orders_table_time: '時間'
schedule_id_label: '排程ID:'
status_failed: '失敗'
status_success: '成功'
summary_enable_count: '啟用次數'
summary_last_error: '最近錯誤'
summary_last_run: '最後運行時間'
summary_name: '名稱'
summary_status: '狀態'
summary_trade: '交易'
tabs_exec: '運行記錄'
tabs_exec_logs: '执行日誌'
tabs_order_logs: '訂單日志'
tabs_orders: '交易記錄'
title: '記錄'
title_with_name: '記錄 - {{name}}'
