clear_drawings: 'Clear All Drawings'
drawing_extended_line: 'Extended Line'
drawing_fibonacci: 'Fibonacci Retracement'
drawing_horizontal_line: 'Horizontal Line'
drawing_measure: 'Measure (Shift+drag)'
drawing_parallel_channel: 'Parallel Channel'
drawing_price_channel: 'Price Channel'
drawing_price_line: 'Price Line'
drawing_ray: 'Ray'
drawing_trend_line: 'Trend Line'
drawing_vertical_line: 'Vertical Line'
hide: 'Hide'
remove: 'Remove'
settings: 'Settings'
show: 'Show'
