clear_drawings: 'Xóa Tất Cả Bản Vẽ'
drawing_extended_line: 'Đường Kéo Dài'
drawing_fibonacci: 'Fibonacci Retracement'
drawing_horizontal_line: 'Đường Ngang'
drawing_measure: 'Đo lường (Shift+kéo)'
drawing_parallel_channel: 'Kênh Song Song'
drawing_price_channel: 'Kênh Giá'
drawing_price_line: 'Đường Giá'
drawing_ray: 'Tia'
drawing_trend_line: 'Đường Xu hướng'
drawing_vertical_line: 'Đường Dọc'
hide: 'Ẩn'
remove: 'Xóa'
settings: 'Cài Đặt'
show: 'Hiện'
