#!/usr/bin/env npx tsx
/**
 * i18n-build — textproto → i18next resources + TS key constants
 *
 * For each section in SECTIONS:
 *   1. Reads proto/ant/v1/i18n/strategy_{section}_{locale}.textproto
 *   2. Reads proto/ant/v1/i18n/strategy_{section}_map.json  (field→i18n path mappings)
 *   3. Outputs:
 *      a. frontend/src/i18n/resources/{locale}/strategy_{section}.ts
 *      b. frontend/src/gen/ant/v1/i18n/strategy_{section}_keys.ts
 *
 * Usage: npx tsx scripts/i18n-build.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const PROTO_DIR = path.resolve(__dirname, '..', 'proto', 'ant', 'v1', 'i18n');
const OUT_RESOURCES = path.resolve(__dirname, '..', 'frontend', 'src', 'i18n', 'resources');
const OUT_KEYS = path.resolve(__dirname, '..', 'frontend', 'src', 'gen', 'ant', 'v1', 'i18n');

const LOCALES = ['en', 'zh-cn', 'zh-tw', 'ja', 'vi'] as const;

const SECTIONS = [
  // strategy sections
  'strategy_workspace',
  'strategy_backtest_params',
  'strategy_tuning',
  'strategy_ai',
  'strategy_backtest',
  'strategy_code_assist',
  'strategy_validate',
  'strategy_code_quality',
  'strategy_code_editor',
  'strategy_chart_tools',
  'strategy_quick_trade_section',
  'strategy_library',
  'strategy_templates',
  'strategy_experiment',
  'strategy_market_regime',
  'strategy_asset',
  'strategy_asset_analysis',
  'strategy_backtest_run',
  'strategy_schedules',
  'strategy_schedule_logs',
  'strategy_gen',
  'strategy_ai_chat',
  'strategy_paper',
  'strategy_default_templates',
  // non-strategy sections
  'accounts',
  'ai_core',
  'ai_settings',
  'ai_wizard',
  'ai_store',
  'base',
  'dashboard',
  'trading',
  'analytics',
  'admin',
  'logs',
  'errors',
] as const;

// ── Types ──

interface FieldMap {
  prefix: string;
  fields: Record<string, string>;  // proto_field_name → i18n_relative_path
}

// ── Parse textproto ──

function parseTextproto(content: string): Map<string, string> {
  const fields = new Map<string, string>();
  for (const line of content.split('\n')) {
    const m = line.match(/^(\w+):\s*'((?:[^'\\]|\\.)*)'\s*$/);
    if (m) {
      fields.set(m[1], m[2].replace(/\\'/g, "'"));
    }
  }
  return fields;
}

// ── Build i18next resource ──

function setNested(obj: Record<string, unknown>, path: string, value: string): void {
  const parts = path.split('.');
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!current[parts[i]]) current[parts[i]] = {};
    current = current[parts[i]] as Record<string, unknown>;
  }
  current[parts[parts.length - 1]] = value;
}

function buildI18nextResource(
  fields: Map<string, string>,
  fieldMap: FieldMap,
): Record<string, unknown> {
  // Sort by path depth descending — nested keys (a.b.c) must be set before
  // parent keys (a.b) to avoid overwriting objects with strings.
  const sortedFields = Object.entries(fieldMap.fields)
    .sort(([, a], [, b]) => (b.match(/\./g) || []).length - (a.match(/\./g) || []).length);

  if (fieldMap.prefix === '__root__') {
    // Root-level keys (base.ts) — no prefix nesting
    const resource: Record<string, unknown> = {};
    for (const [protoField, i18nRelPath] of sortedFields) {
      const value = fields.get(protoField);
      if (value !== undefined) {
        setNested(resource, i18nRelPath, value);
      }
    }
    return resource;
  }

  // Build nested object from the prefix path
  const prefixParts = fieldMap.prefix.split('.');
  const resource: Record<string, unknown> = {};
  let current = resource;
  for (const part of prefixParts) {
    current[part] = {};
    current = current[part] as Record<string, unknown>;
  }

  // Fill in translations — sorted by depth so nested keys come before parent keys
  for (const [protoField, i18nRelPath] of sortedFields) {
    const value = fields.get(protoField);
    if (value !== undefined) {
      setNested(current, i18nRelPath, value);
    }
  }

  return resource;
}

// ── Generate TS key constants ──

function toPascalCase(snake: string): string {
  return snake
    .split('_')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function buildKeyConstants(section: string, fieldMap: FieldMap): string {
  const constName = toPascalCase(section).toUpperCase() + '_KEYS';
  const typeName = toPascalCase(section) + 'Key';

  let ts = `// Auto-generated by scripts/i18n-build.ts — DO NOT EDIT\n`;
  ts += `// Source: proto/ant/v1/i18n/${section}.proto\n\n`;

  // Individual key constants
  for (const [protoField, i18nRelPath] of Object.entries(fieldMap.fields)) {
    const fullPath = fieldMap.prefix === '__root__' ? i18nRelPath : `${fieldMap.prefix}.${i18nRelPath}`;
    const constName = protoField.toUpperCase() + '_KEY';
    ts += `/** ${i18nRelPath} */\n`;
    ts += `export const ${constName} = '${fullPath}' as const;\n\n`;
  }

  // Keys object
  ts += `export const ${constName} = {\n`;
  for (const [protoField, i18nRelPath] of Object.entries(fieldMap.fields)) {
    const fullPath = `${fieldMap.prefix}.${i18nRelPath}`;
    ts += `  ${protoField}: '${fullPath}',\n`;
  }
  ts += `} as const;\n\n`;
  ts += `export type ${typeName} = typeof ${constName}[keyof typeof ${constName}];\n`;

  return ts;
}

// ── Main ──

function main(): void {
  console.log('[i18n-build] Starting...');
  fs.mkdirSync(OUT_KEYS, { recursive: true });

  for (const section of SECTIONS) {
    // Load field map
    const mapPath = path.join(PROTO_DIR, `${section}_map.json`);
    if (!fs.existsSync(mapPath)) {
      console.error(`  ✗ Missing field map: ${mapPath}`);
      process.exit(1);
    }
    const fieldMap: FieldMap = JSON.parse(fs.readFileSync(mapPath, 'utf-8'));

    // 1. Generate key constants
    const keyTs = buildKeyConstants(section, fieldMap);
    const keyPath = path.join(OUT_KEYS, `${section}_keys.ts`);
    fs.writeFileSync(keyPath, keyTs);
    console.log(`  ${section}: keys → ${path.relative(process.cwd(), keyPath)}`);

    // 2. Generate i18next resources for each locale
    for (const locale of LOCALES) {
      const tpPath = path.join(PROTO_DIR, `${section}_${locale}.textproto`);
      if (!fs.existsSync(tpPath)) {
        console.error(`  ✗ Missing textproto: ${tpPath}`);
        process.exit(1);
      }

      const content = fs.readFileSync(tpPath, 'utf-8');
      const fields = parseTextproto(content);
      if (fields.size === 0) {
        console.error(`  ✗ Empty textproto: ${tpPath}`);
        process.exit(1);
      }

      const resource = buildI18nextResource(fields, fieldMap);
      const outDir = path.join(OUT_RESOURCES, locale);
      fs.mkdirSync(outDir, { recursive: true });
      const outPath = path.join(outDir, `${section}.ts`);

      const camelName = toPascalCase(section);
      const resourceTs =
        `// Auto-generated from proto/ant/v1/i18n/${section}_${locale}.textproto\n` +
        `// DO NOT EDIT MANUALLY — run: npx tsx scripts/i18n-build.ts\n` +
        `const ${camelName} = ${JSON.stringify(resource, null, 2)} as const;\n` +
        `export default ${camelName};\n`;

      fs.writeFileSync(outPath, resourceTs);
    }
    console.log(`         resources → 5 locales`);
  }

  console.log(`[i18n-build] Done. ${SECTIONS.length} sections processed.`);
}

main();
