// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Auth = {
  "auth": {
    "validation": {
      "loginRequired": "請輸入電子郵件或帳號編號"
    },
    "fields": {
      "login": "電子郵件/帳號"
    },
    "seo": {
      "login": {
        "title": "登入",
        "description": "登入 AlphaForge 管理您的 MT4/MT5 交易策略。"
      },
      "register": {
        "title": "註冊",
        "description": "建立免費的 AlphaForge 帳號，開始回測和自動交易 MT4/MT5 策略。"
      },
      "forgotPassword": {
        "title": "忘記密碼",
        "description": "重設您的 AlphaForge 帳號密碼。"
      },
      "resetPassword": {
        "title": "重設密碼",
        "description": "重設您的 AlphaForge 帳號密碼。"
      },
      "verifyEmail": {
        "title": "驗證電子郵件",
        "description": "驗證您的電子郵件地址"
      }
    }
  }
} as const;
export default Auth;
