// Auto-generated by scripts/generate-missing-i18n.mjs + manual Seo keys
const Auth = {
  "auth": {
    "validation": {
      "loginRequired": "請輸入郵箱或賬號編號"
    },
    "fields": {
      "login": "郵箱/賬號"
    },
    "seo": {
      "login": {
        "title": "登入",
        "description": "登入 AlphaForge 管理您的 MT4/MT5 交易策略。"
      },
      "register": {
        "title": "註冊",
        "description": "建立免費的 AlphaForge 賬戶，開始回測和自動交易 MT4/MT5 策略。"
      },
      "forgotPassword": {
        "title": "忘記密碼",
        "description": "重置您的 AlphaForge 賬戶密碼。"
      },
      "resetPassword": {
        "title": "重置密碼",
        "description": "重置您的 AlphaForge 賬戶密碼。"
      },
      "verifyEmail": {
        "title": "驗證郵箱",
        "description": "驗證您的郵箱地址"
      }
    }
  }
} as const;
export default Auth;
