// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to zh-tw
const Common = {
  "common": {
    "copied": "複製全部",
    "deleteFailed": "刪除失敗",
    "operationFailed": "操作失敗",
    "saveSuccess": "儲存成功",
    "refresh": "重新整理",
    "refresh": "重新整理",
    "loading": "載入中...",
    "noData": "未找到日誌",
    "confirm": "確認",
    "confirm": "確認",
    "cancel": "取消"
  }
} as const;
export default Common;
