// Auto-generated by scripts/generate-missing-i18n.mjs
const ImportAnalysis = {
  "importAnalysis": {
    "execution": {
      "onBar": "Bar 收盤事件驅動",
      "onInitGrid": "初始化網格"
    },
    "sizing": {
      "fixed": "固定手數",
      "percentBalance": "餘額百分比"
    },
    "analyzing": "正在分析策略結構...",
    "tradeLogicComplete": "交易邏輯已完全識別",
    "guiNoiseDesc": "以下盲區為圖表顯示/按鈕功能，服務端執行時跳過，不影響交易結果。可安全匯入。",
    "emptyAnalysisDesc": "未識別到任何策略邏輯。源碼可能不完整、使用了不同語言，請嘗試 AI 翻譯。",
    "cannotImport": "無法自動匯入",
    "incompleteCoverage": "交易邏輯覆蓋不完整",
    "goodCoverage": "匯入覆蓋良好",
    "goodCoverageDesc": "策略主要邏輯已識別。可安全匯入。使用前請檢查引數列表。",
    "coverageTitle": "匯入覆蓋率",
    "userActionRequired": "需要您手動確認",
    "noBlindSpots": "無需確認的邏輯",
    "noBlindSpotsDesc": "所有策略邏輯已自動識別。可安全匯入。"
  }
} as const;
export default ImportAnalysis;
