// Auto-generated by scripts/generate-missing-i18n.mjs
const Market = {
  "market": {
    "allSymbols": "全部品種",
    "selectSymbol": "選擇品種",
    "loadingSymbols": "未找到品種"
  }
} as const;
export default Market;
