// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to zh-tw
const Market = {
  "market": {
    "selectSymbol": "選擇品種",
    "loadingSymbols": "未找到品種"
  }
  }
} as const;
export default Market;
