// Auto-generated by scripts/generate-missing-i18n.mjs
const Monitoring = {
  "monitoring": {
    "title": "系統監控",
    "sseConnected": "SSE 已連線",
    "streamError": "流錯誤",
    "waitingData": "等待資料...",
    "serviceHealth": "服務健康",
    "diskUsage": "磁碟使用",
    "goRuntime": "Go 執行時",
    "gcCount": "GC 次數",
    "gcPauseAvg": "GC 平均暫停",
    "stackUsage": "棧使用",
    "heapMemory": "堆記憶體",
    "dbPool": "資料庫連線池",
    "mdGateway": "行情閘道器",
    "spillFiles": "溢位檔案",
    "droppedBars": "丟棄 K 線",
    "droppedSignals": "丟棄訊號",
    "consumerLag": "消費者延遲",
    "staleAccounts": "過期賬號",
    "deadAccounts": "死賬號",
    "avgGapSec": "平均間隔 (秒)",
    "maxGapSec": "最大間隔 (秒)",
    "dlq": "死信佇列 (DLQ)",
    "parseErrors": "解析錯誤",
    "bidGtAsk": "買價>賣價",
    "pushInterval": "最後更新"
  }
} as const;
export default Monitoring;
