// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to zh-tw
const Notifications = {
  "notifications": {
    "prefs": {
      "newStrategy": "新策略已釋出",
      "priceChange": "策略價格已變更",
      "subExpiring": "訂閱即將到期",
      "performance": "策略表現異常",
      "newRating": "收到新評分或評論",
      "title": "通知偏好設定"
    }
    }
  }
} as const;
export default Notifications;
