// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to zh-tw
const Notifications = {
  "notifications": {
    "prefs": {
      "saveFailed": "Failed to save preferences",
      "newStrategy": "New strategy published",
      "priceChange": "Strategy price changed",
      "subExpiring": "Subscription expiring soon",
      "performance": "Strategy performance anomaly",
      "newRating": "New rating or comment received",
      "title": "Notification Preferences"
    }
  }
} as const;
export default Notifications;
