// Auto-generated by scripts/generate-missing-i18n.mjs
const Onboarding = {
  "onboarding": {
    "step1": {
      "title": "連線您的賬戶",
      "desc": "繫結您的 MT4/MT5 交易賬戶以開始。",
      "action": "繫結賬戶"
    },
    "step2": {
      "title": "建立您的第一個策略",
      "desc": "使用 AI 從自然語言生成交易策略。",
      "action": "開啟工作區"
    },
    "step3": {
      "title": "升級您的套餐",
      "desc": "解鎖更多 AI 代幣、策略和實盤交易功能。",
      "action": "檢視套餐"
    },
    "welcome": "歡迎使用 AlphaForge，{{name}}！",
    "subtitle": "3 個簡單步驟即可開始",
    "dismiss": "知道了，關閉"
  }
} as const;
export default Onboarding;
