// Auto-generated by scripts/generate-missing-i18n.mjs
// TODO: Translate to zh-tw
const Share = {
  "share": {
    "deleteConfirm": "刪除此分享連結？",
    "title": "分享管理",
    "createNew": "建立新分享連結",
    "empty": "暫無分享連結"
  }
  }
} as const;
export default Share;
