// Auto-generated by scripts/generate-missing-i18n.mjs + manual share keys
const SharePage = {
  "sharePage": {
    "noPositions": "無持倉",
    "positionsLocked": "持倉已被建立者隱藏",
    "notFound": "策略未找到或已不可用",
    "backtestReturn": "回測收益",
    "maxDrawdown": "最大回撤",
    "livePerformance": "實盤表現",
    "liveReturn": "實盤收益",
    "liveMaxDD": "實盤最大回撤",
    "codePreview": "程式碼預覽"
  }
} as const;
export default SharePage;
