// Auto-generated by scripts/generate-missing-i18n.mjs
const Sre = {
  "sre": {
    "breakers": {
      "stateHalfOpen": "半開（探測中）",
      "columns": {
        "strategyId": "策略 ID",
        "totalPnl": "總盈虧",
        "lossPercent": "虧損 %",
        "trippedAt": "熔斷時間",
        "tripReason": "熔斷原因"
      },
      "confirmReset": "重置此熔斷器？",
      "title": "策略熔斷器",
      "description": "策略熔斷器狀態總覽 — 自動檢測異常虧損並熔斷",
      "noBreakers": "無已註冊熔斷器"
    },
    "canary": {
      "columns": {
        "strategyId": "策略 ID",
        "versionTag": "版本標籤",
        "accounts": "金絲雀賬號",
        "startAt": "開始時間"
      },
      "confirmDelete": "刪除此金絲雀配置？",
      "title": "金絲雀配置",
      "description": "新策略版本先在少數賬號上執行 N 天，再推廣到全部賬號",
      "newCanary": "新建金絲雀",
      "noCanaries": "無金絲雀配置",
      "newCanaryTitle": "新建金絲雀",
      "accountIdsLabel": "金絲雀賬號 ID（逗號或換行分隔）",
      "durationDays": "金絲雀天數"
    },
    "killSwitch": {
      "title": "一鍵停止",
      "description": "一鍵停止所有交易 — 需輸入 KILL 確認；5 分鐘內可撤銷",
      "engaged": "一鍵停止已觸發 — 所有交易已停止",
      "disarmed": "一鍵停止已解除 — 交易正常",
      "engagedAt": "觸發時間",
      "undo": "撤銷一鍵停止",
      "disengage": "解除一鍵停止",
      "engage": "觸發一鍵停止",
      "confirmTitle": "觸發一鍵停止 — 確認",
      "confirmEngage": "確認觸發",
      "confirmWarning": "這將立即停止所有賬號的所有交易活動，包括待提交和已提交的訂單。請輸入原因並輸入 KILL 確認。",
      "reasonLabel": "原因（必填）",
      "reasonPlaceholder": "例如：檢測到異常市場波動，緊急停止所有交易",
      "typeKill": "輸入 KILL 確認",
      "typeKillPlaceholder": "輸入 KILL（大寫）"
    }
  }
} as const;
export default Sre;
